// ============================================================================
// Done by: Odane Robinson
// Run with: node scripts/diagram-kit/generate-example.js
//
// Demonstrates the toolkit by rebuilding the jan_q6_cheese.svg diagram
// (the sector-prism "18 degree wedge" diagram) entirely from the given
// facts - radius 12cm (drawn at 230px), height 8cm (drawn at 200px), angle
// 18 degrees - instead of hand-typed/eyeballed coordinates, then verifies
// the result against the same facts before writing anything to disk. This
// is the template to copy for building a NEW diagram from scratch; see
// public/cxc2025/jan_q6_cheese.svg's own header comment for what was wrong
// with the original hand-typed version this replaced.
// ============================================================================
const fs = require("fs");
const path = require("path");
const { polarPoint, distance, angleBetween } = require("./index");

const O = { x: 450, y: 100 };
const RADIUS = 230;
const HEIGHT = 200;
const HALF_ANGLE = 9; // 18 degree wedge, split evenly either side of vertical

const A = polarPoint(O, -HALF_ANGLE, RADIUS);
const B = polarPoint(O, HALF_ANGLE, RADIUS);
const D = { x: A.x, y: A.y + HEIGHT };
const C = { x: B.x, y: B.y + HEIGHT };

// Verify the geometry actually satisfies the given facts before writing
// anything - this is the check that would have caught the original bug
// (unequal radii, ~70 degree angle instead of 18) immediately.
const oaLen = distance(O, A);
const obLen = distance(O, B);
const wedgeAngle = angleBetween(O, A, B);
console.log(`OA = ${oaLen.toFixed(1)}px, OB = ${obLen.toFixed(1)}px (must be equal)`);
console.log(`angle AOB = ${wedgeAngle.toFixed(3)} deg (must be 18)`);

if (Math.abs(oaLen - obLen) > 1e-6) throw new Error("OA and OB are not equal length");
if (Math.abs(wedgeAngle - 18) > 1e-6) throw new Error("Wedge angle is not 18 degrees");

const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="900" height="560" viewBox="0 0 900 560">
<!--
  Done by: Odane Robinson
  Generated by scripts/diagram-kit/generate-example.js from the actual
  given facts (radius, height, 18 degree angle) rather than hand-typed
  coordinates. Regenerate with: node scripts/diagram-kit/generate-example.js
-->
<style>
text{font-family:Arial,Helvetica,sans-serif;fill:#162033}
.label{font-size:18px;font-weight:600}
.small{font-size:15px}
.line{stroke:#162033;stroke-width:3;fill:none}
</style>
<rect width="900" height="560" fill="white"/>
<path d="M${D.x.toFixed(1)} ${D.y.toFixed(1)} L${O.x} ${O.y+HEIGHT} L${C.x.toFixed(1)} ${C.y.toFixed(1)} A${RADIUS} ${RADIUS} 0 0 1 ${D.x.toFixed(1)} ${D.y.toFixed(1)} Z" fill="#e9edf3" stroke="#162033" stroke-width="2"/>
<path d="M${A.x.toFixed(1)} ${A.y.toFixed(1)} L${D.x.toFixed(1)} ${D.y.toFixed(1)} L${O.x} ${O.y} Z" fill="#eef2f7" stroke="#162033" stroke-width="3"/>
<path d="M${B.x.toFixed(1)} ${B.y.toFixed(1)} L${C.x.toFixed(1)} ${C.y.toFixed(1)} L${O.x} ${O.y} Z" fill="#e5eaf1" stroke="#162033" stroke-width="3"/>
<path d="M${O.x} ${O.y} L${A.x.toFixed(1)} ${A.y.toFixed(1)} A${RADIUS} ${RADIUS} 0 0 0 ${B.x.toFixed(1)} ${B.y.toFixed(1)} Z" fill="#f4f7fb" stroke="#162033" stroke-width="3"/>
<text x="440" y="90" class="label">O</text>
<text x="${(A.x-22).toFixed(0)}" y="${A.y.toFixed(0)}" class="label">A</text>
<text x="${(B.x+8).toFixed(0)}" y="${B.y.toFixed(0)}" class="label">B</text>
<text x="${(C.x+8).toFixed(0)}" y="${C.y.toFixed(0)}" class="label">C</text>
<text x="${(D.x-22).toFixed(0)}" y="${D.y.toFixed(0)}" class="label">D</text>
<text x="452" y="258" class="label" text-anchor="middle">18°</text>
<text x="415" y="230" class="small" text-anchor="end">12 cm</text>
<text x="500" y="430" class="small">8 cm</text>
</svg>
`;

const outPath = path.join(__dirname, "example-output.svg");
fs.writeFileSync(outPath, svg);
console.log(`\nWritten to ${outPath} - geometry verified before writing.`);
