import { SECTION_D_ELECTRICITY_MAGNETISM_LESSONS } from '../course/sectionDElectricityMagnetismLessons.mjs';
const words=s=>String(s||'').toLowerCase().replace(/[^a-z0-9Ω]+/g,' ').split(/\s+/).filter(w=>w.length>3&&!['that','with','from','this','which','when','into','than','they','their','where','what','should','would','because','about'].includes(w));
const terms=s=>[...new Set(words(s))].slice(0,6);
function criteriaFor(topic,id){const card=topic.objectiveCards?.[id]||{}, a=terms(card.inShort||card.detail), b=terms(card.detail), c=terms(card.watchOut);return [
{code:'B1',marks:1,profile:'KC',objective:id,description:`states a correct core idea for ${id}`,check:{type:'writtenConcept',any:a.length?a:[id.toLowerCase()]}},
{code:'B2',marks:1,profile:'UK',objective:id,description:`adds a relevant condition, mechanism or application for ${id}`,check:{type:'writtenConcept',any:b.length?b:a}},
{code:'B3',marks:1,profile:'UK',objective:id,description:`avoids the common misconception and gives a physically consistent statement`,check:{type:'writtenConcept',any:[...a,...b].slice(0,8),forbidden:c.slice(0,2)}}];}
const qs=[];let serial=1;for(const topic of SECTION_D_ELECTRICITY_MAGNETISM_LESSONS){for(let i=0;i<topic.objectives.length;i+=4){const group=topic.objectives.slice(i,i+4);const parts=group.map(([id,wording],j)=>({id:String.fromCharCode(97+j),marks:3,objective:id,prompt:topic.objectiveCards?.[id]?.howAsked||`Explain or apply: ${wording}`,requireDrawing:/draw|sketch|map|circuit diagram|field pattern/i.test(topic.objectiveCards?.[id]?.howAsked||wording),criteria:criteriaFor(topic,id)}));const practical=group.some(([id,wording])=>/investigate|conduct|draw|map/i.test(wording));qs.push({id:`d-${topic.id.toLowerCase()}-p2-${String(serial++).padStart(2,'0')}`,topic:topic.id,kind:practical?'data analysis':'structured',marks:parts.reduce((s,p)=>s+p.marks,0),title:`${topic.id} ${topic.title} practice ${Math.floor(i/4)+1}`,stem:`Work through the following ${topic.title.toLowerCase()} parts. Show calculations, directions, units and practical detail where the question requires them.`,parts});}}
export const SECTION_D_STRUCTURED_BANK=Object.freeze(qs);export function sectionDStructuredStats(){return{questions:SECTION_D_STRUCTURED_BANK.length,marks:SECTION_D_STRUCTURED_BANK.reduce((s,q)=>s+q.marks,0),byTopic:Object.fromEntries(SECTION_D_ELECTRICITY_MAGNETISM_LESSONS.map(t=>[t.id,SECTION_D_STRUCTURED_BANK.filter(q=>q.topic===t.id).length]))}}
