// Original CSEC-style structured and data-analysis practice for Section C.
// Drawing and graph criteria remain explicit manual checks. Typed responses are
// assessed against one-mark criteria by the shared Physics checker contract.
const c=(code,profile,objective,description,check=null,extra={})=>({code,marks:1,profile,objective,description,...(check?{check}:{}),...extra});
export const SECTION_C_STRUCTURED_BANK=Object.freeze([
{
id:'c1-p2-wave-motion-01',topic:'C1',kind:'structured',marks:15,title:'Wave motion and wave graphs',
stem:'A ripple tank produces a regular wave train. A student records both a displacement-position graph and a displacement-time graph.',parts:[
{id:'a',marks:4,objective:'C1.1',prompt:'Distinguish transverse from longitudinal waves and give one example of each.',criteria:[
c('B1','KC','C1.1','transverse vibration is perpendicular to wave travel',{type:'writtenConcept',all:['perpendicular'],any:['direction','travel']}),
c('B2','KC','C1.1','longitudinal vibration is parallel to wave travel',{type:'writtenConcept',all:['parallel'],any:['direction','travel']}),
c('B3','KC','C1.1','gives a valid transverse example',{type:'writtenConcept',any:['light','water wave','rope','electromagnetic']}),
c('B4','KC','C1.1','gives a valid longitudinal example',{type:'writtenConcept',any:['sound','slinky','compression']})]},
{id:'b',marks:5,objective:'C1.2',prompt:'The wave has frequency 8.0 Hz and wavelength 0.25 m. Calculate its speed and period.',criteria:[
c('M1','UK','C1.2','uses v = fλ',{type:'formulaUse',formula:'v=fλ'}),c('A1','UK','C1.2','obtains speed 2.0 m/s',{type:'physicsQuantity',quantity:'speed',value:2,unit:'m/s'},{depends:['M1']}),
c('M2','UK','C1.2','uses f = 1/T or T = 1/f',{type:'formulaUse',formula:'f=1/T'}),c('A2','UK','C1.2','obtains period 0.125 s',{type:'physicsQuantity',quantity:'time',value:.125,unit:'s',relativeTolerance:.002},{depends:['M2']}),
c('B1','KC','C1.2','states amplitude is maximum displacement from equilibrium',{type:'writtenConcept',all:['maximum displacement'],any:['rest','equilibrium']})]},
{id:'c',marks:4,objective:'C1.3',prompt:'Explain how wavelength, period and amplitude are obtained from the two graphs.',criteria:[
c('B1','KC','C1.3','wavelength comes from horizontal separation of equal-phase points on displacement-position graph',{type:'writtenConcept',all:['wavelength'],any:['position','distance','crest to crest']}),
c('B2','KC','C1.3','period comes from horizontal time separation on displacement-time graph',{type:'writtenConcept',all:['period'],any:['time','crest to crest']}),
c('B3','KC','C1.3','amplitude is vertical displacement from rest position',{type:'writtenConcept',all:['amplitude'],any:['rest','equilibrium','vertical']}),
c('B4','UK','C1.3','states the horizontal axis must be checked before identifying wavelength or period',{type:'writtenConcept',all:['axis'],any:['position','time']})]},
{id:'d',marks:2,objective:'C1.2',prompt:'State what happens to frequency and wavelength when the same wave source enters a medium where the wave speed is lower.',criteria:[
c('B1','UK','C1.2','frequency remains unchanged',{type:'writtenConcept',all:['frequency'],any:['same','unchanged','constant']}),c('B2','UK','C1.2','wavelength decreases when speed decreases at fixed frequency',{type:'writtenConcept',all:['wavelength'],any:['decrease','shorter']})]}
]},
{
id:'c2-p2-sound-echo-01',topic:'C2',kind:'structured',marks:15,title:'Sound, pitch and an echo',stem:'A signal generator drives a loudspeaker. A microphone and oscilloscope are used to observe the sound, and an echo is timed from a wall.',parts:[
{id:'a',marks:3,objective:'C2.1',prompt:'Describe how the loudspeaker produces and transmits sound through air.',criteria:[c('B1','KC','C2.1','loudspeaker cone vibrates',{type:'writtenConcept',all:['vibrat'],any:['cone','speaker']}),c('B2','KC','C2.1','vibration creates compressions and rarefactions',{type:'writtenConcept',any:['compression','rarefaction']}),c('B3','KC','C2.1','air particles pass the disturbance along without bulk transport',{type:'writtenConcept',all:['particle'],any:['disturbance','energy','neighbour']})]},
{id:'b',marks:4,objective:'C2.2',prompt:'Explain what changes in the oscilloscope trace when pitch is increased and when loudness is increased.',criteria:[c('B1','KC','C2.2','higher pitch means higher frequency',{type:'writtenConcept',all:['pitch','frequency'],any:['higher','increase']}),c('B2','UK','C2.2','higher frequency gives a shorter period on the time trace',{type:'writtenConcept',all:['period'],any:['shorter','decrease']}),c('B3','KC','C2.2','greater loudness is associated with greater amplitude',{type:'writtenConcept',all:['loud','amplitude'],any:['greater','increase']}),c('B4','KC','C2.2','does not confuse amplitude with frequency',{type:'writtenConcept',all:['amplitude'],any:['loudness','frequency']})]},
{id:'c',marks:5,objective:'C2.3',prompt:'An echo returns 0.72 s after a short pulse. Taking the speed of sound as 340 m/s, calculate the distance to the wall.',criteria:[c('M1','UK','C2.3','uses distance travelled = vt',{type:'formulaUse',formula:'d=vt'}),c('A1','UK','C2.3','obtains total sound path 244.8 m',{type:'physicsQuantity',quantity:'length',value:244.8,unit:'m',relativeTolerance:.002},{depends:['M1']}),c('M2','UK','C2.3','recognises the echo path is a round trip',{type:'writtenConcept',any:['there and back','round trip','twice','divide by 2']}),c('A2','UK','C2.3','obtains wall distance 122.4 m',{type:'physicsQuantity',quantity:'length',value:122.4,unit:'m',relativeTolerance:.002},{depends:['M2']}),c('B1','UK','C2.3','states why light travel time is negligible in thunder-lightning timing',{type:'writtenConcept',all:['light'],any:['much faster','negligible','3 x 10']})]},
{id:'d',marks:3,objective:'C2.1',prompt:'Explain why the sound becomes faint when the bell-jar air is pumped out even though the source continues vibrating.',criteria:[c('B1','KC','C2.1','sound requires a material medium',{type:'writtenConcept',all:['sound'],any:['medium','particles']}),c('B2','UK','C2.1','fewer air particles remain to transmit compressions and rarefactions',{type:'writtenConcept',all:['particle'],any:['fewer','removed','compression']}),c('B3','UK','C2.1','does not claim that sound travels through a perfect vacuum',{type:'writtenConcept',any:['vacuum','cannot travel','no sound']})]}
]},
{
id:'c2-p2-wave-behaviour-ultrasound-01',topic:'C2',kind:'extended response',marks:15,title:'Wave behaviour and ultrasound',stem:'Sound waves show the standard behaviours of waves and are also used at frequencies above human hearing.',parts:[
{id:'a',marks:4,objective:'C2.4',prompt:'Give one observation for each of reflection, refraction, diffraction and interference of sound.',criteria:[c('B1','KC','C2.4','reflection example such as echo',{type:'writtenConcept',any:['echo','reflection']}),c('B2','KC','C2.4','refraction example such as sound bending in temperature layers',{type:'writtenConcept',any:['refraction','night','temperature layer','bend']}),c('B3','KC','C2.4','diffraction example such as hearing around a corner',{type:'writtenConcept',any:['corner','doorway','diffraction']}),c('B4','KC','C2.4','interference example with loud and quiet positions',{type:'writtenConcept',any:['interference','loud and quiet','two speakers']})]},
{id:'b',marks:4,objective:'C2.5',prompt:'Define ultrasound and explain how it is used to locate a crack inside a metal block.',criteria:[c('B1','KC','C2.5','defines ultrasound above about 20 kHz',{type:'writtenConcept',all:['20'],any:['khz','20000','above']}),c('B2','UK','C2.5','pulse is sent into material',{type:'writtenConcept',all:['pulse'],any:['metal','material','send']}),c('B3','UK','C2.5','pulse reflects from crack or internal boundary',{type:'writtenConcept',all:['reflect'],any:['crack','boundary']}),c('B4','UK','C2.5','return time is used to infer depth or position',{type:'writtenConcept',all:['time'],any:['depth','distance','position']})]},
{id:'c',marks:4,objective:'C2.5',prompt:'Explain two reasons ultrasound is useful in prenatal imaging and describe what produces the image information.',criteria:[c('B1','KC','C2.5','states ultrasound is non-ionising',{type:'writtenConcept',any:['non ionising','non-ionising','not ionising']}),c('B2','UK','C2.5','waves reflect at boundaries between tissues',{type:'writtenConcept',all:['reflect'],any:['tissue','boundary']}),c('B3','UK','C2.5','return times or echo strengths are processed into image information',{type:'writtenConcept',any:['return time','echo','image','depth']}),c('B4','KC','C2.5','distinguishes ultrasound from X-rays',{type:'writtenConcept',any:['x ray','x-ray','ionising']})]},
{id:'d',marks:3,objective:'C2.4',prompt:'Explain why sound diffracts around a doorway much more noticeably than visible light.',criteria:[c('B1','UK','C2.4','diffraction is strong when gap size is comparable with wavelength',{type:'writtenConcept',all:['wavelength'],any:['comparable','similar','gap']}),c('B2','UK','C2.4','sound wavelengths are comparable with doorway dimensions',{type:'writtenConcept',all:['sound'],any:['doorway','long wavelength']}),c('B3','UK','C2.4','visible-light wavelengths are much smaller than doorway dimensions',{type:'writtenConcept',all:['light'],any:['much smaller','tiny','short wavelength']})]}
]},
{
id:'c3-p2-em-spectrum-01',topic:'C3',kind:'extended response',marks:15,title:'The electromagnetic spectrum',stem:'A communication and medical centre uses several regions of the electromagnetic spectrum.',parts:[
{id:'a',marks:4,objective:'C3.1',prompt:'State four properties common to electromagnetic waves.',criteria:[c('B1','KC','C3.1','transverse',{type:'writtenConcept',any:['transverse']}),c('B2','KC','C3.1','travel through vacuum',{type:'writtenConcept',any:['vacuum','no medium']}),c('B3','KC','C3.1','speed 3 × 10^8 m/s in vacuum',{type:'writtenConcept',all:['3'],any:['10^8','10 8','speed']}),c('B4','KC','C3.1','carry energy or show wave behaviours',{type:'writtenConcept',any:['energy','reflection','refraction','diffraction','interference']})]},
{id:'b',marks:4,objective:'C3.2',prompt:'Write the seven main regions in order of increasing frequency and state what happens to wavelength along the sequence.',criteria:[c('B1','KC','C3.2','starts radio, microwave, infrared',{type:'writtenConcept',all:['radio','microwave','infrared']}),c('B2','KC','C3.2','places visible then ultraviolet',{type:'writtenConcept',all:['visible','ultraviolet']}),c('B3','KC','C3.2','ends X-ray then gamma',{type:'writtenConcept',all:['x ray','gamma']}),c('B4','UK','C3.2','states wavelength decreases as frequency increases',{type:'writtenConcept',all:['wavelength','frequency'],any:['decrease','inverse','shorter']})]},
{id:'c',marks:5,objective:'C3.3',prompt:'Give a suitable source and use for any two different regions of the spectrum, and explain the physical property that makes one chosen use suitable.',criteria:[c('B1','KC','C3.3','first valid region/source pairing',{type:'writtenConcept',any:['aerial','magnetron','warm body','sun','lamp','x ray tube','radioactive']}),c('B2','KC','C3.3','first valid use',{type:'writtenConcept',any:['broadcast','cooking','phone','remote','thermal','seeing','sterilis','radiograph','cancer']}),c('B3','KC','C3.3','second valid region/source pairing',{type:'writtenConcept',any:['aerial','magnetron','warm body','sun','lamp','x ray tube','radioactive']}),c('B4','KC','C3.3','second valid use',{type:'writtenConcept',any:['broadcast','cooking','phone','remote','thermal','seeing','sterilis','radiograph','cancer']}),c('B5','UK','C3.3','links a use to a relevant absorption, penetration, reflection or energy property',{type:'writtenConcept',any:['absorb','penetrat','energy','reflect','ionis','water molecule','dense']})]},
{id:'d',marks:2,objective:'C3.1',prompt:'A radio wave and a gamma ray travel together through a vacuum. Compare their speeds.',criteria:[c('B1','KC','C3.1','states they have the same speed',{type:'writtenConcept',all:['same'],any:['speed','velocity']}),c('B2','KC','C3.1','gives approximately 3 × 10^8 m/s',{type:'physicsQuantity',quantity:'speed',value:3e8,unit:'m/s',relativeTolerance:.001})]}
]},
{
id:'c4-p2-refraction-data-01',topic:'C4',kind:'data analysis',marks:25,title:'Refraction through a glass block',stem:'A student measures the angle of refraction r for several angles of incidence i in air. The student calculates sin i and sin r and investigates Snell\'s law.',parts:[
{id:'a',marks:4,objective:'C4.8',prompt:'Describe how to trace the incident and refracted rays through a rectangular glass block using pins.',criteria:[c('B1','XS','C4.8','draws around block and a normal at the point of incidence',{type:'writtenConcept',all:['normal'],any:['draw around','outline','block']}),c('B2','XS','C4.8','places two pins along the incident ray',{type:'writtenConcept',all:['pins'],any:['incident','two']}),c('B3','XS','C4.8','aligns two more pins with images through the block',{type:'writtenConcept',all:['pins'],any:['align','images','line']}),c('B4','XS','C4.8','removes block and joins pin marks to trace ray',{type:'writtenConcept',any:['join','trace','remove block','ray']})]},
{id:'b',marks:5,objective:'C4.10',prompt:'For one reading, i = 50.0° and r = 30.7°. Calculate the refractive index of the glass.',criteria:[c('M1','UK','C4.10','uses n = sin i / sin r',{type:'formulaUse',formula:'n=sin(i)/sin(r)'}),c('M2','UK','C4.10','uses angles measured from normal',{type:'writtenConcept',all:['normal'],any:['angle','measured']}),c('M3','UK','C4.10','substitutes sin 50.0 and sin 30.7',{type:'containsValues',values:[50,30.7],needAll:true}),c('A1','UK','C4.10','obtains n approximately 1.50',{type:'physicsQuantity',quantity:'dimensionless',value:1.5,unit:'',unitRequired:false,relativeTolerance:.015},{depends:['M1']}),c('B1','KC','C4.10','states refractive index has no unit',{type:'writtenConcept',any:['no unit','dimensionless']})]},
{id:'c',marks:6,objective:'C4.10',prompt:'Plot sin i on the vertical axis against sin r on the horizontal axis for the supplied data and use the best fit line to determine n.',requireDrawing:true,criteria:[c('B1','XS','C4.10','labels horizontal axis sin r',null,{manual:true}),c('B2','XS','C4.10','labels vertical axis sin i',null,{manual:true}),c('B3','XS','C4.10','uses a sensible scale and plots points accurately',null,{manual:true}),c('B4','XS','C4.10','draws a best fit straight line',null,{manual:true}),c('M1','XS','C4.10','uses a large gradient triangle on the best fit line',null,{manual:true}),c('A1','UK','C4.10','identifies gradient as refractive index',{type:'writtenConcept',all:['gradient'],any:['refractive index','n']})]},
{id:'d',marks:4,objective:'C4.7',prompt:'State two everyday observations that demonstrate refraction and explain one of them using a change of wave speed.',criteria:[c('B1','KC','C4.7','first valid observation',{type:'writtenConcept',any:['bent pencil','pool','apparent depth','coin','glass block']}),c('B2','KC','C4.7','second valid observation',{type:'writtenConcept',any:['bent pencil','pool','apparent depth','coin','glass block']}),c('B3','UK','C4.7','states light speed changes at boundary',{type:'writtenConcept',all:['speed'],any:['change','slower','faster']}),c('B4','UK','C4.7','links speed change to bending/refraction',{type:'writtenConcept',any:['bend','refract','direction']})]},
{id:'e',marks:3,objective:'C4.8',prompt:'Name one specific source of error in the pin method and give a matching precaution.',responseFields:['error','precaution'],criteria:[c('B1','XS','C4.8','names a specific error such as parallax, pins not vertical or pins too close',{type:'writtenConcept',any:['parallax','not vertical','too close']},{field:'error'}),c('B2','XS','C4.8','gives a precaution that addresses the named error',{type:'writtenConcept',any:['eye level','vertical','far apart','spacing','careful alignment']},{field:'precaution'}),c('B3','XS','C4.8','states angles are measured from the normal',{type:'writtenConcept',all:['normal'],any:['angle','measure']},{field:'precaution'})]},
{id:'f',marks:3,objective:'C4.10',prompt:'A glass has refractive index 1.50. Calculate the speed of light in the glass.',criteria:[c('M1','UK','C4.10','uses n = c/v',{type:'formulaUse',formula:'n=c/v'}),c('M2','UK','C4.10','rearranges v = c/n and uses c = 3 × 10^8 m/s',{type:'containsValues',values:[3e8,1.5],needAll:true}),c('A1','UK','C4.10','obtains 2.0 × 10^8 m/s',{type:'physicsQuantity',quantity:'speed',value:2e8,unit:'m/s',relativeTolerance:.003},{depends:['M1']})]}
]},
{
id:'c4-p2-reflection-mirror-01',topic:'C4',kind:'structured',marks:15,title:'Straight-line light, reflection and a plane mirror',stem:'A narrow beam is directed at a plane mirror and a pinhole camera is used nearby.',parts:[
{id:'a',marks:3,objective:'C4.4',prompt:'Explain why a pinhole camera forms an inverted image.',criteria:[c('B1','KC','C4.4','light travels in straight lines',{type:'writtenConcept',all:['straight'],any:['light','ray']}),c('B2','UK','C4.4','rays from upper object points pass through pinhole to lower image points',{type:'writtenConcept',any:['top','upper','lower','cross','pinhole']}),c('B3','UK','C4.4','links crossing ray paths to inverted image',{type:'writtenConcept',all:['inverted'],any:['image','ray']})]},
{id:'b',marks:4,objective:'C4.5',prompt:'A ray makes 25° with the mirror surface. Determine the angles of incidence and reflection and state the second law of reflection.',criteria:[c('M1','UK','C4.5','converts surface angle to normal angle',{type:'containsValues',values:[25,65],needAll:true}),c('A1','UK','C4.5','angle of incidence 65°',{type:'physicsQuantity',quantity:'angle',value:65,unit:'°',relativeTolerance:.001}),c('A2','UK','C4.5','angle of reflection 65°',{type:'physicsQuantity',quantity:'angle',value:65,unit:'°',relativeTolerance:.001}),c('B1','KC','C4.5','incident ray, reflected ray and normal lie in same plane',{type:'writtenConcept',all:['incident','reflected','normal'],any:['same plane','one plane']})]},
{id:'c',marks:5,objective:'C4.6',prompt:'Describe the image formed by a plane mirror and explain why it is virtual.',criteria:[c('B1','KC','C4.6','image is upright',{type:'writtenConcept',any:['upright','erect']}),c('B2','KC','C4.6','image is same size as object',{type:'writtenConcept',all:['same size'],any:['object','image']}),c('B3','KC','C4.6','image distance behind mirror equals object distance in front',{type:'writtenConcept',all:['same distance'],any:['behind','front']}),c('B4','KC','C4.6','image is laterally inverted',{type:'writtenConcept',any:['laterally inverted','left right','left-right']}),c('B5','UK','C4.6','virtual because rays only appear to meet behind mirror',{type:'writtenConcept',all:['virtual'],any:['appear','do not meet','cannot screen']})]},
{id:'d',marks:3,objective:'C4.4',prompt:'Give three phenomena or devices explained using straight-line propagation of light.',criteria:[c('B1','KC','C4.4','first valid example',{type:'writtenConcept',any:['shadow','eclipse','pinhole']}),c('B2','KC','C4.4','second valid example',{type:'writtenConcept',any:['shadow','eclipse','pinhole']}),c('B3','KC','C4.4','third valid example or clear ray explanation',{type:'writtenConcept',any:['shadow','eclipse','pinhole','ray']})]}
]},
{
id:'c4-p2-young-diffraction-01',topic:'C4',kind:'extended response',marks:15,title:'How light reveals its wave behaviour',stem:'A class discusses historical models of light, performs a Young double-slit activity and compares diffraction of light with sound.',parts:[
{id:'a',marks:4,objective:'C4.1',prompt:'Compare Newton\'s and Huygens\' historical models and state the modern conclusion about light.',criteria:[c('B1','KC','C4.1','Newton associated with particle/corpuscular model',{type:'writtenConcept',all:['newton'],any:['particle','corpuscle']}),c('B2','KC','C4.1','Huygens associated with wave model',{type:'writtenConcept',all:['huygens'],any:['wave']}),c('B3','UK','C4.1','Young interference supported wave behaviour',{type:'writtenConcept',all:['young'],any:['interference','wave']}),c('B4','KC','C4.1','modern light shows wave and particle behaviour',{type:'writtenConcept',all:['wave','particle']})]},
{id:'b',marks:5,objective:'C4.2',prompt:'Describe a Young double-slit setup and the observation that supports the wave model.',criteria:[c('B1','XS','C4.2','uses coherent or single-source illumination of two narrow slits',{type:'writtenConcept',all:['slit'],any:['two','double','coherent']}),c('B2','XS','C4.2','places a screen beyond the slits',{type:'writtenConcept',all:['screen'],any:['slits','behind']}),c('B3','XS','C4.2','observes alternating bright and dark fringes',{type:'writtenConcept',all:['bright','dark'],any:['fringe','band']}),c('B4','UK','C4.2','bright fringes from constructive interference',{type:'writtenConcept',all:['constructive'],any:['bright','interference']}),c('B5','UK','C4.2','dark fringes from destructive interference',{type:'writtenConcept',all:['destructive'],any:['dark','interference']})]},
{id:'c',marks:3,objective:'C4.3',prompt:'Explain why diffraction of light is not normally obvious at a doorway.',criteria:[c('B1','UK','C4.3','diffraction is strongest when aperture is comparable with wavelength',{type:'writtenConcept',all:['wavelength'],any:['gap','aperture','comparable']}),c('B2','KC','C4.3','visible-light wavelength is extremely small',{type:'writtenConcept',all:['light'],any:['small wavelength','tiny wavelength','short wavelength']}),c('B3','UK','C4.3','doorway is enormously larger than visible wavelength so spreading is weak',{type:'writtenConcept',all:['door'],any:['larger','weak','little diffraction']})]},
{id:'d',marks:3,objective:'C4.2',prompt:'State three practical features that improve the chance of seeing a stable double-slit fringe pattern.',criteria:[c('B1','XS','C4.2','uses narrow slits',{type:'writtenConcept',all:['narrow'],any:['slit']}),c('B2','XS','C4.2','uses coherent or single monochromatic source',{type:'writtenConcept',any:['coherent','monochromatic','laser','single source']}),c('B3','XS','C4.2','uses suitable slit separation and screen distance/darkened environment',{type:'writtenConcept',any:['screen distance','far screen','dark','separation']})]}
]},
{
id:'c4-p2-dispersion-tir-01',topic:'C4',kind:'structured',marks:15,title:'Dispersion and total internal reflection',stem:'White light passes through a prism. A separate glass block is then used to investigate critical angle and total internal reflection.',parts:[
{id:'a',marks:3,objective:'C4.9',prompt:'Explain how a prism produces a visible spectrum from white light.',criteria:[c('B1','KC','C4.9','white light contains a range of visible wavelengths/colours',{type:'writtenConcept',all:['white light'],any:['colour','wavelength']}),c('B2','UK','C4.9','different wavelengths refract by different amounts',{type:'writtenConcept',all:['different'],any:['refract','bend']}),c('B3','KC','C4.9','names dispersion or states violet bends more than red',{type:'writtenConcept',any:['dispersion','violet','red']})]},
{id:'b',marks:4,objective:'C4.11',prompt:'Define critical angle and state both conditions required for total internal reflection.',criteria:[c('B1','KC','C4.11','critical angle is incidence angle in denser medium when refracted angle is 90°',{type:'writtenConcept',all:['90'],any:['critical','refracted']}),c('B2','KC','C4.11','light travels from higher to lower refractive index',{type:'writtenConcept',any:['denser to less dense','higher refractive','lower refractive']}),c('B3','KC','C4.11','incidence angle exceeds critical angle',{type:'writtenConcept',all:['critical angle'],any:['greater','exceed','above']}),c('B4','UK','C4.11','states no refracted ray then leaves and reflection is internal',{type:'writtenConcept',all:['reflect'],any:['total','no refracted','inside']})]},
{id:'c',marks:4,objective:'C4.12',prompt:'Calculate the critical angle for glass of refractive index 1.50.',criteria:[c('M1','UK','C4.12','uses sin c = 1/n',{type:'formulaUse',formula:'sin(c)=1/n'}),c('M2','UK','C4.12','substitutes n = 1.50',{type:'containsValues',values:[1.5],needAll:true}),c('M3','UK','C4.12','takes inverse sine of 1/1.50',{type:'writtenConcept',any:['sin^-1','inverse sine','arcsin']}),c('A1','UK','C4.12','obtains about 41.8° or 42°',{type:'physicsQuantity',quantity:'angle',value:41.81,unit:'°',tolerance:.5},{depends:['M1']})]},
{id:'d',marks:4,objective:'C4.13',prompt:'Describe how total internal reflection is used in an optical fibre or a right-angle prism. Include the refractive-index or angle condition.',criteria:[c('B1','KC','C4.13','names optical fibre or prism application',{type:'writtenConcept',any:['optical fibre','fiber','prism']}),c('B2','UK','C4.13','ray meets internal boundary above critical angle',{type:'writtenConcept',all:['critical angle'],any:['greater','above','exceed']}),c('B3','UK','C4.13','core/material has higher refractive index than surroundings/cladding where relevant',{type:'writtenConcept',all:['refractive index'],any:['higher','lower','cladding']}),c('B4','UK','C4.13','repeated internal reflection guides or turns light with little escape',{type:'writtenConcept',all:['reflection'],any:['guide','turn','repeated','stay inside']})]}
]},
{
id:'c5-p2-lens-images-01',topic:'C5',kind:'structured',marks:15,title:'Converging lenses and image formation',stem:'An illuminated object is placed at different distances from a thin converging lens.',parts:[
{id:'a',marks:3,objective:'C5.1',prompt:'Describe the effect of a converging lens and a diverging lens on a parallel beam.',criteria:[c('B1','KC','C5.1','converging lens brings parallel rays to principal focus',{type:'writtenConcept',all:['converging'],any:['focus','meet']}),c('B2','KC','C5.1','diverging lens spreads parallel rays',{type:'writtenConcept',all:['diverging'],any:['spread','diverge']}),c('B3','KC','C5.1','diverging rays appear to come from focus on incident side',{type:'writtenConcept',all:['focus'],any:['appear','incident side','virtual']})]},
{id:'b',marks:4,objective:'C5.2',prompt:'Define principal axis, principal focus, focal length and magnification.',criteria:[c('B1','KC','C5.2','defines principal axis through optical centre/foci',{type:'writtenConcept',all:['principal axis'],any:['optical centre','focus']}),c('B2','KC','C5.2','defines principal focus for parallel axial rays',{type:'writtenConcept',all:['focus'],any:['parallel','meet','appear']}),c('B3','KC','C5.2','focal length is distance from optical centre to focus',{type:'writtenConcept',all:['focal length'],any:['distance','centre','focus']}),c('B4','KC','C5.2','magnification is image size/object size',{type:'writtenConcept',all:['magnification'],any:['image size','object size','ratio']})]},
{id:'c',marks:3,objective:'C5.3',prompt:'Differentiate a real image from a virtual image.',criteria:[c('B1','KC','C5.3','real image formed where rays actually meet',{type:'writtenConcept',all:['real'],any:['actually meet','converge']}),c('B2','KC','C5.3','real image can be formed on a screen',{type:'writtenConcept',all:['screen'],any:['real','project']}),c('B3','KC','C5.3','virtual rays only appear to meet and cannot be projected',{type:'writtenConcept',all:['virtual'],any:['appear','cannot','screen']})]},
{id:'d',marks:5,objective:'C5.4',prompt:'An object 2.0 cm high forms an image 5.0 cm high at an image distance of 40 cm. Calculate the magnification and the object distance.',criteria:[c('M1','UK','C5.4','uses m = image size/object size',{type:'formulaUse',formula:'m=image/object'}),c('A1','UK','C5.4','obtains m = 2.5',{type:'physicsQuantity',quantity:'dimensionless',value:2.5,unit:'',unitRequired:false,relativeTolerance:.001},{depends:['M1']}),c('M2','UK','C5.4','uses m = v/u',{type:'formulaUse',formula:'m=v/u'}),c('M3','UK','C5.4','rearranges u = v/m',{type:'containsValues',values:[40,2.5],needAll:true}),c('A2','UK','C5.4','obtains object distance 16 cm',{type:'physicsQuantity',quantity:'length',value:16,unit:'cm',relativeTolerance:.001},{depends:['M2']})]}
]},
{
id:'c5-p2-focal-length-01',topic:'C5',kind:'data analysis',marks:15,title:'Determining the focal length of a converging lens',stem:'A student forms sharp real images of an illuminated object on a screen and records object distance u and image distance v.',parts:[
{id:'a',marks:4,objective:'C5.5',prompt:'Describe a method to collect suitable u and v readings for determining focal length.',criteria:[c('B1','XS','C5.5','places object, lens and screen on same principal axis',{type:'writtenConcept',all:['object','lens','screen'],any:['axis','aligned']}),c('B2','XS','C5.5','moves screen until image is sharp',{type:'writtenConcept',all:['sharp'],any:['focus','screen']}),c('B3','XS','C5.5','measures u and v from optical centre of lens',{type:'writtenConcept',all:['u','v'],any:['measure','optical centre','lens']}),c('B4','XS','C5.5','repeats for several object positions',{type:'writtenConcept',any:['repeat','several','different object distance']})]},
{id:'b',marks:5,objective:'C5.5',prompt:'For one pair of readings u = 30.0 cm and v = 60.0 cm, calculate the focal length.',criteria:[c('M1','UK','C5.5','uses 1/f = 1/u + 1/v',{type:'formulaUse',formula:'1/f=1/u+1/v'}),c('M2','UK','C5.5','substitutes u = 30.0 cm and v = 60.0 cm',{type:'containsValues',values:[30,60],needAll:true}),c('M3','UK','C5.5','obtains reciprocal 1/f = 0.05 cm^-1',{type:'writtenConcept',any:['0.05','1/20']}),c('A1','UK','C5.5','obtains f = 20.0 cm',{type:'physicsQuantity',quantity:'length',value:20,unit:'cm',relativeTolerance:.002},{depends:['M1']}),c('B1','UK','C5.5','keeps u, v and f in consistent length units',{type:'writtenConcept',any:['cm','same unit','consistent']})]},
{id:'c',marks:3,objective:'C5.4',prompt:'Use the same data to calculate magnification and state whether the image is larger or smaller than the object.',criteria:[c('M1','UK','C5.4','uses m = v/u',{type:'formulaUse',formula:'m=v/u'}),c('A1','UK','C5.4','obtains m = 2.0',{type:'physicsQuantity',quantity:'dimensionless',value:2,unit:'',unitRequired:false,relativeTolerance:.002},{depends:['M1']}),c('B1','UK','C5.4','states image is larger/magnified',{type:'writtenConcept',any:['larger','magnified','twice']})]},
{id:'d',marks:3,objective:'C5.5',prompt:'State three sources of uncertainty or improvements for this lens experiment.',criteria:[c('B1','XS','C5.5','first specific issue/improvement such as locating optical centre or reducing parallax',{type:'writtenConcept',any:['parallax','optical centre','centre of lens','ruler']}),c('B2','XS','C5.5','second specific issue/improvement such as judging sharpest focus or darkening room',{type:'writtenConcept',any:['sharp','focus','dark','screen']}),c('B3','XS','C5.5','repeats readings and averages focal length',{type:'writtenConcept',any:['repeat','average','several']})]}
]}
]);
export function sectionCStructuredStats(){const topics={};for(const q of SECTION_C_STRUCTURED_BANK)topics[q.topic]=(topics[q.topic]||0)+1;return{questions:SECTION_C_STRUCTURED_BANK.length,marks:SECTION_C_STRUCTURED_BANK.reduce((s,q)=>s+q.marks,0),byTopic:topics};}
