import { boyleFinalPressure, charlesFinalVolume, celsiusToKelvin, heatingCurveState, radiationSurfaceModel, sensibleHeat, specificHeatFromElectrical, thermalExpansionModel } from '../bThermalPhysics.mjs';

export function buildJouleLabModel({massKg=2,heightM=5,gNPerKg=10,efficiency=0.92,waterMassKg=0.5,specificHeat=4200}={}){const work=massKg*gNPerKg*heightM;const toWater=work*Math.max(0,Math.min(1,efficiency));return{workJ:work,toWaterJ:toWater,temperatureRiseC:toWater/(waterMassKg*specificHeat),otherJ:work-toWater};}
export function buildGasLawLabModel({law='boyle',p1KPa=100,v1Cm3=300,v2Cm3=150,t1C=27,t2C=127}={}){if(law==='boyle'){const p2Pa=boyleFinalPressure({p1:p1KPa*1000,v1:v1Cm3,v2:v2Cm3});return{law,p2KPa:p2Pa/1000,v2Cm3,t1K:celsiusToKelvin(t1C),t2K:celsiusToKelvin(t2C)}}const v2=charlesFinalVolume({v1:v1Cm3,t1K:celsiusToKelvin(t1C),t2K:celsiusToKelvin(t2C)});return{law,p2KPa:p1KPa,v2Cm3:v2,t1K:celsiusToKelvin(t1C),t2K:celsiusToKelvin(t2C)};}
export function buildKelvinGraphModel({slope=0.35,tempsC=[-200,-100,0,100]}={}){const points=tempsC.map(c=>({c,k:celsiusToKelvin(c),value:slope*celsiusToKelvin(c)}));return{points,interceptC:-273,note:'The zero intercept is an extrapolation of the idealised gas-law trend. Real gases condense before the line can be followed physically to zero pressure or volume.'};}
export function buildExpansionLabModel(input={}){return thermalExpansionModel(input);}
export function buildHeatingCurveLabModel({energyKJ=0,massKg=0.25}={}){return heatingCurveState({energyJ:energyKJ*1000,massKg});}
export function buildSpecificHeatLabModel({powerW=48,timeS=300,massKg=0.8,deltaTC=16}={}){const energyJ=powerW*timeS;return{energyJ,specificHeat:specificHeatFromElectrical({powerW,timeS,massKg,deltaTK:deltaTC}),idealEnergyCheck:sensibleHeat({massKg,specificHeatJPerKgK:specificHeatFromElectrical({powerW,timeS,massKg,deltaTK:deltaTC}),deltaTK:deltaTC})};}
export function buildRadiationLabModel({temperatureC=80}={}){const surfaces=['dull-black','dull-white','shiny-metal'].map(surface=>radiationSurfaceModel({temperatureC,surface}));const max=Math.max(...surfaces.map(s=>s.relativeEmission));return{temperatureC,surfaces:surfaces.map(s=>({...s,relativeIndex:max?s.relativeEmission/max:0}))};}
export function buildConvectionLabModel({bottomTempC=80,topTempC=30}={}){const delta=bottomTempC-topTempC;return{bottomTempC,topTempC,deltaC:delta,currentStrength:Math.max(0,Math.min(1,delta/80)),state:delta>0?'warm fluid rises and cooler fluid sinks':delta<0?'the imposed gradient opposes the usual heating-from-below circulation':'no temperature-driven density contrast'};}
