export const IT_SBA_COMPONENTS = [
  {
    id: "database",
    short: "DB",
    title: "Database Management",
    marks: 20,
    description: "Plan related tables, keys, relationships, queries, a form with a subform, and a report.",
  },
  {
    id: "spreadsheet",
    short: "SS",
    title: "Spreadsheet",
    marks: 20,
    description: "Use functions, formulas, references, formatting, sorting, filtering, summaries, charts and linked sheets.",
  },
  {
    id: "word",
    short: "WP",
    title: "Word Processing",
    marks: 20,
    description: "Produce well-formatted documents and complete two advanced word-processing features.",
  },
  {
    id: "web",
    short: "WEB",
    title: "Web Page Design",
    marks: 10,
    description: "Design one clear web page for the intended audience with suitable text, graphics and hyperlinks.",
  },
  {
    id: "programming",
    short: "PSP",
    title: "Problem-Solving and Programming",
    marks: 15,
    description: "Define the problem, design an algorithm, trace test data, implement a working program and document it.",
  },
];

export const IT_SBA_MARKS = [
  { label: "Word Processing", marks: "20 raw" },
  { label: "Web Page Design", marks: "10 raw" },
  { label: "Spreadsheet", marks: "20 raw" },
  { label: "Database", marks: "20 raw" },
  { label: "Problem-Solving and Programming", marks: "15" },
];

export const IT_SBA_CURRENT_LIMITS = [
  {
    id: "word",
    title: "Word Processing",
    text: "Use the required document formatting and page layout. The marking scheme allows choice, including TWO advanced features from mail merge, table of contents and fillable forms. A fillable form should use no more than four controls.",
  },
  {
    id: "web",
    title: "Web Page Design",
    text: "Use one web page for the SBA assignment. Include a project logo, clear navigation and content areas, and at least two suitable hyperlink types.",
  },
  {
    id: "spreadsheet",
    title: "Spreadsheet",
    text: "Use one workbook with two or more worksheets. Keep the assignment to a maximum of TWO major tasks, with no more than THREE requirements in each task, and no more than TWO chart types.",
  },
  {
    id: "database",
    title: "Database Management",
    text: "Use no more than THREE tables, TWO queries, ONE calculation within queries, ONE form with a main form and subform, and ONE grouped and sorted report.",
  },
  {
    id: "programming",
    title: "Problem-Solving and Programming",
    text: "Use the programming language selected by your centre. Keep the coded solution to input, output, conditional branching and iteration. Submit the problem-solving evidence as a PDF with the required project evidence.",
  },
];

export const IT_SBA_MARKING_GUIDE = {
  word: [
    { label: "Document formatting", marks: 4 },
    { label: "Page layout", marks: 2 },
    { label: "Two selected standard features", marks: 4 },
    { label: "Two selected advanced features", marks: 10 },
  ],
  web: [
    { label: "Design features with text and graphics", marks: 3 },
    { label: "Layout for the intended audience", marks: 2 },
    { label: "Information consistent with the project", marks: 3 },
    { label: "Two suitable hyperlinks", marks: 2 },
  ],
  spreadsheet: [
    { label: "Three different functions", marks: 3 },
    { label: "Three different arithmetic formulas", marks: 3 },
    { label: "Formula replication and absolute references or range names", marks: 2 },
    { label: "Spreadsheet formatting", marks: 4 },
    { label: "Sorting", marks: 1 },
    { label: "Filtering or data extraction", marks: 2 },
    { label: "Pivot table", marks: 1 },
    { label: "Charting", marks: 3 },
    { label: "Linking cells between sheets", marks: 1 },
  ],
  database: [
    { label: "Create and populate the database", marks: 5 },
    { label: "Relationships between tables", marks: 2 },
    { label: "Queries including the calculated field", marks: 5 },
    { label: "Main form and subform", marks: 2 },
    { label: "Sorting", marks: 1 },
    { label: "Grouped report with summary and correct title", marks: 5 },
  ],
  programming: [
    { label: "Flowchart or pseudocode", marks: 6 },
    { label: "Trace table with suitable test data", marks: 4 },
    { label: "Working program execution", marks: 1 },
    { label: "Programming-language features and working solution", marks: 3 },
    { label: "Program documentation", marks: 1 },
  ],
};

const COMMON_MISTAKES = {
  database: [
    "Using one large table instead of separating repeated information into related tables.",
    "Choosing a field as a primary key even though the value can repeat.",
    "Creating queries that display the correct fields but do not apply the required criteria.",
    "Making a report look attractive but forgetting grouping, sorting, summary values or the required title.",
  ],
  spreadsheet: [
    "Typing answers into cells instead of using formulas.",
    "Hard-coding a value that should be stored once and referenced.",
    "Copying formulas without checking relative and absolute references.",
    "Creating a chart before checking that the source range and labels are correct.",
  ],
  word: [
    "Formatting the document first and leaving the required advanced feature until the end.",
    "Using mail merge fields that do not match the data source.",
    "Adding form controls without clear labels or instructions.",
    "Using too many fonts, colours or decorative features that reduce readability.",
  ],
  web: [
    "Building several pages when the current CXC syllabus task is limited to one web page.",
    "Using large images without resizing them for the layout.",
    "Adding links without testing them.",
    "Writing content that does not suit the intended audience.",
  ],
  programming: [
    "Writing code before defining the problem, inputs, processes and outputs.",
    "Using test data that only proves the normal case.",
    "Creating a trace table that does not follow the algorithm line by line.",
    "Submitting screenshots without showing the input and the result produced.",
  ],
};

const GUIDE_STEPS = {
  database: [
    {
      title: "Identify the information to be stored",
      detail: "Read the project brief and underline the main groups of information. Each group is a possible table. Look for information that will repeat if everything is stored in one table.",
    },
    {
      title: "Plan at least two related tables",
      detail: "Give each table a clear purpose. List suitable field names and choose an appropriate data type for each field.",
    },
    {
      title: "Choose primary and foreign keys",
      detail: "A primary key must uniquely identify each record. Use matching foreign-key fields to connect related tables.",
    },
    {
      title: "Create and test relationships",
      detail: "Set the relationship that matches the real situation. Check whether it should be one-to-one or one-to-many before entering large amounts of data.",
    },
    {
      title: "Enter realistic records",
      detail: "Use believable data with enough variety to test your queries. Include different categories, dates, amounts and statuses.",
    },
    {
      title: "Create two queries and include one calculation",
      detail: "Keep within the current SBA limit. Use one query with criteria from one table and one query that uses related tables. Include one calculated field within the queries and check the returned records carefully.",
    },
    {
      title: "Create a form with a subform",
      detail: "Use the main form for the parent record and the subform for related records. Add suitable headings and make the form easy to use.",
    },
    {
      title: "Create a grouped report",
      detail: "Select useful fields, apply the required grouping and sorting, add a summary such as count, sum or average, and use the exact report title required by the brief.",
    },
  ],
  spreadsheet: [
    {
      title: "Import or enter the source data",
      detail: "Keep the source data in a clean rectangular list with one heading row. Do not place decorative headings inside the data range.",
    },
    {
      title: "Plan the workbook as two major tasks",
      detail: "Use two or more worksheets, but keep the assessed assignment within the current limit of TWO major tasks with no more than THREE requirements in each task. Group related calculations and analysis together.",
    },
    {
      title: "Use efficient formulas",
      detail: "Create formulas from cell references instead of typing values into the formula. Use one formula and fill it down where possible.",
    },
    {
      title: "Use at least three different functions",
      detail: "Choose functions that solve a real task in the project. SUM, AVERAGE, IF, COUNTIF, VLOOKUP and PMT are examples, but the brief should determine your choice.",
    },
    {
      title: "Show relative and absolute referencing",
      detail: "Use absolute references or named ranges when a rate, fee or lookup table must stay fixed while a formula is copied.",
    },
    {
      title: "Format the worksheet",
      detail: "Apply suitable number formats, alignment, fonts, borders and headings. Money should look like money and percentages should look like percentages.",
    },
    {
      title: "Sort and filter the data",
      detail: "Use the criteria stated in the project. Check that the displayed records match the requirement after the operation.",
    },
    {
      title: "Create a summary",
      detail: "Use a pivot table or another appropriate summary method to answer a useful question about the data.",
    },
    {
      title: "Create and label suitable charts",
      detail: "Choose chart types that match the data. Add useful titles and the required axes or data labels. The current SBA guidance limits the assignment to no more than TWO chart types.",
    },
    {
      title: "Link worksheets",
      detail: "Use a formula that refers to another worksheet so changes in the source data are reflected automatically.",
    },
  ],
  word: [
    {
      title: "Choose the two advanced features",
      detail: "The current marking scheme allows a choice of TWO advanced features from table of contents, mail merge and fillable forms. Your teacher may specify the pair. If you use a fillable form, keep it within the current control limit.",
    },
    {
      title: "Set up the document correctly",
      detail: "Set margins, orientation, header or footer and any required page numbering before the document becomes too large.",
    },
    {
      title: "Apply document formatting",
      detail: "Use clear fonts, suitable sizes, bold, underline or italics only where they help the reader. Keep the layout consistent.",
    },
    {
      title: "Insert useful content",
      detail: "Add a table, columns, chart or imported graphic only when it supports the task. Size imported items so they fit the page properly.",
    },
    {
      title: "Complete advanced feature one",
      detail: "For mail merge, check the data source, primary document, merge fields and final merged output. For a fillable form, use clearly labelled controls and no more than four controls in the assignment.",
    },
    {
      title: "Complete advanced feature two",
      detail: "If using a table of contents, use heading levels first and then generate the table automatically. If using another advanced feature, test every part.",
    },
    {
      title: "Proofread and test",
      detail: "Check spelling, names, numbers, merge output, form controls, page breaks and imported content.",
    },
    {
      title: "Save with a sensible filename",
      detail: "Use the exact filename requested by your teacher. Keep a backup copy before making final changes.",
    },
  ],
  web: [
    {
      title: "Identify the audience and purpose",
      detail: "Decide who will use the page and what information they need first.",
    },
    {
      title: "Plan one page",
      detail: "The current CXC syllabus limits this SBA task to one web page. Plan clear sections on the same page, including a project logo, a navigation area and a content area. Follow your teacher's current instructions if they provide additional requirements.",
    },
    {
      title: "Write the content",
      detail: "Use short headings and useful paragraphs. The information should match the project and be suitable for the intended audience.",
    },
    {
      title: "Add and size graphics",
      detail: "Use relevant images or graphics. Keep them clear, appropriately sized and positioned.",
    },
    {
      title: "Add at least two hyperlink types",
      detail: "Use at least two suitable hyperlink types from the current list, such as another web page, a location on the page, an email address or a user-created file. Test every link.",
    },
    {
      title: "Check consistency",
      detail: "Make sure names, fees, dates, services and contact details agree with the other SBA components.",
    },
    {
      title: "Test the final page",
      detail: "Open the page in a browser. Test every link, check the layout at more than one screen width and correct any missing content.",
    },
  ],
  programming: [
    {
      title: "Define the problem",
      detail: "State the part of the overall project that the program will solve. Keep the programmed task small enough to test properly.",
    },
    {
      title: "List inputs, processes and outputs",
      detail: "Write down what the user enters, what calculations or decisions are made, and what the program must display.",
    },
    {
      title: "Choose variables",
      detail: "Use clear variable names and identify the data each variable will store.",
    },
    {
      title: "Design the algorithm",
      detail: "Write pseudocode or draw a flowchart. Include prompts, input, processing, output, at least one selection and at least one loop.",
    },
    {
      title: "Create the trace table",
      detail: "Use test data that follows the algorithm. Show how important variable values change.",
    },
    {
      title: "Add boundary and invalid test data",
      detail: "Test values at decision boundaries and include at least one incorrect input where the project allows validation.",
    },
    {
      title: "Write the program",
      detail: "Translate the tested algorithm into the selected programming language. Keep the logic close to the pseudocode.",
    },
    {
      title: "Run and correct the program",
      detail: "Use the same test data from the trace table and compare the program output with the expected result.",
    },
    {
      title: "Capture evidence",
      detail: "Take clear screenshots showing data entry and results. Make sure each screenshot proves a specific test.",
    },
    {
      title: "Prepare the PDF documentation",
      detail: "Include the cover sheet, problem definition, algorithm, source code, trace table, test data and screenshots of program execution.",
    },
  ],
};

function makeProject(config) {
  return {
    ...config,
    components: {
      database: {
        title: "Database Management",
        produce: config.databaseProduce,
        steps: GUIDE_STEPS.database,
        completed: config.databaseCompleted,
        mistakes: COMMON_MISTAKES.database,
      },
      spreadsheet: {
        title: "Spreadsheet",
        produce: config.spreadsheetProduce,
        steps: GUIDE_STEPS.spreadsheet,
        completed: config.spreadsheetCompleted,
        mistakes: COMMON_MISTAKES.spreadsheet,
      },
      word: {
        title: "Word Processing",
        produce: config.wordProduce,
        steps: GUIDE_STEPS.word,
        completed: config.wordCompleted,
        mistakes: COMMON_MISTAKES.word,
      },
      web: {
        title: "Web Page Design",
        produce: config.webProduce,
        steps: GUIDE_STEPS.web,
        completed: config.webCompleted,
        mistakes: COMMON_MISTAKES.web,
      },
      programming: {
        title: "Problem-Solving and Programming",
        produce: config.programmingProduce,
        steps: GUIDE_STEPS.programming,
        completed: config.programmingCompleted,
        mistakes: COMMON_MISTAKES.programming,
      },
    },
  };
}

export const IT_SBA_PROJECTS = [
  makeProject({
    id: "sports-academy",
    code: "SBA 01",
    title: "SPARK Sports Academy",
    sector: "Sports",
    level: "Balanced",
    accent: "Membership, training and fees",
    scenario: "SPARK Sports Academy offers after-school training in athletics, football, swimming and netball. The academy wants one system to manage athletes, guardians, programmes, monthly fees and training attendance. Management also wants a clear summary of income and programme participation before the new term begins.",
    purpose: "Build a connected solution that stores member records, analyses fees and participation, communicates with guardians, presents the academy to families and automates a membership-fee calculation.",
    databaseProduce: "Create Athlete, Guardian and Programme tables. Link each athlete to a guardian and programme. Create TWO queries: Junior Athletes using criteria from one table, and Athlete Finance using related tables with one fee calculation. Create one member form with a guardian subform and one grouped programme-fees report.",
    databaseCompleted: [
      "Athlete table: AthleteID, FirstName, LastName, DOB, Gender, ProgrammeCode, JoinDate, MedicalNote, Status.",
      "Guardian table: GuardianID, AthleteID, FullName, Relation, Phone, Email.",
      "Programme table: ProgrammeCode, ProgrammeName, MonthlyFee, Coach, TrainingDays.",
      "Queries: Junior Athletes filters the Athlete table. Athlete Finance joins related tables and includes one calculated TermFee field such as [MonthlyFee]*3.",
      "Report: group by ProgrammeName, sort by athlete last name and show the average TermFee for each programme.",
    ],
    spreadsheetProduce: "Create an AcademyFees workbook with Members and Summary sheets. Organise it as TWO major tasks with no more than THREE requirements in each. Task A covers fee calculations, functions and references. Task B covers data analysis, one chart and a linked summary.",
    spreadsheetCompleted: [
      "Use VLOOKUP or XLOOKUP-style logic supported by the software to return the programme fee from a fee table.",
      "Example term fee: =D2*3.",
      "Example discount: =IF(E2=\"Junior\",F2*10%,0).",
      "Place one equipment-service rate in a fixed cell such as $M$2 and use an absolute reference when copied.",
      "Create a pivot summary of Balance by Programme and a column chart titled Outstanding Balance by Programme.",
      "Link Summary!B2 to the total balance calculated on the Members sheet.",
    ],
    wordProduce: "Create a fillable athlete registration form and a mail-merge fee notice for guardians. Use clear instructions, suitable controls, a professional header and a table showing the available programmes.",
    wordCompleted: [
      "Registration form controls: athlete name text box, date picker for DOB, programme drop-down list and medical-information check box.",
      "Mail merge fields: GuardianName, AthleteName, ProgrammeName, TermFee and Balance.",
      "The fee notice includes a short payment message, a programme table and the programme chart from the spreadsheet.",
      "Use one consistent academy letterhead, clear margins, a footer and readable formatting.",
    ],
    webProduce: "Design one family information page for the academy. Include a project logo, clear navigation and content areas, programme information, fees, training times, a relevant graphic and at least two suitable hyperlink types.",
    webCompleted: [
      "Page sections: About the Academy, Programmes and Fees, Training Schedule, Registration and Contact.",
      "Include one email link and one link to the downloadable registration form or another suitable user-created file.",
      "Use the same programme names and fees shown in the database and spreadsheet.",
    ],
    programmingProduce: "Write a program that accepts athlete details and a programme choice, determines the fee, applies a junior discount where appropriate, displays the athlete summary and keeps a running total for all athletes entered.",
    programmingCompleted: {
      problem: "Calculate the amount each athlete should pay for a term and the total expected income for all athletes entered in one program run.",
      inputs: ["Athlete name", "Age", "Programme code", "Number of athletes to enter"],
      processes: ["Look up programme fee", "Multiply monthly fee by 3", "Apply 10% junior discount when age is under 13", "Add final fee to running total"],
      outputs: ["Athlete name", "Programme", "Discount", "Final term fee", "Total expected income"],
      pseudocode: [
        "START",
        "SET grandTotal <- 0",
        "INPUT athleteCount",
        "FOR counter <- 1 TO athleteCount",
        "  INPUT athleteName, age, programmeCode",
        "  SET monthlyFee <- fee for programmeCode",
        "  SET termFee <- monthlyFee * 3",
        "  IF age < 13 THEN",
        "    SET discount <- termFee * 0.10",
        "  ELSE",
        "    SET discount <- 0",
        "  ENDIF",
        "  SET finalFee <- termFee - discount",
        "  SET grandTotal <- grandTotal + finalFee",
        "  DISPLAY athleteName, programmeCode, discount, finalFee",
        "NEXT counter",
        "DISPLAY grandTotal",
        "STOP",
      ],
      trace: [
        ["Alicia Brown", "12", "SWM", "9000", "27000", "2700", "24300"],
        ["Dario King", "15", "FTB", "7500", "22500", "0", "22500"],
        ["Renee Blake", "11", "NET", "7000", "21000", "2100", "18900"],
      ],
      pascal: [
        "program AcademyFees;",
        "var",
        "  i, athleteCount, age: integer;",
        "  athleteName, programmeCode: string;",
        "  monthlyFee, termFee, discount, finalFee, grandTotal: real;",
        "begin",
        "  grandTotal := 0;",
        "  write('Number of athletes: '); readln(athleteCount);",
        "  for i := 1 to athleteCount do",
        "  begin",
        "    write('Athlete name: '); readln(athleteName);",
        "    write('Age: '); readln(age);",
        "    write('Programme code: '); readln(programmeCode);",
        "    if programmeCode = 'SWM' then monthlyFee := 9000",
        "    else if programmeCode = 'FTB' then monthlyFee := 7500",
        "    else if programmeCode = 'NET' then monthlyFee := 7000",
        "    else monthlyFee := 8000;",
        "    termFee := monthlyFee * 3;",
        "    if age < 13 then discount := termFee * 0.10 else discount := 0;",
        "    finalFee := termFee - discount;",
        "    grandTotal := grandTotal + finalFee;",
        "    writeln(athleteName, ' final fee: ', finalFee:0:2);",
        "  end;",
        "  writeln('Total expected income: ', grandTotal:0:2);",
        "end.",
      ],
    },
    starterRows: [
      ["AthleteID","FirstName","LastName","Age","ProgrammeCode","MonthlyFee","Status"],
      ["A001","Alicia","Brown","12","SWM","9000","Active"],
      ["A002","Dario","King","15","FTB","7500","Active"],
      ["A003","Renee","Blake","11","NET","7000","Active"],
      ["A004","Malik","Grant","14","ATH","8000","Active"],
      ["A005","Jada","Campbell","13","SWM","9000","Active"],
      ["A006","Andre","Lewis","10","FTB","7500","Active"],
    ],
  }),

  makeProject({
    id: "medical-centre",
    code: "SBA 02",
    title: "IslandCare Medical Centre",
    sector: "Medicine",
    level: "Detailed",
    accent: "Patients, appointments and service charges",
    scenario: "IslandCare Medical Centre provides general consultations, wellness checks and selected diagnostic services. Staff currently keep separate appointment and payment records. The centre wants a small information system to manage patients, emergency contacts, service types, appointments and outstanding balances.",
    purpose: "Create a connected project that improves patient record keeping, analyses service charges, produces appointment communication and automates the calculation of charges and discounts.",
    databaseProduce: "Create Patient, Service and Appointment tables. Store the emergency-contact details required by the project in the Patient table. Create TWO queries: Daily Appointments using criteria, and Outstanding Accounts using related tables with one balance calculation. Create one patient form with an appointment subform and one service-income report.",
    databaseCompleted: [
      "Patient table: PatientID, FirstName, LastName, DOB, Gender, Phone, Parish, EmergencyName, EmergencyRelation, EmergencyPhone.",
      "Service table: ServiceCode, ServiceName, StandardFee.",
      "Appointment table: AppointmentID, PatientID, ServiceCode, VisitDate, PaidAmount, Status.",
      "Queries: Daily Appointments filters appointments by date. Outstanding Accounts joins Patient, Service and Appointment and includes one calculated Balance field such as [StandardFee]-[PaidAmount].",
      "Report: group by ServiceName and show count of visits plus total and average charges.",
    ],
    spreadsheetProduce: "Create a MedicalAccounts workbook with at least two worksheets. Organise it as TWO major tasks with no more than THREE requirements in each. Task A covers service-fee calculations, functions and references. Task B covers filtering, a service summary with one chart, and a linked dashboard total.",
    spreadsheetCompleted: [
      "Look up StandardFee from the service table using ServiceCode.",
      "Example balance: =F2-G2.",
      "Example senior discount: =IF(D2>=65,E2*5%,0).",
      "Use COUNTIF to count unpaid visits and AVERAGE to find the average service charge.",
      "Create a summary of total charges by ServiceName and a bar chart titled Charges by Service.",
      "Link the dashboard total to the detailed accounts sheet.",
    ],
    wordProduce: "Create a fillable patient information form and a mail-merge appointment or balance notice. Use clear instructions and protect sensitive information in the example data.",
    wordCompleted: [
      "Form controls: patient name, date picker, service drop-down and consent check box.",
      "Mail merge fields: PatientName, AppointmentDate, ServiceName and Balance.",
      "Include a professional header, clinic contact information and a short privacy note.",
      "Use fictional patient data only in the SPARK reference project.",
    ],
    webProduce: "Design one patient information page with a project logo, clear navigation and content areas, services, opening hours, appointment guidance, contact information and at least two suitable hyperlink types.",
    webCompleted: [
      "Page sections: Welcome, Services, Before Your Visit, Opening Hours and Contact.",
      "Include an email link and an internal link to the Services section.",
      "Do not publish private patient data on the page.",
    ],
    programmingProduce: "Write a program that accepts patient age, service code and amount paid, calculates the service charge and any senior discount, displays the balance and totals the expected balances for all patients entered.",
    programmingCompleted: {
      problem: "Calculate the outstanding balance for each visit and the combined outstanding balance for all visits processed.",
      inputs: ["Patient name", "Age", "Service code", "Amount paid"],
      processes: ["Select service fee", "Apply 5% senior discount at age 65 or over", "Subtract amount paid", "Accumulate balances"],
      outputs: ["Patient summary", "Discount", "Outstanding balance", "Combined outstanding balance"],
      pseudocode: [
        "START",
        "SET totalBalance <- 0",
        "INPUT visitCount",
        "FOR visit <- 1 TO visitCount",
        "  INPUT patientName, age, serviceCode, amountPaid",
        "  SET serviceFee <- fee for serviceCode",
        "  IF age >= 65 THEN",
        "    SET discount <- serviceFee * 0.05",
        "  ELSE",
        "    SET discount <- 0",
        "  ENDIF",
        "  SET balance <- serviceFee - discount - amountPaid",
        "  SET totalBalance <- totalBalance + balance",
        "  DISPLAY patientName, discount, balance",
        "NEXT visit",
        "DISPLAY totalBalance",
        "STOP",
      ],
      trace: [
        ["Marlon Reid","67","GEN","6500","3000","325","3175"],
        ["Keisha Hall","41","WEL","8500","8500","0","0"],
        ["Noel James","72","DIA","12000","5000","600","6400"],
      ],
      pascal: [
        "program MedicalBalances;",
        "var",
        "  i, visitCount, age: integer;",
        "  patientName, serviceCode: string;",
        "  serviceFee, amountPaid, discount, balance, totalBalance: real;",
        "begin",
        "  totalBalance := 0;",
        "  write('Number of visits: '); readln(visitCount);",
        "  for i := 1 to visitCount do",
        "  begin",
        "    write('Patient name: '); readln(patientName);",
        "    write('Age: '); readln(age);",
        "    write('Service code: '); readln(serviceCode);",
        "    write('Amount paid: '); readln(amountPaid);",
        "    if serviceCode = 'GEN' then serviceFee := 6500",
        "    else if serviceCode = 'WEL' then serviceFee := 8500",
        "    else serviceFee := 12000;",
        "    if age >= 65 then discount := serviceFee * 0.05 else discount := 0;",
        "    balance := serviceFee - discount - amountPaid;",
        "    totalBalance := totalBalance + balance;",
        "    writeln(patientName, ' balance: ', balance:0:2);",
        "  end;",
        "  writeln('Combined balance: ', totalBalance:0:2);",
        "end.",
      ],
    },
    starterRows: [
      ["PatientID","FirstName","LastName","Age","ServiceCode","StandardFee","PaidAmount"],
      ["P001","Marlon","Reid","67","GEN","6500","3000"],
      ["P002","Keisha","Hall","41","WEL","8500","8500"],
      ["P003","Noel","James","72","DIA","12000","5000"],
      ["P004","Tiana","Morris","29","GEN","6500","6500"],
      ["P005","Howard","Grant","65","WEL","8500","4000"],
      ["P006","Safiya","Brown","36","DIA","12000","12000"],
    ],
  }),

  makeProject({
    id: "community-market",
    code: "SBA 03",
    title: "YardFresh Community Market",
    sector: "Business",
    level: "Balanced",
    accent: "Products, suppliers, sales and stock",
    scenario: "YardFresh Community Market sells groceries and locally produced goods. The owner needs better records for products, suppliers, sales and stock levels. The business also wants a simple customer information page and a program that calculates purchase totals and discounts.",
    purpose: "Build a small business solution that tracks inventory, analyses sales, produces supplier communication, presents customer information and automates checkout calculations.",
    databaseProduce: "Create Product, Supplier and StockPurchase tables. Create TWO queries: Low Stock using criteria from Product, and Supplier Orders using related tables with one calculated order-value field. Create one product form with a supplier subform and one grouped stock-value report.",
    databaseCompleted: [
      "Product table: ProductID, ProductName, Category, UnitPrice, QuantityInStock, ReorderLevel, SupplierID.",
      "Supplier table: SupplierID, SupplierName, Phone, Email, Parish.",
      "StockPurchase table: PurchaseID, ProductID, PurchaseDate, QuantityBought, CostPerUnit.",
      "Calculated query: StockValue: [UnitPrice]*[QuantityInStock].",
      "Low Stock query criteria: QuantityInStock <= ReorderLevel.",
      "Report: group by Category and show total stock value.",
    ],
    spreadsheetProduce: "Create a SalesAnalysis workbook with ProductSales and Dashboard sheets. Organise it as TWO major tasks with no more than THREE requirements in each. Task A covers sales calculations, functions and absolute references. Task B covers filtering, a category summary with one chart, and a linked dashboard total.",
    spreadsheetCompleted: [
      "Example sales value: =B2*C2.",
      "Example loyalty discount: =IF(D2>=10000,D2*5%,0).",
      "Store the GCT rate once and use an absolute reference when copied.",
      "Use SUM, AVERAGE and COUNTIF to answer sales questions.",
      "Create a pivot summary of sales by Category and a column chart.",
      "Link the Dashboard sales total to the detailed sheet.",
    ],
    wordProduce: "Create a fillable supplier-registration form and a mail-merge reorder notice. Include product and reorder information from the database or spreadsheet.",
    wordCompleted: [
      "Supplier form controls: supplier name, parish drop-down, product-category drop-down and delivery check box.",
      "Mail merge fields: SupplierName, ProductName, QuantityRequired and RequiredDate.",
      "Use a simple business letterhead and a table showing order details.",
    ],
    webProduce: "Design one customer page with a project logo, clear navigation and content areas, featured products, opening hours, delivery information, contact details and at least two suitable hyperlink types.",
    webCompleted: [
      "Page sections: Fresh This Week, Product Categories, Delivery Information, Opening Hours and Contact.",
      "Include an email link and an internal link to Product Categories.",
      "Keep prices and opening hours consistent with the project data.",
    ],
    programmingProduce: "Write a checkout program that accepts item totals for several customers, applies a 5% discount when the purchase reaches the threshold, adds GCT and keeps a running total of sales.",
    programmingCompleted: {
      problem: "Calculate the amount each customer pays after discount and GCT and display the total sales processed.",
      inputs: ["Customer name", "Purchase subtotal", "Number of customers"],
      processes: ["Apply discount at or above 10000", "Calculate GCT on the discounted amount", "Calculate final amount", "Accumulate total sales"],
      outputs: ["Customer name", "Discount", "GCT", "Final amount", "Total sales"],
      pseudocode: [
        "START",
        "SET totalSales <- 0",
        "INPUT customerCount",
        "FOR customer <- 1 TO customerCount",
        "  INPUT customerName, subtotal",
        "  IF subtotal >= 10000 THEN",
        "    SET discount <- subtotal * 0.05",
        "  ELSE",
        "    SET discount <- 0",
        "  ENDIF",
        "  SET taxable <- subtotal - discount",
        "  SET gct <- taxable * 0.15",
        "  SET finalAmount <- taxable + gct",
        "  SET totalSales <- totalSales + finalAmount",
        "  DISPLAY customerName, discount, gct, finalAmount",
        "NEXT customer",
        "DISPLAY totalSales",
        "STOP",
      ],
      trace: [
        ["Marsha Lee","8500","0","1275","9775"],
        ["Owen Grant","12000","600","1710","13110"],
        ["Ruth Henry","10000","500","1425","10925"],
      ],
      pascal: [
        "program MarketCheckout;",
        "var",
        "  i, customerCount: integer;",
        "  customerName: string;",
        "  subtotal, discount, taxableAmount, gct, finalAmount, totalSales: real;",
        "begin",
        "  totalSales := 0;",
        "  write('Number of customers: '); readln(customerCount);",
        "  for i := 1 to customerCount do",
        "  begin",
        "    write('Customer name: '); readln(customerName);",
        "    write('Subtotal: '); readln(subtotal);",
        "    if subtotal >= 10000 then discount := subtotal * 0.05 else discount := 0;",
        "    taxableAmount := subtotal - discount;",
        "    gct := taxableAmount * 0.15;",
        "    finalAmount := taxableAmount + gct;",
        "    totalSales := totalSales + finalAmount;",
        "    writeln(customerName, ' pays ', finalAmount:0:2);",
        "  end;",
        "  writeln('Total sales: ', totalSales:0:2);",
        "end.",
      ],
    },
    starterRows: [
      ["ProductID","ProductName","Category","UnitPrice","QuantityInStock","ReorderLevel"],
      ["PR001","Rice 2kg","Grocery","980","25","10"],
      ["PR002","Plantain Chips","Snacks","350","8","12"],
      ["PR003","Fresh Juice","Beverage","500","18","8"],
      ["PR004","Ground Coffee","Beverage","1800","6","8"],
      ["PR005","Bath Soap","Household","420","30","10"],
      ["PR006","Cereal","Grocery","1200","9","10"],
    ],
  }),

  makeProject({
    id: "community-library",
    code: "SBA 04",
    title: "HarbourView Community Library",
    sector: "Education",
    level: "Starter friendly",
    accent: "Members, loans and overdue charges",
    scenario: "HarbourView Community Library serves students and adults from nearby communities. Staff want to track members, books and loans more accurately, identify overdue items, analyse borrowing patterns and make library information easier to access.",
    purpose: "Create a connected library project that manages lending data, analyses overdue charges, prepares member communication, presents library services and automates fine calculations.",
    databaseProduce: "Create Member, Book and Loan tables. Create TWO queries: Overdue Loans using criteria and one calculated fine field, and Member Loans using related tables. Create one member form with a loan subform and one grouped overdue report.",
    databaseCompleted: [
      "Member table: MemberID, FirstName, LastName, MemberType, Phone, Email.",
      "Book table: BookID, Title, Category, Author, DailyFine.",
      "Loan table: LoanID, MemberID, BookID, DateBorrowed, DueDate, DateReturned.",
      "Queries: Overdue Loans uses the overdue criterion and one calculated FineDue field. Member Loans joins member, book and loan details.",
      "Report: group by MemberType and show count and total FineDue.",
    ],
    spreadsheetProduce: "Create a LoansAnalysis workbook with at least two worksheets. Organise it as TWO major tasks with no more than THREE requirements in each. Task A covers date/fine calculations, functions and references. Task B covers overdue filtering, a category summary with one chart, and a linked dashboard total.",
    spreadsheetCompleted: [
      "Calculate DaysLate from DueDate and DateReturned or the agreed reference date.",
      "Example fine: =IF(F2>0,F2*G2,0).",
      "Use COUNTIF to count overdue loans and AVERAGE to find the average fine.",
      "Filter to show overdue records only.",
      "Create a summary of loans by Category and a suitable chart.",
      "Link a dashboard cell to the total outstanding fines.",
    ],
    wordProduce: "Create a fillable membership form and a mail-merge overdue notice. Use clear instructions and include library contact details.",
    wordCompleted: [
      "Membership form controls: full name, member type drop-down, date picker and terms check box.",
      "Mail merge fields: MemberName, BookTitle, DueDate and FineDue.",
      "Include a clear payment or return instruction and a short table of borrowing rules.",
    ],
    webProduce: "Design one library information page with a project logo, clear navigation and content areas, services, borrowing rules, opening hours, featured categories and at least two suitable hyperlink types.",
    webCompleted: [
      "Page sections: Welcome, Services, Borrowing Rules, Opening Hours and Contact.",
      "Include one email link and one internal link to Borrowing Rules.",
      "Use headings and short paragraphs that are easy for students and adults to scan.",
    ],
    programmingProduce: "Write a program that accepts a member name, days late and member type, calculates the overdue fine, applies a student concession if required and totals all fines processed.",
    programmingCompleted: {
      problem: "Calculate the overdue amount for each library member and the total fines from all records processed.",
      inputs: ["Member name", "Days late", "Member type"],
      processes: ["Calculate base fine", "Apply student concession", "Accumulate total fines"],
      outputs: ["Member name", "Days late", "Fine", "Total