const STORAGE_PREFIX='spark_physics_section_b_progress_v1';
export function physicsThermalStorageKey(userId){const safe=String(userId||'guest').trim()||'guest';return `${STORAGE_PREFIX}:${safe}`;}
function storageOrNull(storage){if(storage)return storage;try{return typeof window!=='undefined'?window.localStorage:null}catch{return null}}
export function readPhysicsThermalProgress(userId,storage){const target=storageOrNull(storage);if(!target)return{};try{return JSON.parse(target.getItem(physicsThermalStorageKey(userId))||'{}')||{}}catch{return{}}}
export function writePhysicsThermalProgress(userId,progress,storage){const target=storageOrNull(storage);if(!target)return false;try{target.setItem(physicsThermalStorageKey(userId),JSON.stringify(progress||{}));return true}catch{return false}}
export function setPhysicsThermalCompletion(userId,progress,key,completed,storage){const next={...(progress||{}),[String(key)]:Boolean(completed)};writePhysicsThermalProgress(userId,next,storage);return next;}
export function recordPhysicsThermalResult(userId,progress,key,result,storage){const safeResult={score:Number(result?.score)||0,maxScore:Number(result?.maxScore)||0,percent:Number(result?.percent)||0,at:new Date().toISOString()};const previous=progress?.[key];const next={...(progress||{}),[key]:safeResult,[`${key}:best`]:Math.max(Number(previous?.percent)||0,Number(progress?.[`${key}:best`])||0,safeResult.percent)};writePhysicsThermalProgress(userId,next,storage);return next;}
export function physicsThermalProgressSummary(progress,topics,interactives){const p=progress||{},ts=Array.isArray(topics)?topics:[],labs=Array.isArray(interactives)?interactives:[];const labsCompleted=labs.filter(l=>p[`lab:${l.id}`]).length;const quizResults=ts.map(t=>p[`quiz:${t.id}`]).filter(Boolean);return{labsCompleted,labsTotal:labs.length,topicsPractised:quizResults.length,topicsTotal:ts.length,averageTopicPercent:quizResults.length?Math.round(quizResults.reduce((s,r)=>s+(Number(r.percent)||0),0)/quizResults.length):0,checkpointPercent:Number(p['checkpoint:B']?.percent)||0};}
export const PHYSICS_THERMAL_PROGRESS_VERSION=1;
