export const INFORMATION_TECHNOLOGY_PRACTICAL_LABS = Object.freeze([
  {
    id: "word-processing",
    title: "Word Processing Studio",
    app: "Word Processing",
    mark: "W",
    section: "Word-Processing and Web Page Design",
    description: "Create and refine a professional document using formatting, page layout, tables, review tools, mail merge and form controls.",
    outcomes: ["Formatting", "Page layout", "Tables", "Review", "Mail merge"],
  },
  {
    id: "spreadsheet",
    title: "Spreadsheet Studio",
    app: "Spreadsheet",
    mark: "X",
    section: "Spreadsheets",
    description: "Work in a live worksheet with formulae, functions, references, sorting, filtering, charts, linked sheets and pivot-style summaries.",
    outcomes: ["Formulae", "Functions", "References", "Data tools", "Charts"],
  },
  {
    id: "database",
    title: "Database Studio",
    app: "Database",
    mark: "DB",
    section: "Database Management",
    description: "Design tables, set keys and relationships, create queries, build forms and produce grouped reports.",
    outcomes: ["Tables", "Keys", "Relationships", "Queries", "Reports"],
  },
  {
    id: "presentation",
    title: "Presentation Studio",
    app: "Presentation",
    mark: "P",
    section: "Productivity Tools",
    description: "Build a coherent slide deck using layouts, themes, media, transitions, speaker notes and slide-show controls.",
    outcomes: ["Slides", "Layouts", "Themes", "Media", "Delivery"],
  },
  {
    id: "web-design",
    title: "Web Design Studio",
    app: "Web Design",
    mark: "</>",
    section: "Word-Processing and Web Page Design",
    description: "Plan and build a three-page site, add navigation and links, preview responsive layouts and run publishing checks.",
    outcomes: ["Planning", "Pages", "Links", "Media", "Testing"],
  },
  {
    id: "programming",
    title: "Programming Studio",
    app: "Programming",
    mark: "{ }",
    section: "Program Implementation",
    description: "Practise high-level syntax, variables, input/output, selection, loops, testing, debugging and documentation.",
    outcomes: ["Variables", "Selection", "Iteration", "Testing", "Debugging"],
  },
]);
