import React, { useMemo, useState } from 'react';
import MathText from '../../../practice/MathText';
import { buildConvectionLabModel, buildExpansionLabModel, buildGasLawLabModel, buildHeatingCurveLabModel, buildJouleLabModel, buildKelvinGraphModel, buildLatentHeatFusionLabModel, buildRadiationLabModel, buildSpecificHeatLabModel } from '../interactives/bThermalInteractiveModels.mjs';
import { THERMAL_INTERACTIVES } from '../interactives/bThermalInteractiveRegistry.mjs';
import './physicsThermal.css';

const fmt=(n,d=2)=>Number(n).toFixed(d).replace(/\.00$/,'').replace(/(\.\d*[1-9])0+$/,'$1');
function Range({label,value,setValue,min,max,step=1,unit=''}){return <label className="pm-control"><span><b>{label}</b><output>{fmt(value,step<1?2:0)}{unit}</output></span><input aria-label={label} aria-valuetext={`${fmt(value,step<1?2:0)}${unit}`} type="range" min={min} max={max} step={step} value={value} onChange={e=>setValue(Number(e.target.value))}/></label>}
function Metrics({items}){return <div className="pm-metrics">{items.map(([label,value])=><div className="pm-metric" key={label}><strong><MathText prose>{String(value)}</MathText></strong><span>{label}</span></div>)}</div>}
function LabShell({meta,children,note}){return <article className="pm-lab-frame thermal-lab"><div className="pm-lab-heading"><div className="pm-eyebrow">{meta.topic} interactive</div><h3>{meta.title}</h3><p>{meta.action}</p></div>{children}{note&&<div className="pm-lab-note"><MathText prose>{note}</MathText></div>}</article>}

function JouleLab({meta}){const[m,setM]=useState(2),[h,setH]=useState(5),[eff,setEff]=useState(.92);const r=useMemo(()=>buildJouleLabModel({massKg:m,heightM:h,efficiency:eff}),[m,h,eff]);return <LabShell meta={meta} note="The missing energy is not destroyed. In a real experiment some energy warms the paddle, container and surroundings."><div className="pm-controls-grid"><Range label="Falling mass" value={m} setValue={setM} min={.5} max={5} step={.5} unit=" kg"/><Range label="Drop height" value={h} setValue={setH} min={1} max={10} step={.5} unit=" m"/><Range label="Energy reaching water" value={Math.round(eff*100)} setValue={v=>setEff(v/100)} min={60} max={100} step={1} unit="%"/></div><div className="thermal-energy-flow"><i style={{width:`${eff*100}%`}}/><span>mechanical work → thermal energy</span></div><Metrics items={[["Mechanical work",`${fmt(r.workJ)} J`],["To water",`${fmt(r.toWaterJ)} J`],["Water temperature rise",`${fmt(r.temperatureRiseC,3)} °C`]]}/></LabShell>}
function GasLab({meta}){const[law,setLaw]=useState('boyle'),[p,setP]=useState(100),[v1,setV1]=useState(300),[v2,setV2]=useState(150),[t1,setT1]=useState(27),[t2,setT2]=useState(127);const r=useMemo(()=>buildGasLawLabModel({law,p1KPa:p,v1Cm3:v1,v2Cm3:v2,t1C:t1,t2C:t2}),[law,p,v1,v2,t1,t2]);return <LabShell meta={meta} note="Gas-law temperatures are absolute temperatures. Convert Celsius to kelvin before using Charles' law or the pressure law."><div className="thermal-segment" role="group" aria-label="Gas law"><button type="button" aria-pressed={law==='boyle'} className={law==='boyle'?'active':''} onClick={()=>setLaw('boyle')}>Boyle</button><button type="button" aria-pressed={law==='charles'} className={law==='charles'?'active':''} onClick={()=>setLaw('charles')}>Charles</button><button type="button" aria-pressed={law==='pressure'} className={law==='pressure'?'active':''} onClick={()=>setLaw('pressure')}>Pressure law</button></div><div className="pm-controls-grid"><Range label="Initial pressure" value={p} setValue={setP} min={50} max={300} step={10} unit=" kPa"/><Range label="Initial volume" value={v1} setValue={setV1} min={100} max={500} step={10} unit=" cm³"/>{law==='boyle'?<Range label="Final volume" value={v2} setValue={setV2} min={80} max={500} step={10} unit=" cm³"/>:<><Range label="Initial temperature" value={t1} setValue={setT1} min={-50} max={100} step={1} unit=" °C"/><Range label="Final temperature" value={t2} setValue={setT2} min={-20} max={200} step={1} unit=" °C"/></>}</div><div className="thermal-pistons"><div style={{width:`${Math.min(100,v1/5)}%`}}>State 1</div><div style={{width:`${Math.min(100,r.v2Cm3/5)}%`}}>State 2</div></div><Metrics items={law==='boyle'?[["Final pressure",`${fmt(r.p2KPa)} kPa`],["P₁V₁",`${fmt(p*v1)} kPa cm³`],["P₂V₂",`${fmt(r.p2KPa*v2)} kPa cm³`]]:law==='pressure'?[["T₁",`${r.t1K} K`],["T₂",`${r.t2K} K`],["Final pressure",`${fmt(r.p2KPa)} kPa`],["P₁/T₁",`${fmt(p/r.t1K,3)} kPa/K`],["P₂/T₂",`${fmt(r.p2KPa/r.t2K,3)} kPa/K`]]:[["T₁",`${r.t1K} K`],["T₂",`${r.t2K} K`],["Final volume",`${fmt(r.v2Cm3)} cm³`]]}/></LabShell>}
function KelvinLab({meta}){
  const[slope,setSlope]=useState(.35);
  const r=useMemo(()=>buildKelvinGraphModel({slope}),[slope]);
  const plot=useMemo(()=>{
    const left=70,right=620,top=26,bottom=190,minC=-300,maxC=120,maxValue=.7*393;
    const xy=(c,value)=>({x:left+(c-minC)/(maxC-minC)*(right-left),y:bottom-value/maxValue*(bottom-top)});
    const points=r.points.map(p=>({...p,...xy(p.c,p.value)}));
    const start=xy(-273,0),end=xy(120,slope*(120+273));
    const zeroX=xy(0,0).x,maxX=xy(120,0).x;
    return{points,start,end,zeroX,maxX,left,right,top,bottom};
  },[r,slope]);
  return <LabShell meta={meta} note={r.note}>
    <div className="pm-controls-grid"><Range label="Relative gas-pressure scale" value={slope} setValue={setSlope} min={.15} max={.7} step={.05}/></div>
    <svg className="thermal-kelvin-graph" viewBox="0 0 660 240" role="img" aria-label="Idealised gas pressure against Celsius temperature extrapolated to minus 273 degrees Celsius">
      <line className="thermal-grid" x1="70" y1="80" x2="620" y2="80"/><line className="thermal-grid" x1="70" y1="135" x2="620" y2="135"/>
      <line className="thermal-axis" x1="70" y1="190" x2="625" y2="190"/><line className="thermal-axis" x1="70" y1="22" x2="70" y2="194"/>
      <line data-testid="kelvin-trend" className="thermal-trend" x1={plot.start.x} y1={plot.start.y} x2={plot.end.x} y2={plot.end.y}/>
      {plot.points.map((point,index)=><circle key={index} cx={point.x} cy={point.y} r="5" className="thermal-point"/>)}
      <text x="6" y="22">relative pressure</text><text x="500" y="222">temperature / °C</text>
      <text x={plot.start.x} y="210" textAnchor="middle" style={{fill:'var(--pm-primary)',fontWeight:800}}>{String.fromCharCode(8722)}273</text>
      <text x={plot.zeroX} y="210" textAnchor="middle">0</text>
      <text x={plot.maxX} y="210" textAnchor="middle">120</text>
    </svg>
    <Metrics items={[["Extrapolated zero-pressure intercept","−273 °C"],["Absolute zero","0 K"],["Room-temperature example","27 °C = 300 K"]]}/>
  </LabShell>
}
function ExpansionLab({meta}){
  const[l,setL]=useState(2),[dt,setDt]=useState(80);
  const r=useMemo(()=>buildExpansionLabModel({initialLengthM:l,temperatureRiseC:dt}),[l,dt]);
  const extensionMm=r.extensionM*1000;
  const extensionDisplay=Math.min(18,extensionMm*1.5);
  const specimenWidth=Math.min(96,38+(l/10)*40+extensionDisplay);
  return <LabShell meta={meta} note="Most solids expand only a small amount, but long structures need gaps, rollers or slack because even a small fractional change becomes important over a large length.">
    <div className="pm-controls-grid"><Range label="Initial length" value={l} setValue={setL} min={.5} max={10} step={.5} unit=" m"/><Range label="Temperature rise" value={dt} setValue={setDt} min={0} max={150} step={5} unit={' '+String.fromCharCode(176)+'C'}/></div>
    <div className="thermal-expansion" aria-label={`Solid specimen with a calculated extension of ${fmt(extensionMm,3)} millimetres`}>
      <div style={{position:'relative',height:24,width:`${specimenWidth}%`,maxWidth:'100%',borderRadius:6,background:'var(--pm-line)',overflow:'hidden',transition:'width .2s ease'}}>
        <i aria-hidden="true" style={{position:'absolute',right:0,top:0,bottom:0,width:`${extensionDisplay}%`,background:'var(--pm-primary)',transition:'width .2s ease'}}/>
      </div>
      <span style={{fontSize:12,color:'var(--pm-muted)'}}>{extensionMm>0?'Highlighted end = calculated extension, enlarged for visibility.':'No extension when the temperature change is 0 K.'}</span>
    </div>
    <Metrics items={[["Extension",`${fmt(extensionMm,3)} mm`],["Final length",`${fmt(r.finalLengthM,5)} m`],["Temperature change",`${dt} K`]]}/>
  </LabShell>
}
function HeatingCurveLab({meta}){const[e,setE]=useState(0),[m,setM]=useState(.25);const r=useMemo(()=>buildHeatingCurveLabModel({energyKJ:e,massKg:m}),[e,m]);return <LabShell meta={meta} note="During melting and boiling, temperature stays constant while energy changes the particle arrangement. After the phase change is complete, further energy raises the temperature again."><div className="pm-controls-grid"><Range label="Energy added" value={e} setValue={setE} min={0} max={800} step={5} unit=" kJ"/><Range label="Sample mass" value={m} setValue={setM} min={.1} max={.5} step={.05} unit=" kg"/></div><div className="thermal-stage"><strong>{r.phase}</strong><span>{fmt(r.temperatureC,1)} °C</span>{r.fractionChanged!=null&&<i style={{width:`${Math.max(2,r.fractionChanged*100)}%`}}/>}</div><Metrics items={[["Phase / stage",r.phase],["Temperature",`${fmt(r.temperatureC,1)} °C`],["Phase fraction",r.fractionChanged==null?'Not changing phase':`${fmt(r.fractionChanged*100,1)}%`]]}/></LabShell>}
function SpecificHeatLab({meta}){const[p,setP]=useState(48),[time,setTime]=useState(300),[mass,setMass]=useState(.8),[dt,setDt]=useState(16);const r=useMemo(()=>buildSpecificHeatLabModel({powerW:p,timeS:time,massKg:mass,deltaTC:dt}),[p,time,mass,dt]);return <LabShell meta={meta} note="In the real practical, lag the block, measure its mass, improve thermometer contact and account for energy transferred to the surroundings."><div className="pm-controls-grid"><Range label="Heater power" value={p} setValue={setP} min={20} max={100} step={2} unit=" W"/><Range label="Heating time" value={time} setValue={setTime} min={60} max={600} step={30} unit=" s"/><Range label="Block mass" value={mass} setValue={setMass} min={.2} max={2} step={.1} unit=" kg"/><Range label="Temperature rise" value={dt} setValue={setDt} min={5} max={50} step={1} unit=" °C"/></div><Metrics items={[["Electrical energy",`${fmt(r.energyJ)} J`],["Measured c",`${fmt(r.specificHeat)} J/(kg K)`],["Check E = mcΔT",`${fmt(r.idealEnergyCheck)} J`]]}/></LabShell>}
function LatentHeatLab({meta}){const[v,setV]=useState(12),[i,setI]=useState(2),[time,setTime]=useState(300),[massG,setMassG]=useState(20),[backgroundG,setBackgroundG]=useState(2);const r=useMemo(()=>buildLatentHeatFusionLabModel({voltageV:v,currentA:i,timeS:time,massMeltedKg:massG/1000,backgroundMassKg:backgroundG/1000}),[v,i,time,massG,backgroundG]);return <LabShell meta={meta} note="A control run estimates ice melted by energy from the surroundings. Subtract that background mass before calculating L. Use ice already at 0 °C and keep water away from exposed electrical connections."><div className="pm-controls-grid"><Range label="Heater voltage" value={v} setValue={setV} min={4} max={24} step={1} unit=" V"/><Range label="Heater current" value={i} setValue={setI} min={.5} max={5} step={.1} unit=" A"/><Range label="Heating time" value={time} setValue={setTime} min={60} max={600} step={30} unit=" s"/><Range label="Mass melted" value={massG} setValue={setMassG} min={5} max={80} step={1} unit=" g"/><Range label="Control melt" value={backgroundG} setValue={setBackgroundG} min={0} max={20} step={1} unit=" g"/></div><Metrics items={[["Electrical energy",`${fmt(r.energyJ)} J`],["Corrected mass",`${fmt(r.correctedMassKg*1000,1)} g`],["Measured L",`${fmt(r.specificLatentHeatJPerKg/1000,1)} kJ/kg`]]}/></LabShell>}
function RadiationLab({meta}){const[t,setT]=useState(80);const r=useMemo(()=>buildRadiationLabModel({temperatureC:t}),[t]);return <LabShell meta={meta} note="This is a relative comparison, not a CSEC Stefan-Boltzmann calculation. The syllabus focus is the effect of surface nature and texture on absorption and emission."><div className="pm-controls-grid"><Range label="Surface temperature" value={t} setValue={setT} min={30} max={150} step={5} unit=" °C"/></div><div className="thermal-radiation-bars">{r.surfaces.map(s=><div key={s.surface}><span>{s.surface.replace('-',' ')}</span><i style={{width:`${s.relativeIndex*100}%`}}/></div>)}</div><Metrics items={r.surfaces.map(s=>[s.surface,`${fmt(s.relativeIndex*100,0)} relative`])}/></LabShell>}
function ConvectionLab({meta}){const[bottom,setBottom]=useState(80),[top,setTop]=useState(30);const r=useMemo(()=>buildConvectionLabModel({bottomTempC:bottom,topTempC:top}),[bottom,top]);return <LabShell meta={meta} note="Warm fluid rises because heating usually lowers its density relative to surrounding cooler fluid, not simply because it is 'hot'."><div className="pm-controls-grid"><Range label="Bottom temperature" value={bottom} setValue={setBottom} min={20} max={100} step={5} unit=" °C"/><Range label="Top temperature" value={top} setValue={setTop} min={20} max={100} step={5} unit=" °C"/></div><div className="thermal-convection" aria-label="Convection current strength"><span>↑</span><i style={{height:`${20+70*r.currentStrength}%`}}/><span>↓</span></div><Metrics items={[["Temperature difference",`${fmt(r.deltaC)} °C`],["Relative current",`${fmt(r.currentStrength*100,0)}%`],["Model state",r.state]]}/></LabShell>}

const COMPONENTS={'b1-joule-work-heat':JouleLab,'b2-gas-laws':GasLab,'b2-kelvin-extrapolation':KelvinLab,'b2-expansion':ExpansionLab,'b3-heating-curve':HeatingCurveLab,'b3-specific-heat':SpecificHeatLab,'b3-latent-heat':LatentHeatLab,'b4-radiation-surfaces':RadiationLab,'b4-convection':ConvectionLab};
export default function ThermalInteractiveLab({interactiveId}){const meta=THERMAL_INTERACTIVES.find(x=>x.id===interactiveId);if(!meta)return <div className="pm-empty">Interactive not found.</div>;const Component=COMPONENTS[interactiveId];return Component?<Component meta={meta}/>:<div className="pm-empty">Interactive implementation unavailable.</div>}
