import React, { useMemo, useState } from 'react';
import MathText from '../../../practice/MathText';
import { buildConvectionLabModel, buildExpansionLabModel, buildGasLawLabModel, buildHeatingCurveLabModel, buildJouleLabModel, buildKelvinGraphModel, buildRadiationLabModel, buildSpecificHeatLabModel } from '../interactives/bThermalInteractiveModels.mjs';
import { THERMAL_INTERACTIVES } from '../interactives/bThermalInteractiveRegistry.mjs';
import './physicsThermal.css';

const fmt=(n,d=2)=>Number(n).toFixed(d).replace(/\.00$/,'').replace(/(\.\d*[1-9])0+$/,'$1');
function Range({label,value,setValue,min,max,step=1,unit=''}){return <label className="pm-control"><span><b>{label}</b><output>{fmt(value,step<1?2:0)}{unit}</output></span><input type="range" min={min} max={max} step={step} value={value} onChange={e=>setValue(Number(e.target.value))}/></label>}
function Metrics({items}){return <div className="pm-metrics">{items.map(([label,value])=><div className="pm-metric" key={label}><strong><MathText prose>{String(value)}</MathText></strong><span>{label}</span></div>)}</div>}
function LabShell({meta,children,note}){return <article className="pm-lab-frame thermal-lab"><div className="pm-lab-heading"><div className="pm-eyebrow">{meta.topic} interactive</div><h3>{meta.title}</h3><p>{meta.action}</p></div>{children}{note&&<div className="pm-lab-note"><MathText prose>{note}</MathText></div>}</article>}

function JouleLab({meta}){const[m,setM]=useState(2),[h,setH]=useState(5),[eff,setEff]=useState(.92);const r=useMemo(()=>buildJouleLabModel({massKg:m,heightM:h,efficiency:eff}),[m,h,eff]);return <LabShell meta={meta} note="The missing energy is not destroyed. In a real experiment some energy warms the paddle, container and surroundings."><div className="pm-controls-grid"><Range label="Falling mass" value={m} setValue={setM} min={.5} max={5} step={.5} unit=" kg"/><Range label="Drop height" value={h} setValue={setH} min={1} max={10} step={.5} unit=" m"/><Range label="Energy reaching water" value={Math.round(eff*100)} setValue={v=>setEff(v/100)} min={60} max={100} step={1} unit="%"/></div><div className="thermal-energy-flow"><i style={{width:`${eff*100}%`}}/><span>mechanical work → thermal energy</span></div><Metrics items={[["Mechanical work",`${fmt(r.workJ)} J`],["To water",`${fmt(r.toWaterJ)} J`],["Water temperature rise",`${fmt(r.temperatureRiseC,3)} °C`]]}/></LabShell>}
function GasLab({meta}){const[law,setLaw]=useState('boyle'),[p,setP]=useState(100),[v1,setV1]=useState(300),[v2,setV2]=useState(150),[t1,setT1]=useState(27),[t2,setT2]=useState(127);const r=useMemo(()=>buildGasLawLabModel({law,p1KPa:p,v1Cm3:v1,v2Cm3:v2,t1C:t1,t2C:t2}),[law,p,v1,v2,t1,t2]);return <LabShell meta={meta} note="Gas-law temperatures are absolute temperatures. Convert Celsius to kelvin before using Charles' law or the pressure law."><div className="thermal-segment"><button type="button" className={law==='boyle'?'active':''} onClick={()=>setLaw('boyle')}>Boyle</button><button type="button" className={law==='charles'?'active':''} onClick={()=>setLaw('charles')}>Charles</button></div><div className="pm-controls-grid"><Range label="Initial pressure" value={p} setValue={setP} min={50} max={300} step={10} unit=" kPa"/><Range label="Initial volume" value={v1} setValue={setV1} min={100} max={500} step={10} unit=" cm³"/>{law==='boyle'?<Range label="Final volume" value={v2} setValue={setV2} min={80} max={500} step={10} unit=" cm³"/>:<><Range label="Initial temperature" value={t1} setValue={setT1} min={-50} max={100} step={1} unit=" °C"/><Range label="Final temperature" value={t2} setValue={setT2} min={-20} max={200} step={1} unit=" °C"/></>}</div><div className="thermal-pistons"><div style={{width:`${Math.min(100,v1/5)}%`}}>State 1</div><div style={{width:`${Math.min(100,r.v2Cm3/5)}%`}}>State 2</div></div><Metrics items={law==='boyle'?[["Final pressure",`${fmt(r.p2KPa)} kPa`],["P₁V₁",`${fmt(p*v1)} kPa cm³`],["P₂V₂",`${fmt(r.p2KPa*v2)} kPa cm³`]]:[["T₁",`${r.t1K} K`],["T₂",`${r.t2K} K`],["Final volume",`${fmt(r.v2Cm3)} cm³`]]}/></LabShell>}
function KelvinLab({meta}){const[slope,setSlope]=useState(.35);const r=useMemo(()=>buildKelvinGraphModel({slope}),[slope]);return <LabShell meta={meta} note={r.note}><div className="pm-controls-grid"><Range label="Graph scale" value={slope} setValue={setSlope} min={.15} max={.7} step={.05}/></div><div className="thermal-graph" role="img" aria-label="Idealised pressure against Celsius temperature line extrapolated to minus 273 degrees Celsius"><div className="thermal-graph-axis y"/><div className="thermal-graph-axis x"/><div className="thermal-graph-line"/><span className="thermal-zero">−273 °C</span>{r.points.map((p,i)=><i key={i} style={{left:`${18+(p.c+200)/300*72}%`,bottom:`${18+Math.min(70,p.value/(slope*373)*70)}%`}}/>)}</div><Metrics items={[["Extrapolated intercept","−273 °C"],["Kelvin zero","0 K"],["27 °C","300 K"]]}/></LabShell>}
function ExpansionLab({meta}){const[l,setL]=useState(2),[dt,setDt]=useState(80);const r=useMemo(()=>buildExpansionLabModel({initialLengthM:l,temperatureRiseC:dt}),[l,dt]);return <LabShell meta={meta} note="Most solids expand only a small amount, but long structures need gaps, rollers or slack because even a small fractional change becomes important over a large length."><div className="pm-controls-grid"><Range label="Initial length" value={l} setValue={setL} min={.5} max={10} step={.5} unit=" m"/><Range label="Temperature rise" value={dt} setValue={setDt} min={0} max={150} step={5} unit=" °C"/></div><div className="thermal-expansion"><div/><div style={{width:`${Math.min(100,70+r.extensionM*5000)}%`}}/></div><Metrics items={[["Extension",`${fmt(r.extensionM*1000,3)} mm`],["Final length",`${fmt(r.finalLengthM,5)} m`],["Temperature change",`${dt} K`]]}/></LabShell>}
function HeatingCurveLab({meta}){const[e,setE]=useState(0),[m,setM]=useState(.25);const r=useMemo(()=>buildHeatingCurveLabModel({energyKJ:e,massKg:m}),[e,m]);return <LabShell meta={meta} note="During melting and boiling, energy changes the particle arrangement rather than increasing average kinetic energy, so temperature stays constant."><div className="pm-controls-grid"><Range label="Energy added" value={e} setValue={setE} min={0} max={800} step={5} unit=" kJ"/><Range label="Sample mass" value={m} setValue={setM} min={.1} max={.5} step={.05} unit=" kg"/></div><div className="thermal-stage"><strong>{r.phase}</strong><span>{fmt(r.temperatureC,1)} °C</span>{r.fractionChanged!=null&&<i style={{width:`${Math.max(2,r.fractionChanged*100)}%`}}/>}</div><Metrics items={[["Phase / stage",r.phase],["Temperature",`${fmt(r.temperatureC,1)} °C`],["Phase fraction",r.fractionChanged==null?'Not changing phase':`${fmt(r.fractionChanged*100,1)}%`]]}/></LabShell>}
function SpecificHeatLab({meta}){const[p,setP]=useState(48),[time,setTime]=useState(300),[mass,setMass]=useState(.8),[dt,setDt]=useState(16);const r=useMemo(()=>buildSpecificHeatLabModel({powerW:p,timeS:time,massKg:mass,deltaTC:dt}),[p,time,mass,dt]);return <LabShell meta={meta} note="In the real practical, lag the block, measure its mass, improve thermometer contact and account for energy transferred to the surroundings."><div className="pm-controls-grid"><Range label="Heater power" value={p} setValue={setP} min={20} max={100} step={2} unit=" W"/><Range label="Heating time" value={time} setValue={setTime} min={60} max={600} step={30} unit=" s"/><Range label="Block mass" value={mass} setValue={setMass} min={.2} max={2} step={.1} unit=" kg"/><Range label="Temperature rise" value={dt} setValue={setDt} min={5} max={50} step={1} unit=" °C"/></div><Metrics items={[["Electrical energy",`${fmt(r.energyJ)} J`],["Measured c",`${fmt(r.specificHeat)} J/(kg K)`],["Check E = mcΔT",`${fmt(r.idealEnergyCheck)} J`]]}/></LabShell>}
function RadiationLab({meta}){const[t,setT]=useState(80);const r=useMemo(()=>buildRadiationLabModel({temperatureC:t}),[t]);return <LabShell meta={meta} note="This is a relative comparison, not a CSEC Stefan-Boltzmann calculation. The syllabus focus is the effect of surface nature and texture on absorption and emission."><div className="pm-controls-grid"><Range label="Surface temperature" value={t} setValue={setT} min={30} max={150} step={5} unit=" °C"/></div><div className="thermal-radiation-bars">{r.surfaces.map(s=><div key={s.surface}><span>{s.surface.replace('-',' ')}</span><i style={{width:`${s.relativeIndex*100}%`}}/></div>)}</div><Metrics items={r.surfaces.map(s=>[s.surface,`${fmt(s.relativeIndex*100,0)} relative`])}/></LabShell>}
function ConvectionLab({meta}){const[bottom,setBottom]=useState(80),[top,setTop]=useState(30);const r=useMemo(()=>buildConvectionLabModel({bottomTempC:bottom,topTempC:top}),[bottom,top]);return <LabShell meta={meta} note="Warm fluid rises because heating usually lowers its density relative to surrounding cooler fluid, not simply because it is 'hot'."><div className="pm-controls-grid"><Range label="Bottom temperature" value={bottom} setValue={setBottom} min={20} max={100} step={5} unit=" °C"/><Range label="Top temperature" value={top} setValue={setTop} min={20} max={100} step={5} unit=" °C"/></div><div className="thermal-convection" aria-label="Convection current strength"><span>↑</span><i style={{height:`${20+70*r.currentStrength}%`}}/><span>↓</span></div><Metrics items={[["Temperature difference",`${fmt(r.deltaC)} °C`],["Relative current",`${fmt(r.currentStrength*100,0)}%`],["Model state",r.state]]}/></LabShell>}

const COMPONENTS={'b1-joule-work-heat':JouleLab,'b2-gas-laws':GasLab,'b2-kelvin-extrapolation':KelvinLab,'b2-expansion':ExpansionLab,'b3-heating-curve':HeatingCurveLab,'b3-specific-heat':SpecificHeatLab,'b4-radiation-surfaces':RadiationLab,'b4-convection':ConvectionLab};
export default function ThermalInteractiveLab({interactiveId}){const meta=THERMAL_INTERACTIVES.find(x=>x.id===interactiveId);if(!meta)return <div className="pm-empty">Interactive not found.</div>;const Component=COMPONENTS[interactiveId];return Component?<Component meta={meta}/>:<div className="pm-empty">Interactive implementation unavailable.</div>}
