export const A1_LESSON = Object.freeze({
  id: 'A1',
  title: 'Scientific Method and Measurement',
  purpose: 'How physics tests ideas, measures quantities, analyses data and decides whether a conclusion is trustworthy.',
  objectives: [
    ['A1.1','discuss how the methodology employed by Galileo contributed to the development of Physics'],
    ['A1.2','investigate the factors which might affect the period of a simple pendulum'],
    ['A1.3','use graphs of experimental data from the simple pendulum'],
    ['A1.4','draw a line of ‘best fit’ for a set of plotted values'],
    ['A1.5','determine the gradient of the straight line graph'],
    ['A1.6','express the result of a measurement or calculation to an appropriate number of significant figures'],
    ['A1.7','discuss possible types and sources of error in any measurement'],
    ['A1.8','use a variety of instruments to measure different quantities'],
    ['A1.9','assess the suitability of instruments on the basis of sensitivity, accuracy and range'],
    ['A1.10','apply the formula for density: ρ = m / V'],
  ].map(([id,text])=>({id,text})),
  sections: [
    { id:'scientific-method', heading:'Physics is tested by evidence', body:'A useful investigation moves from observation to a testable question, hypothesis, experiment, measurements, analysis and conclusion. Change one manipulated variable, measure the responding variable and keep important controlled variables fixed.' },
    { id:'galileo', heading:'Galileo and scientific methodology', body:'Galileo helped establish a method in which claims about motion were tested by observation, measurement and experiment, and the results were described mathematically. The key idea is evidence testing an explanation, not a story about one famous experiment.' },
    { id:'pendulum', heading:'The simple pendulum', body:'For a simple pendulum, mass does not affect the ideal period. Increasing length increases the period. At small angular displacements the period changes very little with amplitude; at larger amplitudes it becomes slightly longer. Measure length from the support to the centre of the bob, release without pushing, time many oscillations, repeat and average.' },
    { id:'graphs', heading:'Tables, graphs and best fit', body:'For “plot y against x”, y is vertical and x is horizontal. Label each axis with quantity and unit, choose a sensible scale, plot fine points and draw a best-fit line or smooth curve rather than joining points dot-to-dot.' },
    { id:'gradient', heading:'Gradient', body:'For a straight line, gradient = Δy/Δx. Use two points on the best-fit line that are far apart, ideally forming a triangle spanning at least half the line. The gradient unit is the vertical-axis unit divided by the horizontal-axis unit.' },
    { id:'precision', heading:'Significant figures and precision', body:'Record results to precision justified by the apparatus and question. Keep extra calculator digits during working and round at the end. Significant figures and decimal places are different ideas.' },
    { id:'errors', heading:'Errors and uncertainty', body:'Random errors vary between readings and can be reduced by repetition and averaging. Systematic errors shift readings consistently and require calibration, zero correction or a changed method. Parallax comes from viewing an analogue scale at an angle. Reaction-time variation is not safely treated as a constant error.' },
    { id:'instruments', heading:'Choosing and reading instruments', body:'Use a metre rule or tape for larger lengths, a vernier caliper for small internal/external dimensions, a micrometer for very small diameters or thicknesses, a balance for mass, a clock or stopwatch for time and a measuring cylinder for liquid volume. Read a concave meniscus such as water at the bottom and a convex meniscus at the top, with the eye level with the surface.' },
    { id:'suitability', heading:'Sensitivity, accuracy and range', body:'Sensitivity concerns the size of change represented or detected by the instrument, accuracy concerns closeness to the accepted value, and range is the interval it can measure. A sensitive instrument can still be inaccurate if it has a calibration or zero error.' },
    { id:'density', heading:'Density', body:'Density is mass per unit volume, ρ = m/V. For an irregular solid, use water displacement and subtract the initial volume from the final volume. Keep units consistent; 1 g cm⁻³ = 1000 kg m⁻³.' },
  ],
  formulas: [
    {label:'Density', equation:'ρ = m/V', unit:'kg m⁻³ or g cm⁻³'},
    {label:'Period from repeated timing', equation:'T = t_N/N', unit:'s'},
    {label:'Simple pendulum, small-angle approximation', equation:'T = 2π√(l/g)', unit:'s'},
    {label:'Linear pendulum relation', equation:'T² = (4π²/g)l', unit:'s²'},
    {label:'Gradient', equation:'Δy/Δx', unit:'vertical unit / horizontal unit'},
  ],
  interactives: ['Pendulum Lab','Plot the Points','Best-Fit Challenge','Gradient Tool','Instrument Explorer','Density by Displacement'],
  stopShipTruths: [
    'Do not teach that pendulum amplitude has no effect at every angle.',
    'Do not classify human reaction time as a fixed systematic error by default.',
    'Do not teach “read the bottom of the meniscus” as a universal rule for every liquid.',
    'Do not define sensitivity and accuracy as synonyms.',
    'Do not teach a universal calculator-style significant-figures rule without regard to apparatus or question wording.',
  ],
});
