// SPARK Physics A3 Statics production-candidate bank.
// All questions are original. `profile` is the demand of THIS item, not an
// official profile attached to the syllabus objective.

export const A3_OBJECTIVES = Object.freeze({
  'A3.1': 'explain the effects of forces',
  'A3.2': 'identify types of forces',
  'A3.3': 'determine the weight of objects',
  'A3.4': 'show how derived quantities and their related units are produced',
  'A3.5': 'recall the special names given to the units for some derived quantities',
  'A3.6': 'express derived units using the index notation',
  'A3.7': 'identify situations in which the application of a force will result in a turning effect',
  'A3.8': 'define the moment of a force, T',
  'A3.9': 'apply the principle of moments',
  'A3.10': 'explain the action of common tools and devices as levers',
  'A3.11': 'determine the location of the centre of gravity of a body',
  'A3.12': 'relate the stability of an object to the position of its centre of gravity and its weight',
  'A3.13': 'investigate the relationship between extension and force',
  'A3.14': "solve problems using Hooke's law",
});

const q = (id, objective, profile, stem, options, answer, explanation, traps, tags=[]) => ({
  id, objective, topic:'A3', profile, stem, options, answer, explanation, traps, tags,
});

export const A3_MCQ_BANK = Object.freeze([
  // A3.1 Effects of forces
  q('a3-1-01','A3.1','KC','Which change can be produced by a force acting on a body?',
    ['A change in its mass only','A change in its shape','A change in the amount of matter in it','A change in its chemical composition only'],1,
    'A force can change the size, shape or motion of a body.',
    ['A force does not create or remove matter.','','Amount of matter is mass.','A mechanical force does not have to change chemical composition.'],['force-effects']),
  q('a3-1-02','A3.1','UK','A moving ball is struck sideways and continues with nearly the same speed in a new direction. What effect has the force had?',
    ['Changed the mass','Changed the velocity','Changed only the size','Produced no change because the speed is similar'],1,
    'Velocity includes direction, so changing direction changes velocity even if speed is almost unchanged.',
    ['Mass need not change.','','The ball need not change size.','A direction change is a change of motion.'],['force-effects','vector-link']),
  q('a3-1-03','A3.1','KC','Stretching a spring demonstrates that a force can change a body\'s',
    ['shape and size','mass and density only','temperature only','chemical identity'],0,
    'Stretching changes the dimensions and shape of the spring.',
    ['','Mass is not created by stretching.','Heating is not the defining effect here.','The material remains the same substance.'],['force-effects']),

  // A3.2 Types of forces
  q('a3-2-01','A3.2','KC','A small charged comb attracts pieces of paper. The interaction is primarily',
    ['gravitational','electric','nuclear','magnetic'],1,
    'Charges produce electric forces.',
    ['Gravity is far too weak to explain the effect.','','Nuclear force acts over nuclear distances.','A charged comb is an electrostatic example.'],['force-types']),
  q('a3-2-02','A3.2','KC','The force responsible for the weight of a book is',
    ['magnetic','nuclear','gravitational','electric'],2,
    'Weight is the gravitational force acting on a mass.',
    ['A book does not need to be magnetic.','Nuclear force acts inside nuclei.','','Electric interactions are not what the term weight means.'],['force-types','weight']),
  q('a3-2-03','A3.2','KC','Which force binds protons and neutrons within a nucleus?',
    ['nuclear','gravitational','magnetic','frictional'],0,
    'The strong nuclear interaction binds nucleons in the nucleus.',
    ['','Gravity is negligible at this scale.','Magnetism is not the binding force of the nucleus.','Friction is a contact force between surfaces.'],['force-types']),

  // A3.3 Weight
  q('a3-3-01','A3.3','UK','A bag has mass 3.2 kg. Taking g = 10 N/kg, its weight is',
    ['0.32 N','3.2 N','32 N','320 N'],2,
    'W = mg = 3.2 × 10 = 32 N.',
    ['This divides by g.','This copies the mass as a force.','','This has an extra factor of ten.'],['weight','calculation']),
  q('a3-3-02','A3.3','UK','An object weighs 75 N where the gravitational field strength is 10 N/kg. Its mass is',
    ['7.5 kg','75 kg','750 kg','0.75 kg'],0,
    'm = W/g = 75/10 = 7.5 kg.',
    ['','This confuses weight with mass.','This multiplies instead of divides.','This divides by 100.'],['weight','rearrangement']),
  q('a3-3-03','A3.3','KC','Which statement about mass and weight is correct?',
    ['Both are measured in newtons','Mass depends on gravitational field strength but weight does not','Weight is a force, while mass is measured in kilograms','Mass and weight are always numerically equal'],2,
    'Weight is a force measured in newtons; mass is measured in kilograms.',
    ['Mass is measured in kilograms.','The dependence is the other way around.','','They are related by W = mg, so they are not generally numerically equal.'],['weight','mass-v-weight']),

  // A3.4 Derived quantities and units
  q('a3-4-01','A3.4','UK','Since density = mass/volume, the SI unit of density is',
    ['kg m⁻³','kg m³','m³ kg⁻¹','kg m⁻²'],0,
    'kg divided by m³ is kg m⁻³.',
    ['','This multiplies by volume.','This is the reciprocal.','Volume is cubic, not square.'],['derived-units','density']),
  q('a3-4-02','A3.4','UK','Using force = mass × acceleration, the unit of force can be written as',
    ['kg m s⁻¹','kg m s⁻²','kg m² s⁻²','m s⁻²'],1,
    'kg × m s⁻² = kg m s⁻².',
    ['This is momentum.','','This is the base-unit form associated with energy.','This is acceleration without the mass factor.'],['derived-units','force']),
  q('a3-4-03','A3.4','UK','Pressure is force divided by area. Which base-unit expression is equivalent to the pascal?',
    ['kg m s⁻²','kg m⁻¹ s⁻²','kg m² s⁻²','kg⁻¹ m s²'],1,
    'Pa = N/m² = (kg m s⁻²)/m² = kg m⁻¹ s⁻².',
    ['This is force.','','This corresponds to energy.','This is not obtained by dividing force by area.'],['derived-units','pressure']),

  // A3.5 Named units
  q('a3-5-01','A3.5','KC','The special name for kg m s⁻² is the',
    ['joule','newton','watt','pascal'],1,
    'kg m s⁻² is one newton.',
    ['A joule is N m.','','A watt is J/s.','A pascal is N/m².'],['named-units']),
  q('a3-5-02','A3.5','KC','Which named unit is used for pressure?',
    ['watt','hertz','pascal','joule'],2,
    ['','', '', ''][2] || 'Pressure is measured in pascals (Pa).',
    ['Watt is power.','Hertz is frequency.','','Joule is work and energy.'],['named-units']),
  q('a3-5-03','A3.5','KC','Which quantity is measured in watts?',
    ['power','force','frequency','pressure'],0,
    'The watt is the SI unit of power.',
    ['','Force is measured in newtons.','Frequency is measured in hertz.','Pressure is measured in pascals.'],['named-units']),

  // A3.6 Index notation
  q('a3-6-01','A3.6','KC','The unit metres per second squared is written in index notation as',
    ['m s²','m s⁻²','m⁻¹ s²','m² s⁻¹'],1,
    'Division by s² is written as multiplication by s⁻².',
    ['This means metres times seconds squared.','','This inverts the metre instead.','This has the wrong powers.'],['index-notation']),
  q('a3-6-02','A3.6','KC','Which expression is equivalent to kg/m³?',
    ['kg m³','kg m⁻³','kg⁻¹ m³','kg³ m⁻¹'],1,
    'A denominator m³ becomes m⁻³ in index notation.',
    ['The sign of the exponent is wrong.','','This takes the reciprocal of the mass.','The exponents do not follow from kg/m³.'],['index-notation']),
  q('a3-6-03','A3.6','UK','N/m² is correctly written using index notation as',
    ['N m²','N m⁻²','N⁻¹ m²','N² m⁻¹'],1,
    'Dividing by m² gives the exponent −2.',
    ['This multiplies by area.','','This inverts newtons as well.','The exponents are incorrect.'],['index-notation','pressure']),

  // A3.7 Turning effect situations
  q('a3-7-01','A3.7','UK','A door is easiest to open when the force is applied',
    ['close to the hinge and parallel to the door','far from the hinge and as nearly perpendicular to the door as possible','at the hinge','far from the hinge but directed along the door toward the hinge'],1,
    'A large perpendicular distance from the hinge to the force line of action gives a larger moment.',
    ['Close to the hinge gives a small moment.','','At the pivot the moment is zero.','A force directed toward the hinge has little or no perpendicular lever arm.'],['turning-effect']),
  q('a3-7-02','A3.7','KC','Which situation mainly involves a turning effect about a pivot?',
    ['Pulling a suitcase straight across the floor','Opening a bottle with a bottle opener','Compressing a block equally from opposite sides','Lifting a book vertically at constant speed'],1,
    'A bottle opener turns about a contact point and acts as a lever.',
    ['This is mainly translational motion.','','Balanced compression is not the intended turning example.','This need not produce rotation.'],['turning-effect','lever']),
  q('a3-7-03','A3.7','UK','The same force is applied perpendicular to two identical spanners. One spanner is twice as long as the other. The longer spanner produces',
    ['half the moment','the same moment','twice the moment','four times the moment'],2,
    'Moment = force × perpendicular distance. Doubling the distance doubles the moment.',
    ['The trend is opposite.','Distance matters.','','Moment depends linearly, not quadratically, on distance.'],['turning-effect','moment']),

  // A3.8 Moment
  q('a3-8-01','A3.8','KC','The moment of a force about a point is',
    ['force × distance moved','force × perpendicular distance from the point to the force\'s line of action','mass × acceleration','force ÷ area'],1,
    'The lever arm is the perpendicular distance from pivot to the line of action.',
    ['That expression is work only when the distance is along the force.','','That is force.','That is pressure.'],['moment','definition']),
  q('a3-8-02','A3.8','UK','A 12 N force acts perpendicular to a handle 0.25 m from its pivot. The moment is',
    ['3.0 N m','48 N m','12.25 N m','0.0208 N m'],0,
    'T = Fd = 12 × 0.25 = 3.0 N m.',
    ['','This divides force by distance.','This adds unlike quantities.','This divides distance by force.'],['moment','calculation']),
  q('a3-8-03','A3.8','KC','Which is the correct unit to state for the moment of a force?',
    ['J','N m','N/m','Pa'],1,
    'The syllabus specifies N m for moment and notes that it is not to be treated as a joule in this context.',
    ['J is used for work and energy, not as the named unit of moment.','','N/m is spring constant.','Pa is pressure.'],['moment','units']),

  // A3.9 Principle of moments
  q('a3-9-01','A3.9','UK','A beam in rotational equilibrium has a 6 N force 0.40 m to the left of a pivot. A force on the right acts 0.30 m from the pivot. Its magnitude is',
    ['4 N','6 N','8 N','12 N'],2,
    '6 × 0.40 = F × 0.30, so F = 8 N.',
    ['This multiplies the wrong ratio.','Equal forces are not required when distances differ.','','This doubles instead of balancing moments.'],['principle-of-moments','calculation']),
  q('a3-9-02','A3.9','KC','For a body in rotational equilibrium about a chosen pivot,',
    ['clockwise moments are greater than anticlockwise moments','sum of clockwise moments equals sum of anticlockwise moments','all forces must act at the pivot','the largest force must have the largest moment'],1,
    'The principle of moments requires the clockwise and anticlockwise totals to balance.',
    ['That would cause rotation.','','Forces may act away from the pivot.','Moment depends on both force and distance.'],['principle-of-moments']),
  q('a3-9-03','A3.9','UK','A uniform metre rule of weight 1.0 N is supported at the 50 cm mark. A 3.0 N load is hung at 20 cm. Where must a 2.0 N load be hung on the other side to balance the rule?',
    ['65 cm','80 cm','95 cm','35 cm'],2,
    'The rule\'s own weight acts through the pivot, so it has zero moment. 3(0.30)=2d gives d=0.45 m, at 95 cm.',
    ['This gives only 0.15 m from the pivot.','This gives 0.30 m from the pivot.','','This is on the same side as the 3 N load.'],['principle-of-moments','metre-rule']),

  // A3.10 Levers
  q('a3-10-01','A3.10','KC','In a first-class lever, the',
    ['load lies between effort and fulcrum','effort lies between load and fulcrum','fulcrum lies between effort and load','effort and load act at the same point'],2,
    'A first-class lever has the fulcrum between the effort and the load.',
    ['That describes a second-class lever.','That describes a third-class lever.','','They act at different locations.'],['levers']),
  q('a3-10-02','A3.10','KC','Which device is a second-class lever?',
    ['wheelbarrow','seesaw','tweezers','scissors'],0,
    'In a wheelbarrow the load lies between the wheel/fulcrum and the effort at the handles.',
    ['','A seesaw is first class.','Tweezers are third class.','Scissors are first class.'],['levers']),
  q('a3-10-03','A3.10','UK','A long crowbar can lift a heavy load with a smaller effort mainly because',
    ['it creates energy','the effort can act at a larger distance from the fulcrum','the load loses mass','the fulcrum removes the load\'s weight'],1,
    'A greater effort arm means a smaller effort can produce the required moment.',
    ['A lever does not create energy.','','Mass is unchanged.','Weight still acts.'],['levers','moment']),

  // A3.11 Centre of gravity
  q('a3-11-01','A3.11','KC','To locate the centre of gravity of an irregular lamina, it should be suspended from at least two points and',
    ['its area measured','a plumbline used to draw a vertical line from each suspension point','its mass halved','a spring attached to its centre'],1,
    'The centre of gravity lies on each vertical plumbline; their intersection locates it.',
    ['Area alone does not locate the centre of gravity.','','Mass does not need to be halved.','The centre is not known beforehand.'],['centre-of-gravity','practical']),
  q('a3-11-02','A3.11','KC','For a uniform rectangular lamina, the centre of gravity is at',
    ['one corner','the midpoint of the longest side only','the geometric centre','the lowest point'],2,
    'For a uniform symmetric lamina the centre of gravity is at the geometric centre.',
    ['A corner is not the balance point.','Both dimensions matter.','','It does not simply move to the lowest point.'],['centre-of-gravity']),
  q('a3-11-03','A3.11','UK','Why does a freely suspended lamina come to rest with its centre of gravity vertically below the point of suspension?',
    ['Its weight then has no turning moment about the suspension point','Its mass becomes zero','Gravity stops acting','The plumbline pushes it into position'],0,
    'When the line of action of weight passes through the suspension point, the moment due to weight is zero.',
    ['','Mass is unchanged.','Gravity continues to act.','The plumbline is an indicator, not the cause.'],['centre-of-gravity','moment']),

  // A3.12 Stability
  q('a3-12-01','A3.12','KC','Which design change generally makes a vehicle more stable?',
    ['raise its centre of gravity and narrow its base','lower its centre of gravity and widen its base','raise its centre of gravity and widen its base only','narrow its base while keeping everything else fixed'],1,
    'A low centre of gravity and wide base make it harder for the line of action of weight to pass outside the base.',
    ['Both changes reduce stability.','','A higher centre of gravity works against stability.','A narrower base reduces the safe tilt angle.'],['stability']),
  q('a3-12-02','A3.12','UK','A tilted block begins to topple when',
    ['its mass decreases','the vertical line through its centre of gravity passes outside its base','its centre of gravity lies exactly at its geometric centre','the normal force becomes larger than its weight'],1,
    'Once the line of action of weight is outside the base, weight produces a moment that turns the block further over.',
    ['Mass need not change.','','Geometric centre alone does not determine toppling.','That is not the toppling criterion.'],['stability','line-of-action']),
  q('a3-12-03','A3.12','UK','The same cuboid is placed first on its broad face and then on its narrow end. It is usually more stable on the broad face because',
    ['its weight becomes smaller','its centre of gravity disappears','its base is wider and the centre of gravity is lower relative to the base','gravity acts upward'],2,
    'The broad orientation widens the support base and normally lowers the centre of gravity, increasing the tilt needed to topple it.',
    ['Weight is essentially unchanged.','Every body has a centre of gravity.','','Gravity acts downward.'],['stability','orientation']),

  // A3.13 Force-extension investigation
  q('a3-13-01','A3.13','KC','In a spring experiment, extension is calculated as',
    ['stretched length + original length','original length − stretched length','stretched length − original length','force ÷ original length'],2,
    'Extension is the increase in length: new length minus original length.',
    ['This adds rather than finds the increase.','This gives a negative value for a stretched spring.','','This is not the definition of extension.'],['hooke-experiment','extension']),
  q('a3-13-02','A3.13','UK','A force-extension graph is a straight line through the origin for the first few readings. This shows that, in that region,',
    ['force is proportional to extension','force is inversely proportional to extension','extension is independent of force','the spring has already exceeded its elastic limit'],0,
    'A straight line through the origin represents direct proportionality.',
    ['','Inverse proportion would not give this graph.','The graph shows extension changes with force.','The proportional region does not by itself indicate the elastic limit was exceeded.'],['hooke-experiment','graph']),
  q('a3-13-03','A3.13','UK','Which procedure best checks whether a spring has been permanently deformed during a force-extension experiment?',
    ['Measure only the largest load','Remove the loads and check whether the spring returns to its original length','Use a heavier spring','Plot mass instead of force'],1,
    'If the spring does not return to its original length after unloading, permanent deformation has occurred.',
    ['One loaded reading cannot show recovery.','','Changing spring changes the system.','Mass may be converted to force, but this does not test recovery.'],['hooke-experiment','elastic-limit']),

  // A3.14 Hooke's law
  q('a3-14-01','A3.14','UK','A spring has spring constant 80 N/m. Within the proportional region, a force of 4.0 N produces an extension of',
    ['0.050 m','20 m','320 m','84 m'],0,
    'x = F/k = 4.0/80 = 0.050 m.',
    ['','This multiplies instead of divides.','This is Fk.','This adds the quantities.'],['hooke-law','calculation']),
  q('a3-14-02','A3.14','UK','A spring extends 6.0 cm under a force of 3.0 N, while still proportional. Its spring constant is',
    ['0.50 N/m','18 N/m','50 N/m','200 N/m'],2,
    '6.0 cm = 0.060 m. k = F/x = 3.0/0.060 = 50 N/m.',
    ['This divides using centimetres without converting correctly.','This multiplies 3 by 6.','','This inverts the ratio.'],['hooke-law','unit-conversion']),
  q('a3-14-03','A3.14','UK','A force-against-extension graph has a straight-line gradient of 120 N/m. What does the gradient represent?',
    ['the spring constant','the mass of the spring','the elastic energy directly','the original length'],0,
    'From F = kx, the gradient of F against x is k.',
    ['','Mass is not the gradient.','Elastic energy is not equal to the gradient.','Original length is not represented by this slope.'],['hooke-law','graph']),
]);

export const A3_FLASHCARDS = Object.freeze(Object.entries(A3_OBJECTIVES).flatMap(([objective, wording]) => {
  const cards = {
    'A3.1': [['What three broad effects can a force have?','It can change the size, shape or motion of a body.'],['Does a force have to change speed to change motion?','No. Changing direction changes velocity and therefore motion.']],
    'A3.2': [['Which four force types are named in A3.2?','Electric, magnetic, nuclear and gravitational.'],['Which force gives an object its weight?','Gravitational force.']],
    'A3.3': [['State the weight equation.','W = mg.'],['Unit of weight?','newton (N).']],
    'A3.4': [['How is the unit of a derived quantity obtained?','Start from the defining equation and multiply/divide the base units in the same way.'],['Derive the SI unit of density.','kg / m³ = kg m⁻³.']],
    'A3.5': [['What is the special name for kg m s⁻²?','newton (N).'],['Name the SI unit of pressure.','pascal (Pa).']],
    'A3.6': [['Write m/s² in index notation.','m s⁻².'],['Write kg/m³ in index notation.','kg m⁻³.']],
    'A3.7': [['What makes a force produce a larger turning effect?','A larger force and/or a larger perpendicular distance from the pivot to its line of action.'],['Why is a door handle far from the hinge?','To increase the moment for the same applied force.']],
    'A3.8': [['Define moment of a force.','Force multiplied by the perpendicular distance from the pivot to the line of action of the force.'],['Unit of moment?','N m. In this context it is not stated as J.']],
    'A3.9': [['State the principle of moments.','For rotational equilibrium, total clockwise moment equals total anticlockwise moment about the same point.'],['Do oblique-force calculations belong to A3.9?','No. The syllabus excludes oblique forces here.']],
    'A3.10': [['First-class lever arrangement?','Fulcrum between effort and load.'],['Second-class lever arrangement?','Load between fulcrum and effort.']],
    'A3.11': [['How do you find the centre of gravity of an irregular lamina?','Suspend it from two or more points and draw vertical plumb lines; their intersection locates the centre of gravity.'],['Why use at least two suspension points?','One plumb line gives only a line; two lines locate a point.']],
    'A3.12': [['When does a tilted object topple?','When the vertical line of action of its weight passes outside its base.'],['How can stability be increased?','Lower the centre of gravity and/or widen the base.']],
    'A3.13': [['How is spring extension found?','stretched length − original length.'],['What does the straight region through the origin of an F-x graph show?','Force is proportional to extension.']],
    'A3.14': [["State Hooke's law for this course.",'Within the proportional region, force is proportional to extension: F = kx.'],['What is k on a graph of force against extension?','The gradient, in N/m.']],
  };
  return cards[objective].map(([front,back],i)=>({id:`fc-${objective.toLowerCase().replace('.','-')}-${i+1}`,objective,topic:'A3',front,back,syllabusWording:wording}));
}));
