import React, { useEffect, useMemo, useState } from 'react';
import MathText from '../../../practice/MathText';
import MechanicsInteractiveLab from './MechanicsInteractiveLab';
import { SECTION_A_TOPICS, SECTION_A_MCQ_BANK, SECTION_A_FLASHCARDS, sectionAStats } from '../sectionAMechanics.mjs';
import { MECHANICS_INTERACTIVES } from '../interactives/mechanicsInteractiveRegistry.mjs';
import { readPhysicsMechanicsProgress, setPhysicsMechanicsCompletion } from '../physicsMechanicsProgress.mjs';
import './physicsMechanics.css';

function stableShuffle(items, seed=1){let s=(Number(seed)>>>0)||1;const r=()=>((s=(1664525*s+1013904223)>>>0)/4294967296);const out=[...items];for(let i=out.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out;}
function normalizeFormula(f){return {name:f.name||f.label||'',equation:f.equation||'',unit:f.unit||'',condition:f.condition||f.symbols||''}}
function paragraphsForSection(section){if(section.body)return [section.body];if(Array.isArray(section.paragraphs))return section.paragraphs;if(section.content)return [section.content];return[]}
function examplesForSection(section){return section.workedExamples||section.examples||[]}
export function lessonObjectives(topic){const lesson=topic?.lesson||{};const raw=Array.isArray(lesson.objectives)?lesson.objectives:Object.entries(topic?.objectives||{});return raw.map(entry=>{if(Array.isArray(entry))return {id:String(entry[0]||''),text:String(entry[1]||'')};if(entry&&typeof entry==='object')return {id:String(entry.id||''),text:String(entry.text||entry.syllabusWording||'')};return {id:'',text:String(entry||'')}}).filter(item=>item.id&&item.text);}
function topicSummary(topic){return topic.lesson.purpose||topic.lesson.summary||topic.lesson.tagline||''}

function StudyView({topic,progress,setCompleted}){
  const lesson=topic.lesson, formulas=(lesson.formulas||lesson.formulae||[]).map(normalizeFormula), objectives=lessonObjectives(topic), objectiveCards=lesson.objectiveCards||{};
  return <div className="pm-study-grid">
    <div className="pm-panel">
      {lesson.sections.map((section,i)=><section className="pm-section-card" key={section.id||i}>
        <h3>{section.heading}</h3>
        {paragraphsForSection(section).map((p,j)=><MathText as="p" prose key={j}>{p}</MathText>)}
        {examplesForSection(section).map((ex,j)=><div className="pm-worked" key={j}><MathText as="strong" prose>{ex.prompt||ex.question||'Worked example'}</MathText>{Array.isArray(ex.steps)?<ol>{ex.steps.map((s,k)=><li key={k}><MathText prose>{s}</MathText></li>)}</ol>:<MathText as="p" prose>{ex.solution||''}</MathText>}</div>)}
      </section>)}
      <div className="pm-completion"><button type="button" className={progress[`lesson:${topic.id}`]?'done':''} onClick={()=>setCompleted(`lesson:${topic.id}`,!progress[`lesson:${topic.id}`])}>{progress[`lesson:${topic.id}`]?'✓ Lesson marked complete':'Mark lesson complete'}</button><span className="pm-feedback">Completion is study progress only. It is not treated as Physics mastery.</span></div>
    </div>
    <aside className="pm-panel">
      <h3>Formulae</h3>
      <div className="pm-table-wrap" tabIndex="0" aria-label="Formula table, scroll horizontally if needed"><table className="pm-formula-table"><thead><tr><th>Quantity</th><th>Relationship</th><th>Unit / condition</th></tr></thead><tbody>{formulas.map((f,i)=><tr key={i}><td><MathText prose>{f.name}</MathText></td><td className="pm-formula"><MathText prose>{f.equation}</MathText></td><td><MathText prose>{`${f.unit}${f.condition?` · ${f.condition}`:''}`}</MathText></td></tr>)}</tbody></table></div>
      <h3 style={{marginTop:22}}>Syllabus objectives</h3>
      <div className="pm-objective-list">{objectives.map(o=>{const c=objectiveCards[o.id];return <div className="pm-objective" key={o.id}><strong>{o.id}</strong><MathText as="p" prose>{o.text}</MathText>{c&&<><p><b>In short:</b> <MathText prose>{c.inShort}</MathText></p><p><b>Watch out:</b> <MathText prose>{c.watchOut}</MathText></p></>}</div>})}</div>
    </aside>
  </div>;
}
function LabsView({topic,progress,setCompleted,onEvidence}){
  const labs=MECHANICS_INTERACTIVES.filter(i=>i.topic===topic.id);
  return <div className="pm-labs-grid">{labs.map(lab=><div key={lab.id}><MechanicsInteractiveLab interactiveId={lab.id} onEvidence={onEvidence}/><div className="pm-completion"><button type="button" className={progress[`lab:${lab.id}`]?'done':''} onClick={()=>setCompleted(`lab:${lab.id}`,!progress[`lab:${lab.id}`])}>{progress[`lab:${lab.id}`]?'✓ Lab explored':'Mark lab explored'}</button><span className="pm-feedback">Exploration completion does not award a mastery score.</span></div></div>)}</div>;
}
function FlashcardsView({topic}){
  const cards=topic.flashcards;const [index,setIndex]=useState(0),[back,setBack]=useState(false);const c=cards[index%cards.length];
  return <div className="pm-panel pm-flashcard-panel"><div className="pm-challenge-row pm-flashcard-panel-head"><div><strong>{topic.id} · {topic.title}</strong><span>Flashcard {index+1} of {cards.length} · {c.objective}</span></div></div><button type="button" className="pm-flashcard pm-flashcard-polished" onClick={()=>setBack(v=>!v)} aria-label={back?'Show question side':'Reveal answer'}>{back?<><small>ANSWER</small><MathText as="p" prose>{c.back}</MathText></>:<><small>{c.objective}</small><MathText as="h3" prose>{c.front}</MathText><p>Click to reveal</p></>}</button><div className="pm-action-row pm-flashcard-actions"><button type="button" className="pm-btn secondary" onClick={()=>{setIndex(i=>(i-1+cards.length)%cards.length);setBack(false)}}>← Previous</button><button type="button" className="pm-btn" onClick={()=>{setIndex(i=>(i+1)%cards.length);setBack(false)}}>Next card →</button></div></div>;
}
export function PhysicsTopicQuiz({topic,onActivity}){
  const [seed,setSeed]=useState(1),[answers,setAnswers]=useState({}),[submitted,setSubmitted]=useState(false);const questions=useMemo(()=>stableShuffle(topic.mcq,seed).slice(0,10),[topic,seed]);
  const score=submitted?questions.reduce((n,q)=>n+(answers[q.id]===q.answer?1:0),0):0;
  return <div className="pm-quiz"><div className="pm-panel"><strong>{topic.id} topic practice</strong><p style={{color:'var(--pm-muted)',marginBottom:0}}>10 original objective-linked multiple-choice questions. This is topic practice, not a full CXC Paper 01 simulation.</p></div>{questions.map((q,qi)=><article className="pm-question" key={q.id}><h3>{qi+1}. <MathText prose>{q.stem}</MathText></h3>{q.options.map((opt,oi)=>{const selected=answers[q.id]===oi;const cls=submitted?(oi===q.answer?'correct':selected?'wrong':''):'';return <label className={`pm-option ${cls}`} key={oi}><input type="radio" name={q.id} checked={selected} disabled={submitted} onChange={()=>setAnswers(a=>({...a,[q.id]:oi}))}/><span>{String.fromCharCode(65+oi)}. <MathText prose>{opt}</MathText></span></label>})}{submitted&&<div className="pm-explanation"><strong>{answers[q.id]===q.answer?'Correct.':'Review:'}</strong> <MathText prose>{q.explanation}</MathText></div>}</article>)}<div className="pm-panel">{submitted?<><h3 style={{marginTop:0}}>Score: {score}/{questions.length} ({Math.round(score/questions.length*100)}%)</h3><button type="button" className="pm-btn" onClick={()=>{setSeed(s=>s+1);setAnswers({});setSubmitted(false)}}>Build another test</button></>:<button type="button" className="pm-btn" onClick={()=>{const computed=questions.reduce((n,q)=>n+(answers[q.id]===q.answer?1:0),0);setSubmitted(true);onActivity?.({type:'physics_topic_quiz',topic:topic.id,score:computed,maxScore:questions.length,percent:Math.round(computed/questions.length*100)})}} disabled={Object.keys(answers).length===0}>Submit topic test</button>}</div></div>;
}
export function PhysicsMechanicsCheckpoint({onActivity}){
  const [seed,setSeed]=useState(1),[answers,setAnswers]=useState({}),[submitted,setSubmitted]=useState(false);const qs=useMemo(()=>{const quotas={A1:6,A2:3,A3:7,A4:5,A5:7,A6:2};const selected=[];for(const t of SECTION_A_TOPICS)selected.push(...stableShuffle(t.mcq,seed+Number(t.id.slice(1))*97).slice(0,quotas[t.id]));return stableShuffle(selected,seed*31);},[seed]);const score=submitted?qs.filter(q=>answers[q.id]===q.answer).length:0;
  return <div className="pm-quiz"><div className="pm-panel"><strong>Section A Mechanics checkpoint</strong><p style={{color:'var(--pm-muted)',marginBottom:0}}>30 questions across A1-A6. This is an internal SPARK cumulative Mechanics test, not a claim about exact CXC Paper 01 section weighting.</p></div>{qs.map((q,i)=><article className="pm-question" key={q.id}><h3>{i+1}. <span className="pm-chip">{q.topic}</span> <MathText prose>{q.stem}</MathText></h3>{q.options.map((o,oi)=>{const selected=answers[q.id]===oi;const cls=submitted?(oi===q.answer?'correct':selected?'wrong':''):'';return <label className={`pm-option ${cls}`} key={oi}><input type="radio" disabled={submitted} checked={selected} onChange={()=>setAnswers(a=>({...a,[q.id]:oi}))} name={q.id}/><span>{String.fromCharCode(65+oi)}. <MathText prose>{o}</MathText></span></label>})}{submitted&&<div className="pm-explanation"><MathText prose>{q.explanation}</MathText></div>}</article>)}<div className="pm-panel">{submitted?<><h3 style={{marginTop:0}}>Mechanics checkpoint: {score}/30 ({Math.round(score/30*100)}%)</h3><button type="button" className="pm-btn" onClick={()=>{setSeed(s=>s+1);setAnswers({});setSubmitted(false)}}>New checkpoint</button></>:<button type="button" className="pm-btn" onClick={()=>{const s=qs.filter(q=>answers[q.id]===q.answer).length;setSubmitted(true);onActivity?.({type:'physics_mechanics_checkpoint',score:s,maxScore:30,percent:Math.round(s/30*100)})}}>Submit checkpoint</button>}</div></div>;
}

export default function PhysicsMechanicsSection({userId,onBack,onActivity,onEvidence}){
  const [topicId,setTopicId]=useState('A1'),[mode,setMode]=useState('study'),[progress,setProgress]=useState(()=>readPhysicsMechanicsProgress(userId));const topic=SECTION_A_TOPICS.find(t=>t.id===topicId)||SECTION_A_TOPICS[0];const stats=sectionAStats();
  useEffect(()=>{setProgress(readPhysicsMechanicsProgress(userId));},[userId]);
  const setCompleted=(key,value)=>setProgress(p=>{const n=setPhysicsMechanicsCompletion(userId,p,key,value);onActivity?.({type:'physics_completion',subject:'CSEC Physics',section:'A',key,completed:Boolean(value)});return n});
  const topicLabs=MECHANICS_INTERACTIVES.filter(i=>i.topic===topic.id);const completedCount=(progress[`lesson:${topic.id}`]?1:0)+topicLabs.filter(l=>progress[`lab:${l.id}`]).length;const totalCount=1+topicLabs.length;const pct=Math.round(completedCount/totalCount*100);
  return <main className="physics-mechanics"><div className="pm-shell"><header className="pm-hero"><div>{onBack&&<button type="button" className="pm-btn secondary" onClick={onBack} style={{marginBottom:12}}>← Back to Physics</button>}<div className="pm-eyebrow">CSEC Physics · Section A</div><h1>Mechanics</h1><p>Study all 52 Mechanics objectives through audited lessons, interactive labs, flashcards and objective-linked practice.</p></div><div className="pm-hero-stats"><div className="pm-stat"><strong>{stats.objectives}</strong><span>objectives</span></div><div className="pm-stat"><strong>{stats.mcq}</strong><span>MCQs</span></div><div className="pm-stat"><strong>{stats.flashcards}</strong><span>flashcards</span></div><div className="pm-stat"><strong>{MECHANICS_INTERACTIVES.length}</strong><span>interactive labs</span></div></div></header>
    <nav className="pm-topics" aria-label="Mechanics topics">{SECTION_A_TOPICS.map(t=><button key={t.id} type="button" aria-pressed={topic.id===t.id} className={`pm-topic-btn ${topic.id===t.id?'active':''}`} onClick={()=>{setTopicId(t.id);setMode('study')}}>{t.id} · {t.title}</button>)}</nav>
    <div className="pm-topic-head"><div><h2>{topic.id}. {topic.title}</h2><MathText as="p" prose>{topicSummary(topic)}</MathText></div><div className="pm-topic-progress"><strong>{pct}% explored</strong><div className="pm-progress-track"><i style={{width:`${pct}%`}}></i></div><span>{completedCount}/{totalCount} study activities marked complete</span></div></div>
    <nav className="pm-modebar" aria-label="Physics learning mode"><button type="button" aria-pressed={mode==='study'} className={`pm-mode-btn ${mode==='study'?'active':''}`} onClick={()=>setMode('study')}>Study</button><button type="button" aria-pressed={mode==='labs'} className={`pm-mode-btn ${mode==='labs'?'active':''}`} onClick={()=>setMode('labs')}>Interactive labs</button><button type="button" aria-pressed={mode==='flashcards'} className={`pm-mode-btn ${mode==='flashcards'?'active':''}`} onClick={()=>setMode('flashcards')}>Flashcards</button><button type="button" aria-pressed={mode==='quiz'} className={`pm-mode-btn ${mode==='quiz'?'active':''}`} onClick={()=>setMode('quiz')}>Topic test</button><button type="button" aria-pressed={mode==='checkpoint'} className={`pm-mode-btn ${mode==='checkpoint'?'active':''}`} onClick={()=>setMode('checkpoint')}>Mechanics checkpoint</button></nav>
    {mode==='study'&&<StudyView topic={topic} progress={progress} setCompleted={setCompleted}/>} {mode==='labs'&&<LabsView topic={topic} progress={progress} setCompleted={setCompleted} onEvidence={onEvidence}/>} {mode==='flashcards'&&<FlashcardsView key={`fc-${topic.id}`} topic={topic}/>} {mode==='quiz'&&<PhysicsTopicQuiz key={`q-${topic.id}`} topic={topic} onActivity={onActivity}/>} {mode==='checkpoint'&&<PhysicsMechanicsCheckpoint onActivity={onActivity}/>} 
  </div></main>;
}

export { SECTION_A_TOPICS, SECTION_A_MCQ_BANK, SECTION_A_FLASHCARDS };
