import React, { useMemo, useState } from 'react';
import MathText from '../../../practice/MathText';
import { ATOMIC_INTERACTIVES } from '../interactives/eAtomicInteractiveRegistry.mjs';
import { buildScatteringModel, buildAtomModel, buildIsotopeModel, buildRadiationModel, buildDeflectionModel, buildNuclearEquationModel, buildDecayModel, buildHalfLifeModel, buildMassEnergyModel, buildNuclearEnergyBalance } from '../interactives/eAtomicInteractiveModels.mjs';
import './physicsAtomic.css';

function Shell({ meta, note, children }) {
  return <article className="pm-panel atomic-lab"><div className="pm-lab-head"><div><span className="pm-chip">{meta.topic}</span><h3>{meta.title}</h3><MathText as="p" prose>{meta.action}</MathText></div></div>{children}{note && <MathText as="p" prose className="pm-feedback">{note}</MathText>}</article>;
}
function Range({ label, value, setValue, min, max, step=1, unit='' }) { return <label className="pm-control"><span>{label} <strong>{value}{unit}</strong></span><input type="range" min={min} max={max} step={step} value={value} onChange={e=>setValue(Number(e.target.value))}/></label>; }
function Metrics({ items }) { return <div className="pm-metrics">{items.map(([label,value])=><div className="pm-metric" key={label}><strong><MathText prose>{String(value)}</MathText></strong><span>{label}</span></div>)}</div>; }
function Toggle({ values, value, setValue }) { return <div className="atomic-toggle">{values.map(x=><button type="button" key={x} className={value===x?'active':''} onClick={()=>setValue(x)}>{x}</button>)}</div>; }

function Scattering({meta}){const[impact,setImpact]=useState(.75);const r=useMemo(()=>buildScatteringModel({impact}),[impact]);return <Shell meta={meta} note="Most alpha particles pass through because the atom is mostly empty space. Large-angle scattering points to a tiny concentrated positive nucleus."><Range label="Impact parameter" value={impact} setValue={setImpact} min={0} max={1} step={.05}/><Metrics items={[["Model deflection",`${r.deflectionDeg}°`],["Interpretation",r.conclusion]]}/></Shell>}
function Atom({meta}){const[A,setA]=useState(23),[Z,setZ]=useState(11),[charge,setCharge]=useState(0);const r=useMemo(()=>buildAtomModel({A,Z,charge}),[A,Z,charge]);return <Shell meta={meta} note="A = Z + N. A neutral atom has the same number of electrons as protons."><div className="pm-controls-grid"><Range label="Mass number A" value={A} setValue={setA} min={1} max={40}/><Range label="Atomic number Z" value={Z} setValue={setZ} min={1} max={20}/><Range label="Ion charge" value={charge} setValue={setCharge} min={-3} max={3}/></div><div className="atomic-nuclide"><div><strong>{r.protons}</strong><span>protons</span></div><div><strong>{r.neutrons}</strong><span>neutrons</span></div><div><strong>{r.electrons}</strong><span>electrons</span></div></div></Shell>}
function Isotope({meta}){const[Z,setZ]=useState(6),[N,setN]=useState(8);const r=useMemo(()=>buildIsotopeModel({Z,N}),[Z,N]);return <Shell meta={meta} note="Isotopes have the same proton number Z but different neutron numbers and mass numbers."><div className="pm-controls-grid"><Range label="Protons Z" value={Z} setValue={setZ} min={1} max={20}/><Range label="Neutrons N" value={N} setValue={setN} min={0} max={24}/></div><Metrics items={[["Mass number A",r.A],["Atomic number Z",r.Z],["Neutrons",r.N]]}/></Shell>}
function Radiation({meta}){const[type,setType]=useState('alpha');const r=useMemo(()=>buildRadiationModel({type}),[type]);return <Shell meta={meta}><Toggle values={['alpha','beta','gamma']} value={type} setValue={setType}/><div className="atomic-radiation-grid"><div className="pm-metric"><strong>{String(r.charge)}</strong><span>relative charge</span></div><div className="pm-metric"><strong>{String(r.ionising)}</strong><span>ionising ability</span></div><div className="pm-metric"><strong>{String(r.penetrating)}</strong><span>penetration</span></div></div><MathText as="p" prose>{`Typical absorber: ${r.absorber}.`}</MathText></Shell>}
function Deflection({meta}){const[type,setType]=useState('alpha');const r=useMemo(()=>buildDeflectionModel({type}),[type]);return <Shell meta={meta} note="Alpha and beta carry opposite charges. Gamma is uncharged and is not deflected."><Toggle values={['alpha','beta','gamma']} value={type} setValue={setType}/><Metrics items={[["Electric field",r.electric],["Magnetic field",r.magnetic],["Relative deflection",r.relative]]}/></Shell>}
function NuclearEquation({meta}){const[mode,setMode]=useState('alpha'),[A,setA]=useState(226),[Z,setZ]=useState(88);const r=useMemo(()=>buildNuclearEquationModel({mode,A,Z}),[mode,A,Z]);return <Shell meta={meta} note="Check both mass number and atomic number. Alpha: A decreases by 4 and Z by 2. Beta-minus: A is unchanged and Z increases by 1."><Toggle values={['alpha','beta']} value={mode} setValue={setMode}/><div className="pm-controls-grid"><Range label="Parent A" value={A} setValue={setA} min={10} max={240}/><Range label="Parent Z" value={Z} setValue={setZ} min={1} max={100}/></div><Metrics items={[["Daughter A",r.A],["Daughter Z",r.Z],["Decay",mode]]}/></Shell>}
function RandomDecay({meta}){const[initial,setInitial]=useState(600),[throws,setThrows]=useState(8);const r=useMemo(()=>buildDecayModel({initial,throws}),[initial,throws]);const max=Math.max(...r.series,1);return <Shell meta={meta} note="The displayed curve is an expected large-sample trend. A real dice run fluctuates because individual decays are random."><div className="pm-controls-grid"><Range label="Starting population" value={initial} setValue={setInitial} min={60} max={1200} step={60}/><Range label="Number of throws" value={throws} setValue={setThrows} min={2} max={14}/></div><div className="atomic-decay" aria-label="Expected random-decay trend">{r.series.map((n,i)=><i key={i} style={{height:`${Math.max(6,n/max*100)}px`}} title={`Step ${i}: ${n.toFixed(0)}`}/>)}</div><Metrics items={[["Start",r.initial.toFixed(0)],["Expected remaining",r.series[r.series.length-1].toFixed(0)]]}/></Shell>}
function HalfLife({meta}){const[initial,setInitial]=useState(1600),[halfLife,setHalfLife]=useState(2),[elapsed,setElapsed]=useState(6);const r=useMemo(()=>buildHalfLifeModel({initial,elapsed,halfLife}),[initial,elapsed,halfLife]);return <Shell meta={meta} note="After n half-lives, the amount remaining is the original amount divided by 2^n."><div className="pm-controls-grid"><Range label="Initial activity" value={initial} setValue={setInitial} min={100} max={3200} step={100} unit=" Bq"/><Range label="Half-life" value={halfLife} setValue={setHalfLife} min={1} max={12} unit=" h"/><Range label="Elapsed time" value={elapsed} setValue={setElapsed} min={0} max={36} unit=" h"/></div><Metrics items={[["Half-lives elapsed",r.halfLives.toFixed(2)],["Activity remaining",`${r.remaining.toFixed(1)} Bq`]]}/></Shell>}
function MassEnergy({meta}){const[mass,setMass]=useState(2);const r=useMemo(()=>buildMassEnergyModel({massMicrogram:mass}),[mass]);return <Shell meta={meta} note="E = mc^2. The model converts micrograms to kilograms before calculating energy."><Range label="Mass change" value={mass} setValue={setMass} min={.1} max={20} step={.1} unit=" μg"/><Metrics items={[["Mass in kilograms",r.massKg.toExponential(3)],["Energy",`${r.energyJ.toExponential(3)} J`]]}/></Shell>}
function EnergyBalance({meta}){const[benefits,setBenefits]=useState(2),[risks,setRisks]=useState(2);const r=useMemo(()=>buildNuclearEnergyBalance({benefits,risks}),[benefits,risks]);return <Shell meta={meta} note="A strong evaluation names specific benefits and specific risks rather than arguing only one side."><div className="pm-controls-grid"><Range label="Evidence points for" value={benefits} setValue={setBenefits} min={0} max={5}/><Range label="Evidence points against" value={risks} setValue={setRisks} min={0} max={5}/></div><Metrics items={[["Balanced evaluation",r.balanced?'Yes':'Not yet'],["For",r.benefits],["Against",r.risks]]}/></Shell>}

const MAP={'e1-scattering':Scattering,'e2-atom-builder':Atom,'e2-isotope-builder':Isotope,'e3-radiation-properties':Radiation,'e3-field-deflection':Deflection,'e3-nuclear-equations':NuclearEquation,'e3-random-decay':RandomDecay,'e3-half-life':HalfLife,'e3-mass-energy':MassEnergy,'e3-nuclear-energy-balance':EnergyBalance};
export default function AtomicInteractiveLab({interactiveId}){const meta=ATOMIC_INTERACTIVES.find(x=>x.id===interactiveId);if(!meta)return <div className="pm-empty">Interactive not found.</div>;const C=MAP[interactiveId];return C?<C meta={meta}/>:<div className="pm-empty">Interactive not found.</div>}
