// SPARK CSEC Physics Section B lesson candidates.
// Built from the user-supplied complete study notes and CXC 22/G/SYLL 13 objective map.
// Per-objective KC/UK/XS labels from the external draft are intentionally not exposed as official CXC classifications.

export const SECTION_B_THERMAL_LESSONS = Object.freeze([
  {
    "id": "B1",
    "section": "B",
    "title": "Nature of Heat",
    "tagline": "The argument that settled what heat actually is, and why it was won by experiment rather than by reasoning.",
    "summary": "The argument that settled what heat actually is, and why it was won by experiment rather than by reasoning.",
    "whyItMatters": "Builds the evidence-based understanding that thermal energy is energy transfer rather than a material substance, and connects mechanical work with conservation of energy.",
    "objectives": [
      [
        "B1.1",
        "differentiate between the caloric and kinetic theories of heat as they existed in the eighteenth century"
      ],
      [
        "B1.2",
        "discuss the role of Joule’s experiments in establishing the principle of conservation of energy"
      ]
    ],
    "prerequisites": [],
    "formulae": [],
    "sections": [
      {
        "id": "overview",
        "heading": "Topic explained",
        "paragraphs": [
          "In the eighteenth century heat was thought to be a substance. It was called caloric, an invisible weightless fluid that flowed from hot bodies into cold ones. The theory worked well enough: it explained why a hot body cools, why heat flows from hot to cold, and why mixing hot and cold water gives something in between.",
          "It had one fatal problem. If caloric is a substance, there is only so much of it in a body, so you should eventually be able to squeeze it all out. Count Rumford, boring cannon barrels in Munich, noticed that the boring produced heat without limit for as long as the drilling continued, even with a blunt tool that cut almost nothing away. A substance would have run out. Mechanical work would not.",
          "The kinetic theory replaced it: heat is not a substance but energy, carried by the random motion of the particles of a body. Rubbing does work on those particles and speeds them up, which is why friction warms things and why the supply never runs out.",
          "Joule finished the argument by measuring it. He turned a known amount of mechanical work into heat, using falling weights to drive a paddle in water, and showed that a fixed amount of work always produced the same rise in temperature. Work and heat were the same currency, and that is the principle of conservation of energy in its original form."
        ]
      }
    ],
    "objectiveCards": {
      "B1.1": {
        "inShort": "The caloric theory said heat is a weightless fluid that flows from hot bodies to cold ones. The kinetic theory says heat is energy carried by the random motion of particles. Rumford's cannon-boring showed that heat could be produced without limit by doing work, which no finite quantity of fluid could explain.",
        "detail": "Both theories explain everyday cooling equally well, so the argument could only be settled by finding a case where they disagree. Rumford found it. Boring a cannon barrel produced heat continuously for as long as the work continued, and it produced just as much when the borer was blunt and removed almost no metal. If heat were a substance stored in the metal it would have been exhausted, and less cutting would have released less of it. Neither happened. Heat had to be something generated by the work itself, which points to motion rather than substance.",
        "formula": "",
        "howAsked": "'Differentiate between the caloric theory and the kinetic theory of heat' or 'state the evidence against the caloric theory'. Marks are for both descriptions and for naming Rumford's observation, that heat was produced without limit by mechanical work.",
        "watchOut": "Saying the caloric theory was disproved because heat has no weight. Rumford's weighing experiments were suggestive, but the unlimited production of heat by work is the argument the syllabus wants."
      },
      "B1.2": {
        "inShort": "Joule measured how much mechanical work produces a given quantity of heat, using falling weights to turn a paddle in an insulated container of water. He found the ratio is always the same, which showed heat is a form of energy and that energy is conserved when it changes form.",
        "detail": "The apparatus is worth picturing. Weights fall through a measured height, so the work they do is mgh. That work turns a paddle wheel inside water, and the churning raises the water temperature by a measured amount. Repeating with different weights and heights always gave the same amount of work for the same heating. Since mechanical energy disappeared and exactly the equivalent thermal energy appeared, nothing was lost, and the principle of conservation of energy follows.",
        "formula": "",
        "howAsked": "'Discuss the role of Joule's experiments in establishing the principle of conservation of energy.' Marks are for describing the experiment, for the finding that a fixed work gives a fixed heating, and for the conclusion that energy changes form without being destroyed.",
        "watchOut": "Describing the apparatus and stopping. The conclusion, that mechanical energy and thermal energy are interchangeable in a fixed ratio, is where the marks are."
      }
    },
    "practicals": [
      "Rub two blocks together and measure the temperature rise, to show that work produces heat without any hot body being present.",
      "Shake a sealed tube of lead shot repeatedly and measure the temperature rise, a small-scale version of Joule's experiment."
    ],
    "commonMistakes": [
      "Describing caloric as simply wrong without saying what evidence defeated it.",
      "Saying Joule proved heat is motion. What he measured is that a fixed amount of work always gives the same amount of heat."
    ]
  },
  {
    "id": "B2",
    "section": "B",
    "title": "Macroscopic Properties and Phenomena",
    "tagline": "Temperature and how it is measured, the three phases of matter explained by particle motion, thermal expansion, and the gas laws.",
    "summary": "Temperature and how it is measured, the three phases of matter explained by particle motion, thermal expansion, and the gas laws.",
    "whyItMatters": "Connects temperature, thermometry, the particle model, thermal expansion, absolute temperature and the gas laws.",
    "objectives": [
      [
        "B2.1",
        "relate temperature to the direction of net thermal energy transfer"
      ],
      [
        "B2.2",
        "identify physical properties which vary with temperature and may be used as the basis for measuring temperature"
      ],
      [
        "B2.3",
        "relate the use of a thermometer to its design"
      ],
      [
        "B2.4",
        "define the fixed points on the Celsius scale"
      ],
      [
        "B2.5",
        "relate the temperature of a body to the kinetic energy of molecules"
      ],
      [
        "B2.6",
        "distinguish among solids, liquids and gases"
      ],
      [
        "B2.7",
        "use the Kinetic theory to explain the different macroscopic properties of solids, liquids and gases; Expansion"
      ],
      [
        "B2.8",
        "explain observations of the effects of thermal expansion"
      ],
      [
        "B2.9",
        "relate graphs of pressure or volume against temperature to the establishment of the Kelvin temperature scale"
      ],
      [
        "B2.10",
        "use the relationship between the Kelvin and Celsius scales"
      ],
      [
        "B2.11",
        "apply the gas laws"
      ],
      [
        "B2.12",
        "give qualitative explanations of the gas laws in terms of the Kinetic theory"
      ]
    ],
    "prerequisites": [],
    "formulae": [
      {
        "name": "Kelvin and Celsius",
        "equation": "T (in K) = θ (in °C) + 273",
        "symbols": "T is the absolute temperature, θ the Celsius temperature",
        "unit": "kelvin (K)",
        "condition": "Every gas law calculation must use kelvin. Converting is the commonest single mark lost in this topic."
      },
      {
        "name": "Boyle's law",
        "equation": "P₁V₁ = P₂V₂",
        "symbols": "P is pressure, V is volume, at constant temperature",
        "unit": "any consistent units",
        "condition": "Pressure and volume are inversely proportional: squeeze it into half the space and the pressure doubles."
      },
      {
        "name": "Charles' law",
        "equation": "V₁ / T₁ = V₂ / T₂",
        "symbols": "V is volume, T is absolute temperature, at constant pressure",
        "unit": "T in kelvin",
        "condition": "Volume is proportional to absolute temperature."
      },
      {
        "name": "Pressure law",
        "equation": "P₁ / T₁ = P₂ / T₂",
        "symbols": "P is pressure, T is absolute temperature, at constant volume",
        "unit": "T in kelvin",
        "condition": "Also called Gay-Lussac's law. Pressure is proportional to absolute temperature."
      }
    ],
    "sections": [
      {
        "id": "overview",
        "heading": "Topic explained",
        "paragraphs": [
          "Temperature is not the same as thermal energy. Temperature tells you the direction thermal energy will flow: energy always moves from the body at higher temperature to the body at lower temperature, and stops when they are equal. A bath at 40 °C contains far more thermal energy than a cup of tea at 80 °C, but energy still flows from the tea to the bath if they touch.",
          "To measure temperature you need a physical property that changes reliably with it. The length of a liquid column in a thin tube, the electrical resistance of a wire, the pressure of a fixed volume of gas and the voltage across a thermocouple junction all work, and each gives a different type of thermometer suited to a different job.",
          "The Celsius scale is fixed by two agreed points, the temperature of pure melting ice and the temperature of steam above water boiling at normal atmospheric pressure, called the lower and upper fixed points. The interval between them is divided into a hundred equal degrees.",
          "The kinetic theory explains the phases. In a solid the particles are close together in a fixed pattern, held by strong forces, and vibrate about fixed positions. In a liquid they are still close but the forces are weaker, so they can slide past one another. In a gas they are far apart, the forces are negligible, and they move rapidly in all directions. That single picture accounts for the shape and volume of each phase and for why gases can be compressed while solids and liquids cannot.",
          "Heating a body makes its particles move faster and, on average, move slightly further apart, so most substances expand. That expansion has to be designed for: gaps in railway lines, loops in overhead telephone and power lines, rollers under bridges.",
          "Cooling a gas at fixed volume lowers its pressure, and the graph of pressure against temperature is a straight line. Extended backwards, that line reaches zero pressure at about −273 °C, whatever the gas. That is absolute zero, the bottom of the Kelvin scale, and the three gas laws are simplest when temperature is measured from there."
        ]
      }
    ],
    "objectiveCards": {
      "B2.1": {
        "inShort": "Temperature decides the direction of net thermal energy transfer. Energy flows from the body at the higher temperature to the body at the lower temperature, and stops when the two are equal, a state called thermal equilibrium.",
        "detail": "This is what temperature is for. It does not tell you how much thermal energy a body holds, which also depends on its mass and material. It tells you which way energy will move when two bodies are placed in contact. When no net energy flows either way the bodies are at the same temperature and are in thermal equilibrium, which is the condition a thermometer relies on: it is placed in contact with the body until the two reach equilibrium, and then it reads its own temperature.",
        "formula": "",
        "howAsked": "'Relate temperature to the direction of thermal energy transfer' or 'explain what is meant by thermal equilibrium'. The mark for equilibrium requires no net transfer, not simply that the bodies touch.",
        "watchOut": "Saying energy flows from the body with more heat. It flows from the body at the higher temperature, whatever the amounts of energy involved."
      },
      "B2.2": {
        "inShort": "Any property that varies steadily with temperature can measure it: the volume of a liquid, the length of a solid, the electrical resistance of a wire, the pressure of a fixed volume of gas, the voltage generated at a thermocouple junction, and the colour of a very hot body.",
        "detail": "The property has to change by a reasonable amount over the range wanted, and change in one direction only, so that a reading maps onto one temperature. Mercury and coloured alcohol expand in a thin tube, which is the liquid-in-glass thermometer. Platinum resistance rises with temperature and gives high accuracy over a wide range. A thermocouple produces a small voltage at a junction between two metals and responds very quickly, which suits rapidly changing temperatures.",
        "formula": "",
        "howAsked": "'Identify TWO physical properties which vary with temperature and could be used in a thermometer.' Name the property and, if asked, the thermometer that uses it.",
        "watchOut": "Naming a thermometer instead of a property. The question asks what changes, not what the instrument is called."
      },
      "B2.3": {
        "inShort": "The design follows the job. A clinical thermometer has a narrow range around body temperature and a constriction so the reading holds after removal. A laboratory thermometer has a wide range. A thermocouple has a very small junction so it responds quickly and can read a point rather than a region.",
        "detail": "Sensitivity comes from a narrow bore and a large bulb, because a given expansion then pushes the column much further along the tube. Quick response comes from a small bulb with thin walls, so the liquid reaches the temperature of its surroundings fast. Those two pull against each other, which is why a sensitive thermometer is usually slower. Range is set by the choice of liquid and the length of the tube: mercury freezes at −39 °C so alcohol is used for very low temperatures, while alcohol boils at 78 °C so mercury is used for high ones.",
        "formula": "",
        "howAsked": "'Relate the design of the thermometer to its use' or 'state ONE feature of a clinical thermometer and explain its purpose'. Each mark needs a feature and the reason for it.",
        "watchOut": "Listing features with no purpose attached. The constriction is worth a mark only when you say it stops the mercury running back."
      },
      "B2.4": {
        "inShort": "The lower fixed point is the temperature of pure melting ice, taken as 0 °C. The upper fixed point is the temperature of steam above water boiling at normal atmospheric pressure, taken as 100 °C.",
        "detail": "Both definitions carry conditions that are worth marks. The ice must be pure and melting, because dissolved substances lower the melting point. The upper point uses the steam above boiling water rather than the water itself, because the steam is at a more reliable temperature than water that may be superheated, and it must be at normal atmospheric pressure, because the boiling point falls as pressure falls. The interval between the two is divided into 100 equal parts to give the Celsius degree.",
        "formula": "",
        "howAsked": "'Define the lower and upper fixed points on the Celsius scale.' The conditions, pure melting ice and steam at normal atmospheric pressure, are what separate a full answer from a half one.",
        "watchOut": "Writing 'the freezing point of water' and 'the boiling point of water' with no conditions. Both depend on purity and pressure."
      },
      "B2.5": {
        "inShort": "The temperature of a body is a measure of the average kinetic energy of its particles. Heating a body makes its particles move faster, so the average kinetic energy rises and the temperature rises with it.",
        "detail": "The word average matters. At any instant some particles move much faster than others, and temperature reflects the average, not the fastest. This is why two bodies at the same temperature have particles with the same average kinetic energy even if one has far more particles and therefore far more thermal energy in total. It also explains thermal equilibrium: when fast particles of a hot body collide with slow particles of a cold one, energy passes to the slower until the averages match.",
        "formula": "",
        "howAsked": "'Relate the temperature of a body to the kinetic energy of its molecules.' The word average is usually required for the mark.",
        "watchOut": "Saying temperature is the kinetic energy of the molecules. It is a measure of the average kinetic energy."
      },
      "B2.6": {
        "inShort": "In a solid the particles are closely packed in a regular pattern, held by strong forces, and vibrate about fixed positions. In a liquid they are still close but not fixed, so they slide past one another. In a gas they are far apart with negligible forces, moving rapidly in all directions.",
        "detail": "Everything else follows from that. A solid has fixed shape and volume because its particles cannot move past each other. A liquid has fixed volume but takes the shape of its container because its particles can slide but not separate. A gas has neither fixed shape nor volume and fills whatever it is in, because nothing holds its particles together. A gas can be compressed a great deal because most of its volume is empty space; a solid or liquid cannot, because the particles are already touching.",
        "formula": "",
        "howAsked": "'Distinguish among solids, liquids and gases' is often set as a table with rows for arrangement, forces, motion, shape and volume. Fill every row, because each is a separate mark.",
        "watchOut": "Describing shape and volume without the particle arrangement behind them. The syllabus asks for the differences in intermolecular forces and motion as well."
      },
      "B2.7": {
        "inShort": "Use the particle picture to explain the property. A gas exerts pressure because its particles collide with the walls of the container. A liquid takes the shape of its container because its particles can slide past one another. A solid keeps its shape because its particles vibrate about fixed positions.",
        "detail": "Work from the arrangement to the property in every case. Gases diffuse quickly because their particles are far apart and moving fast with nothing in the way. Liquids diffuse slowly because the particles are crowded. Solids expand least on heating because the strong forces resist the increase in separation, and gases expand most because there is almost nothing to resist. A gas can be compressed because the particles have space to move into; a liquid cannot because they are already in contact.",
        "formula": "",
        "howAsked": "'Use the kinetic theory to explain why ...' The mark is for the particle behaviour, not for restating the observation. Say what the particles do, then what that produces.",
        "watchOut": "Answering with the property rather than the explanation. 'A gas is compressible because it can be squeezed' earns nothing."
      },
      "B2.8": {
        "inShort": "Most substances expand when heated because their particles vibrate more strongly and take up more room. Overhead telephone and power lines are hung slack in the day so they do not snap when they contract at night; bridges rest on rollers; a metal lid is loosened by running it under hot water.",
        "detail": "Solids expand least, liquids more, gases most, because the forces holding the particles resist the increase in separation and those forces weaken from solid to gas. The engineering consequences are the examinable part. Railway lines are laid with gaps or welded under tension. Concrete roads have expansion joints. A bimetallic strip uses two metals that expand by different amounts, so the strip bends when heated, which is how a simple thermostat and a fire alarm work.",
        "formula": "",
        "howAsked": "'Explain observations of the effects of thermal expansion' or 'state TWO applications'. An application answer needs the effect and the use, for example the bimetallic strip bends because the two metals expand unequally, and that bending switches a circuit.",
        "watchOut": "Saying the metal 'gets hot and grows'. Say the particles vibrate more and their average separation increases."
      },
      "B2.9": {
        "inShort": "Plot the pressure of a fixed mass of gas at constant volume against temperature in degrees Celsius. The graph is a straight line, and extended backwards it cuts the temperature axis at about −273 °C, where the pressure would be zero. That temperature is absolute zero and is the start of the Kelvin scale.",
        "detail": "For a fixed mass of gas at constant volume, a graph of pressure against Celsius temperature is approximately linear over the measured range. Extending the straight-line trend backwards reaches zero pressure at about -273 °C. The corresponding extrapolation of volume at constant pressure also approaches zero near the same temperature. This limiting temperature defines absolute zero and the zero of the Kelvin scale. Real gases condense before these simple gas-law lines can actually be followed all the way to the intercept, so the intercept is an extrapolation rather than a measurement at zero pressure or zero volume.",
        "formula": "",
        "howAsked": "'Explain how a graph of pressure against temperature leads to the Kelvin scale' or a graph to extend back to the axis. Marks are for the straight line, for extrapolating it, and for identifying the intercept as absolute zero.",
        "watchOut": "Reading the intercept off a graph that has not been extended far enough. Draw the line back to the axis with a ruler."
      },
      "B2.10": {
        "inShort": "Add 273 to a Celsius temperature to get kelvin, subtract 273 to go back. So 27 °C is 300 K and 400 K is 127 °C.",
        "detail": "A change of one kelvin equals a change of one degree Celsius, because the two scales have the same sized degree and differ only in where they start. That means a temperature difference is the same number in either scale, but an actual temperature is not, which is exactly why gas law calculations need the conversion and specific heat capacity calculations do not: a specific heat calculation uses ΔT, a temperature change.",
        "formula": "T (K) = θ (°C) + 273",
        "howAsked": "Convert between Celsius temperature and kelvin when using gas-law relationships. A temperature interval has the same numerical size in kelvin and degrees Celsius, but an absolute temperature used in a gas law must be expressed in kelvin.",
        "watchOut": "Converting a temperature difference. A rise of 20 °C is a rise of 20 K, not 293 K."
      },
      "B2.11": {
        "inShort": "Boyle's law: at constant temperature, P₁V₁ = P₂V₂. Charles' law: at constant pressure, V₁/T₁ = V₂/T₂. Pressure law: at constant volume, P₁/T₁ = P₂/T₂. Temperatures must be in kelvin.",
        "detail": "Read the question for the quantity that is held constant, and that tells you which law to use. Then list what you know as a before and after pair, convert any temperature to kelvin, and substitute. A gas at 2 × 10⁵ Pa occupying 300 cm³ that is compressed to 100 cm³ at the same temperature reaches 2 × 10⁵ × 300 / 100 = 6 × 10⁵ Pa. Volumes may be left in cm³ as long as both are in the same unit, because they appear as a ratio.",
        "formula": "P₁V₁ = P₂V₂;  V₁/T₁ = V₂/T₂;  P₁/T₁ = P₂/T₂",
        "howAsked": "'Calculate the new pressure of the gas.' Marks are for naming or writing the correct law, for the conversion to kelvin, for the substitution and for the answer with a unit.",
        "watchOut": "Leaving temperature in Celsius, which is the single commonest error in Section B. Using Boyle's law when the temperature has changed."
      },
      "B2.12": {
        "inShort": "Gas pressure comes from particles colliding with the walls of the container. Boyle: halve the volume and the same particles hit the walls twice as often, so the pressure doubles. Pressure law: raise the temperature and the particles move faster, hitting harder and more often, so the pressure rises. Charles: raise the temperature at constant pressure and the gas must expand to keep the collision rate down.",
        "detail": "Every explanation has the same two ingredients: how often the particles strike the wall, and how hard. Reducing the volume does not change their speed, only the frequency of collisions, so the pressure rises purely on rate. Raising the temperature increases their speed, which raises both the rate and the force of each impact. Keeping pressure constant while heating therefore requires the volume to grow, spreading the collisions over a larger wall area and a longer travel between impacts.",
        "formula": "",
        "howAsked": "'Use the kinetic theory to explain Boyle's law.' Marks are for the collisions with the walls, for what happens to their frequency or force, and for the resulting change in pressure.",
        "watchOut": "Saying the particles 'get squashed'. Particles do not change size; what changes is how often they hit the walls."
      }
    },
    "practicals": [
      "Watch a liquid column rise in a capillary tube as the bulb is warmed, and mark the two fixed points.",
      "Trap air in a sealed tube and measure its volume as the pressure is changed, to test Boyle's law.",
      "Heat a fixed volume of gas and record the pressure at several temperatures, then extrapolate the graph back to zero pressure.",
      "Heat a metal ball that just passes through a ring, and show that it no longer fits."
    ],
    "commonMistakes": [
      "Substituting Celsius temperatures into a gas law. The answer will be badly wrong every time.",
      "Saying a hot body 'contains more heat'. It has more thermal energy, and temperature is a separate idea.",
      "Explaining gas pressure as the particles 'pushing'. The pressure comes from their collisions with the walls.",
      "Confusing the lower fixed point with the freezing point of any water. It is pure melting ice at normal atmospheric pressure."
    ]
  },
  {
    "id": "B3",
    "section": "B",
    "title": "Thermal Measurements",
    "tagline": "Heat capacity and specific heat capacity, latent heat, and why temperature stops rising during a change of phase.",
    "summary": "Heat capacity and specific heat capacity, latent heat, and why temperature stops rising during a change of phase.",
    "whyItMatters": "Develops heat capacity, specific heat capacity, latent heat and the quantitative treatment of heating and changes of state.",
    "objectives": [
      [
        "B3.1",
        "distinguish between specific heat capacity, ‘c’ and heat capacity ‘C’"
      ],
      [
        "B3.2",
        "apply the relationship EH = mc ΔT"
      ],
      [
        "B3.3",
        "determine the specific heat capacity of metals and liquids"
      ],
      [
        "B3.4",
        "demonstrate that temperature remains constant during a phase change"
      ],
      [
        "B3.5",
        "apply the relationship EH = ml"
      ],
      [
        "B3.6",
        "determine the specific latent heat of vaporisation and of fusion of water"
      ],
      [
        "B3.7",
        "distinguish between evaporation and boiling"
      ]
    ],
    "prerequisites": [],
    "formulae": [
      {
        "name": "Heat capacity",
        "equation": "C = m c",
        "symbols": "C is the heat capacity of the object, m its mass, c the specific heat capacity of the material",
        "unit": "J/K",
        "condition": "Heat capacity belongs to the object; specific heat capacity belongs to the material."
      },
      {
        "name": "Energy to change temperature",
        "equation": "EH = m c ΔT",
        "symbols": "m is mass, c specific heat capacity, ΔT the temperature change",
        "unit": "EH in joules, c in J/kg K",
        "condition": "ΔT is a change, so it is the same number in kelvin as in degrees Celsius."
      },
      {
        "name": "Energy to change phase",
        "equation": "EH = m l",
        "symbols": "m is mass, l the specific latent heat",
        "unit": "EH in joules, l in J/kg",
        "condition": "No temperature term, because the temperature does not change during a phase change."
      },
      {
        "name": "Electrical energy supplied by a heater",
        "equation": "E = P t = V I t",
        "symbols": "P is power, t time, V voltage, I current",
        "unit": "joule (J)",
        "condition": "This is how a heater's energy input is measured in both experiments below."
      }
    ],
    "sections": [
      {
        "id": "overview",
        "heading": "Topic explained",
        "paragraphs": [
          "Different substances need different amounts of energy to warm up. Specific heat capacity is the energy needed to raise the temperature of one kilogram of a substance by one kelvin, and it is a property of the material. Heat capacity is the energy needed to raise the temperature of a particular object by one kelvin, so it depends on the size of that object as well as what it is made of.",
          "Water has an unusually high specific heat capacity, about 4200 J/kg K. That is why the sea warms and cools far more slowly than the land, why water is used as a coolant in car engines, and why coastal places have milder weather than inland ones.",
          "During a change of phase the temperature stops changing even though energy is still going in. Put a thermometer in melting ice and it stays at 0 °C until every piece has melted. The energy is not raising the kinetic energy of the particles; it is doing work to break the forces holding them in place. That energy is the latent heat, which means hidden heat, because it produces no temperature change to reveal itself.",
          "There are two kinds. Specific latent heat of fusion is the energy needed to change one kilogram of a solid into liquid at its melting point. Specific latent heat of vaporisation is the energy to change one kilogram of liquid into vapour at its boiling point, and it is much larger, because the particles must be separated completely rather than merely freed to slide.",
          "Evaporation and boiling both turn liquid into vapour but they are different processes. Evaporation happens at any temperature, only from the surface, and only the fastest particles escape, which is why the liquid left behind cools. Boiling happens at one fixed temperature, throughout the liquid, and needs a continuous supply of energy."
        ]
      }
    ],
    "objectiveCards": {
      "B3.1": {
        "inShort": "Specific heat capacity, c, is the energy needed to raise the temperature of one kilogram of a substance by one kelvin, measured in J/kg K. Heat capacity, C, is the energy needed to raise the temperature of a whole object by one kelvin, measured in J/K. They are related by C = mc.",
        "detail": "The distinction is between a material and a thing. Copper has a specific heat capacity of about 380 J/kg K wherever you find it. A particular copper block of mass 2 kg has a heat capacity of 760 J/K, and a bigger block of the same copper has a bigger heat capacity. So specific heat capacity lets you compare substances, and heat capacity tells you about one object.",
        "formula": "C = m c",
        "howAsked": "'Distinguish between heat capacity and specific heat capacity' and 'define specific heat capacity'. The definition needs one kilogram, one kelvin, and the unit.",
        "watchOut": "Giving the unit of specific heat capacity as J/K. That is heat capacity; the specific quantity is per kilogram as well."
      },
      "B3.2": {
        "inShort": "EH = m c ΔT. To heat 0.5 kg of water, specific heat capacity 4200 J/kg K, from 20 °C to 70 °C: 0.5 × 4200 × 50 = 105 000 J.",
        "detail": "ΔT is the change, not the final temperature, and because a kelvin and a Celsius degree are the same size the change is the same number in either scale. The formula also runs backwards: given the energy supplied and the temperature rise you can find c, which is exactly what the electrical experiment does. When two bodies exchange energy with no losses, the energy lost by the hotter equals the energy gained by the cooler, and setting one mcΔT equal to another is the method of mixtures.",
        "formula": "EH = m c ΔT",
        "howAsked": "'Calculate the thermal energy required to raise the temperature of ...'. Marks are for the substitution with mass in kilograms and for the unit. Questions often supply the heater's power and time instead of the energy, so work out E = Pt first.",
        "watchOut": "Using the final temperature as ΔT. Using grams, which makes the answer a thousand times too small."
      },
      "B3.3": {
        "inShort": "Electrical method: heat a lagged block or a known mass of liquid with an immersion heater of known power for a measured time, record the temperature rise, then c = Pt / (mΔT). Method of mixtures: drop a hot solid of known mass and temperature into cold water and equate the energy the solid loses to the energy the water gains.",
        "detail": "For the electrical method the block is lagged to reduce energy transfer to the surroundings, a little oil is put in the thermometer hole to improve contact, and the temperature is recorded before switching on and again at the end. Losses are the main source of error, and they can be reduced by lagging, by starting below room temperature and finishing the same amount above it, and by stirring a liquid to keep the temperature uniform. For the method of mixtures the assumption is that all the energy lost by the metal is gained by the water and none by the container or the air, which is why the answer usually comes out a little low.",
        "formula": "c = P t / (m ΔT);  method of mixtures: m₁c₁ΔT₁ = m₂c₂ΔT₂",
        "howAsked": "'Describe an experiment to determine the specific heat capacity of a metal.' Marks are for the apparatus, the measurements taken, the calculation, and at least one precaution against energy loss.",
        "watchOut": "Forgetting to state a precaution. Assuming no energy is lost without saying that the assumption is being made."
      },
      "B3.4": {
        "inShort": "Heat crushed ice steadily and record its temperature every half minute. The temperature rises to 0 °C, then stays there while the ice melts even though heating continues, then rises again once all of it is liquid. The flat part of the graph is the change of phase.",
        "detail": "The flat section is the whole point. Energy is still being supplied throughout it, so the energy must be doing something other than raising the kinetic energy of the particles: it is doing work to break the bonds holding them in the solid arrangement. A second flat section appears at 100 °C while the water boils, and it is much longer, because the latent heat of vaporisation is far larger than that of fusion. Plotting temperature against time and identifying the flat regions is a standard question.",
        "formula": "",
        "howAsked": "'Sketch a graph of temperature against time for ice heated steadily until it boils' or 'explain why the temperature remains constant while the ice melts'. The explanation must say the energy is used to break the forces between the particles rather than to raise their kinetic energy.",
        "watchOut": "Saying no energy is being supplied during the flat part. It is; it simply is not raising the temperature."
      },
      "B3.5": {
        "inShort": "EH = m l, where l is the specific latent heat. To melt 0.2 kg of ice, specific latent heat of fusion 340 000 J/kg: 0.2 × 340 000 = 68 000 J. There is no temperature term because the temperature does not change.",
        "detail": "A question often has two stages: warm the substance to its melting or boiling point with mcΔT, then change its phase with ml, and add the two. Watch which stage the numbers belong to. To take 0.1 kg of ice at −10 °C to water at 0 °C you need mcΔT for the ice, using the specific heat capacity of ice, and then ml for the melting.",
        "formula": "EH = m l",
        "howAsked": "'Calculate the energy needed to melt ...' or a two-stage problem combining mcΔT and ml. Marks are for splitting the problem into its stages and for using the right constant in each.",
        "watchOut": "Multiplying by a temperature change as well. Using the latent heat of fusion where vaporisation is meant, or the other way round."
      },
      "B3.6": {
        "inShort": "Use an electrical heater of known power. For fusion, melt ice with the heater and measure the mass of water collected in a measured time, then l = Pt/m. For vaporisation, boil water and measure the mass lost in a measured time, then l = Pt/m. Run a control with the heater off to correct for melting caused by the room.",
        "detail": "The control is the part that earns marks. Ice melts from room warmth as well as from the heater, so a second funnel of ice is set up alongside with no heater, and the mass it produces in the same time is subtracted. For vaporisation the container is placed on a balance so the mass lost can be read directly while boiling continues steadily. In both cases the heater's energy is Pt, or VIt if the voltage and current are measured instead.",
        "formula": "l = P t / m",
        "howAsked": "'Describe an experiment to determine the specific latent heat of fusion of ice.' Marks are for the heater of known power, the timing, the mass collected, the control experiment, and the calculation.",
        "watchOut": "Omitting the control. Starting the timing before the heater has brought the system to a steady state."
      },
      "B3.7": {
        "inShort": "Evaporation occurs at any temperature, only at the surface, and cools the liquid left behind. Boiling occurs only at the boiling point, throughout the liquid with bubbles forming inside it, and needs a continuous supply of energy at a fixed temperature.",
        "detail": "In evaporation the fastest particles at the surface escape, so the average kinetic energy of those remaining falls and the liquid cools. That is why sweat cools the skin, why a wet cloth on a water jar keeps it cool, and why the rate rises with temperature, surface area, and moving air. Boiling is different: bubbles of vapour form throughout the liquid because the vapour pressure inside them can match the pressure above, which only happens at one temperature for a given pressure. Reducing the pressure lowers the boiling point, which is why water boils below 100 °C on a mountain.",
        "formula": "",
        "howAsked": "'Distinguish between evaporation and boiling', usually as a table. Give temperature, where it happens, and whether the liquid cools. 'Explain why evaporation causes cooling' needs the escape of the faster particles and the fall in average kinetic energy.",
        "watchOut": "Saying evaporation happens 'below the boiling point'. It happens at any temperature, including at the boiling point."
      }
    },
    "practicals": [
      "Use an immersion heater of known power in a lagged metal block, record the temperature rise over a measured time, and calculate the specific heat capacity.",
      "Use the method of mixtures: drop a hot metal into cold water and equate the energy lost by the metal to the energy gained by the water.",
      "Melt ice with a heater of known power and measure the mass melted in a measured time to find the specific latent heat of fusion.",
      "Boil water with a heater of known power and measure the mass turned to vapour to find the specific latent heat of vaporisation."
    ],
    "commonMistakes": [
      "Using the final temperature instead of the temperature change in EH = mcΔT.",
      "Including a ΔT term in a phase change calculation. The temperature does not change.",
      "Leaving mass in grams. The specific heat capacity is per kilogram.",
      "Saying evaporation happens only at the boiling point. It happens at any temperature."
    ]
  },
  {
    "id": "B4",
    "section": "B",
    "title": "Transfer of Thermal Energy",
    "tagline": "The three ways thermal energy moves, what each needs to work, and how devices are designed around them.",
    "summary": "The three ways thermal energy moves, what each needs to work, and how devices are designed around them.",
    "whyItMatters": "Explains conduction, convection and radiation, then applies them to insulation, everyday devices and energy-transfer systems.",
    "objectives": [
      [
        "B4.1",
        "explain the transfer of thermal energy by conduction"
      ],
      [
        "B4.2",
        "explain the transfer of thermal energy by convection"
      ],
      [
        "B4.3",
        "explain the transfer of thermal energy by radiation"
      ],
      [
        "B4.4",
        "conduct experiments to investigate the factors on which absorption and emission of radiation depend"
      ],
      [
        "B4.5",
        "recall that good absorbers are good emitters"
      ],
      [
        "B4.6",
        "relate the principles of thermal energy transfer to the design of devices"
      ]
    ],
    "prerequisites": [],
    "formulae": [],
    "sections": [
      {
        "id": "overview",
        "heading": "Topic explained",
        "paragraphs": [
          "Thermal energy moves from hotter to colder places in three ways, and telling them apart is the whole topic.",
          "Conduction passes energy through a material without the material itself moving. Particles at the hot end vibrate more strongly and pass the vibration on to their neighbours. In metals there is a second and much faster route: free electrons carry energy through the metal, which is why metals are far better conductors than anything else. Gases are the worst conductors, because their particles are far apart and rarely collide, and that is why trapped air is the basis of nearly every insulator.",
          "Convection moves energy by moving the material itself, so it happens only in fluids, meaning liquids and gases. Heated fluid expands, becomes less dense, and rises; cooler denser fluid sinks to take its place; and the resulting circulation is a convection current. Land and sea breezes, the draught from a heater, and the circulation in a kettle are all convection.",
          "Radiation needs no material at all. Energy travels as infrared electromagnetic waves, which is how energy reaches us from the Sun across empty space. Dull black surfaces are the best absorbers and the best emitters; shiny silvered surfaces are the worst at both, which is why they make good reflectors and poor radiators.",
          "Real devices are designed around all three at once. A vacuum flask stops conduction and convection with the vacuum, stops radiation with silvered walls, and closes the neck with a stopper to stop convection and evaporation. A solar water heater does the opposite, gathering as much radiation as possible with a black absorbing surface and then using convection to circulate the water."
        ]
      }
    ],
    "objectiveCards": {
      "B4.1": {
        "inShort": "Conduction is the transfer of thermal energy through a material without the material moving. Particles at the hot end vibrate more and pass energy to neighbouring particles by collision. In metals free electrons also carry energy, which makes metals much better conductors. Air is a very poor conductor, which is why trapped air insulates.",
        "detail": "Follow the chain. Heating one end gives those particles more kinetic energy, they collide with their neighbours and share it, and the effect passes along. That is slow, because each particle stays roughly where it is. Metals have electrons that are not attached to any one atom, so they travel through the metal carrying energy directly from hot regions to cold ones, and this is why a metal spoon in hot tea heats along its length in seconds. Insulators such as wool, fibreglass, foam and feathers work by trapping air in small pockets, which conducts poorly and cannot circulate.",
        "formula": "",
        "howAsked": "'Explain the transfer of thermal energy by conduction' and 'explain why a woollen jumper keeps you warm'. The jumper answer must credit the trapped air, not the wool itself.",
        "watchOut": "Saying the heat 'travels through' with no mechanism. Name the vibrating particles and, for a metal, the free electrons."
      },
      "B4.2": {
        "inShort": "Convection is the transfer of thermal energy by the movement of the fluid itself. Heated fluid expands, becomes less dense and rises; cooler denser fluid sinks to replace it, setting up a convection current. It happens in liquids and gases only.",
        "detail": "The sequence to write down is: the fluid is heated, it expands, its density falls, it rises, cooler fluid moves in to take its place, and a circulation forms. Land and sea breezes are the standard example. By day the land warms faster than the sea, air above it rises, and cooler air blows in from the sea as a sea breeze. At night the land cools faster, so the flow reverses and a land breeze blows out to sea. A room heater placed low sets up a convection current that warms the whole room, which is why it is not put near the ceiling.",
        "formula": "",
        "howAsked": "'Explain, in terms of convection, how a sea breeze is produced.' Marks are for the unequal heating, the expansion and fall in density, the rising air, and the cooler air moving in.",
        "watchOut": "Saying hot air rises because it is hot. It rises because it is less dense than the fluid around it."
      },
      "B4.3": {
        "inShort": "Radiation is the transfer of thermal energy as infrared electromagnetic waves. It needs no material medium and travels through a vacuum, which is how energy reaches the Earth from the Sun.",
        "detail": "Radiant energy is part of the electromagnetic spectrum, in the infrared region just beyond visible red. Because it is a wave and not a movement of particles, it can cross empty space, and it travels at the speed of light. Every body emits it, and the hotter the body the more it emits. You feel it as the warmth on your face from a fire even when the air between is cool, which shows it is not conduction or convection carrying it.",
        "formula": "",
        "howAsked": "'Explain the transfer of thermal energy by radiation' or 'state how thermal energy from the Sun reaches the Earth'. The mark requires radiation and the fact that no medium is needed.",
        "watchOut": "Calling it 'heat rays' with no mention of electromagnetic or infrared. Saying it needs air to travel through."
      },
      "B4.4": {
        "inShort": "Compare surfaces at the same temperature. Fill identical cans, one dull black and one shiny silvered, with hot water and record the temperature every minute: the black one cools faster, showing it emits more. To test absorption, place both the same distance from a heater and record which warms faster: the black one does. Texture and colour are the two factors.",
        "detail": "Control everything except the surface: same can size and shape, same volume of water, same starting temperature, same distance from the source, same surroundings. Take readings at fixed intervals and plot both cooling curves on the same axes. A Leslie cube does the same job more neatly, having four faces of different finish that can be compared at one temperature with a radiation detector. The syllabus limits the factors to the texture of the surface, rough or smooth, and its nature, shiny or dull, black or white.",
        "formula": "",
        "howAsked": "This appears as a planning and designing question. Marks are for the hypothesis, the manipulated and controlled variables, the readings to be taken, and how the results would be displayed.",
        "watchOut": "Changing more than one thing at a time, for example comparing a large black can with a small shiny one."
      },
      "B4.5": {
        "inShort": "A surface that is a good absorber of radiation is also a good emitter. Dull black surfaces are best at both; shiny, light-coloured surfaces are poorest at both, and are therefore the best reflectors.",
        "detail": "This is why the same choice of surface appears with opposite intentions. A solar panel is black because it must absorb as much as possible. The cooling fins on the back of a refrigerator are black because they must emit as much as possible. A teapot or a marathon runner's foil blanket is shiny because it must emit as little as possible and reflect what falls on it. Houses in hot countries are painted white to reflect the Sun's radiation rather than absorb it.",
        "formula": "",
        "howAsked": "'Explain why the pipes of a solar water heater are painted black' or 'why is a vacuum flask silvered'. State the rule and then apply it to the device in the question.",
        "watchOut": "Treating absorption and emission as opposites. The same surface is good at both or poor at both."
      },
      "B4.6": {
        "inShort": "A vacuum flask blocks all three: the vacuum stops conduction and convection, the silvered walls reflect radiation, and the stopper stops convection and evaporation through the neck. A solar water heater does the reverse, using a black surface to absorb radiation, glass to trap it, and convection to circulate the water.",
        "detail": "Take each feature and name the transfer it deals with, because that is how the marks are allocated. In the flask, the double wall with a vacuum between removes the material that conduction and convection both need. The two facing surfaces are silvered so that radiation crossing the gap is reflected back. The stopper closes the only remaining path. In the solar heater, a black absorbing plate takes in radiation, a glass cover lets radiation in and reduces convection losses from the surface, the copper pipes conduct energy into the water, and the heated water rises to the storage tank by convection while cooler water flows down to replace it.",
        "formula": "",
        "howAsked": "'Explain how the design of a vacuum flask reduces thermal energy transfer' can be assessed as an extended-response question. One mark per feature and the transfer it prevents, so list every feature.",
        "watchOut": "Naming features without naming the transfer method each one blocks. 'The vacuum keeps it hot' does not earn the mark; 'the vacuum has no particles, so there is no conduction or convection' does."
      }
    },
    "practicals": [
      "Heat rods of copper, iron and glass with wax balls stuck along them and compare how quickly each ball falls.",
      "Drop a crystal of potassium permanganate into a beaker of water and heat one corner, to make the convection current visible.",
      "Place a dull black can and a shiny silvered can of hot water side by side and compare how quickly each cools.",
      "Use a Leslie cube with different surfaces at the same temperature to compare emission."
    ],
    "commonMistakes": [
      "Saying convection happens in solids. The material must be free to move.",
      "Explaining conduction in a metal without mentioning free electrons, which is the reason metals conduct so much better.",
      "Describing a vacuum flask as stopping 'heat' without saying which method each feature blocks.",
      "Saying a black surface absorbs radiation but is not also a good emitter."
    ]
  }
]);
