// CSEC Physics practical companions for the existing interactive models.
// Each blueprint turns a simulation into a full experimental workflow with a student notebook.

const make = config => Object.freeze({
  ...config,
  apparatus: Object.freeze(config.apparatus || []),
  variables: config.variables ? Object.freeze({
    independent: config.variables.independent || '',
    dependent: config.variables.dependent || '',
    controls: Object.freeze(config.variables.controls || []),
  }) : null,
  method: Object.freeze(config.method || []),
  table: config.table ? Object.freeze({
    rows: config.table.rows || 5,
    columns: Object.freeze((config.table.columns || []).map(column => Object.freeze(column))),
  }) : null,
  graph: config.graph ? Object.freeze({ fitMode:'linear', ...config.graph }) : null,
  analysis: Object.freeze(config.analysis || []),
  errors: Object.freeze(config.errors || []),
  accuracy: Object.freeze(config.accuracy || []),
  safety: Object.freeze(config.safety || []),
  followUp: Object.freeze((config.followUp || []).map(item => Object.freeze(item))),
});

export const PHYSICS_PRACTICAL_BLUEPRINTS = Object.freeze({
  'a1-pendulum': make({
    topic:'A1', title:'Simple pendulum investigation', source:'CSEC practical workflow',
    aim:'Investigate how the period of a simple pendulum depends on its length and identify variables that should not affect the period for small oscillations.',
    apparatus:['retort stand and clamp','string','pendulum bob','metre rule','stopwatch','protractor'],
    variables:{independent:'pendulum length, l',dependent:'period, T',controls:['release angle kept small','same bob','same timing method']},
    method:['Measure the length from the pivot to the centre of the bob.','Displace the bob through a small angle and release it without pushing.','Time 20 complete oscillations and calculate T = t/20.','Repeat the timing and average the period.','Change the length and repeat for at least five lengths.','Calculate T² for each length.'],
    table:{rows:6,columns:[{key:'l',label:'l',unit:'m'},{key:'t',label:'time for 20 oscillations',unit:'s'},{key:'T',label:'T',unit:'s'},{key:'T2',label:'T²',unit:'s²'}]},
    graph:{xKey:'l',yKey:'T2',xLabel:'l / m',yLabel:'T² / s²',relationship:'A straight T² against l graph supports T² proportional to l.',gradientMeaning:'Use a large triangle on the best-fit line. State gradient units as s²/m.'},
    analysis:['Compare repeated timings before averaging.','Check whether changing mass alters the period when length is fixed.','Use the graph rather than one reading to judge the relationship.'],
    errors:['Reaction time affects the measured interval when timing starts and stops.','Uncertainty in locating the centre of the bob affects the measured pendulum length.'],
    accuracy:['Time many oscillations to reduce percentage reaction-time uncertainty.','Use a fiducial marker at the equilibrium position.','Keep the release angle small and measure length to the centre of the bob.'],
    safety:['Secure the clamp stand so it cannot topple.','Keep the swinging bob clear of faces and glassware.'],
    followUp:[{q:'Why is timing 20 oscillations better than timing one?',a:'The measured interval is longer, so the same reaction-time error is a smaller percentage of the result.'},{q:'Which graph should be straight for a simple pendulum?',a:'T² against l.'}],
  }),
  'a1-density': make({
    topic:'A1', title:'Density of an irregular solid by displacement', source:'CSEC practical workflow',
    aim:'Determine the density of an irregular solid using mass and displaced-water volume.',
    apparatus:['balance','measuring cylinder','water','thin thread','irregular solid'],
    variables:{independent:'object tested',dependent:'density',controls:['read volumes at eye level','object fully submerged','remove trapped air']},
    method:['Measure the dry mass of the object.','Record the initial water volume.','Lower the object until fully submerged without splashing.','Record the final water volume.','Find object volume from the rise in water level.','Calculate density = mass/volume.'],
    table:{rows:4,columns:[{key:'m',label:'mass',unit:'g'},{key:'vi',label:'initial volume',unit:'cm³'},{key:'vf',label:'final volume',unit:'cm³'},{key:'v',label:'object volume',unit:'cm³'},{key:'rho',label:'density',unit:'g/cm³'}]},
    analysis:['For each run, object volume = final volume - initial volume.','Compare repeated density values and identify any outlier.'],
    errors:['Trapped air increases the apparent displaced volume.','Meniscus and scale-reading uncertainty affect both volume readings.'],
    accuracy:['Read the bottom of the meniscus at eye level.','Use a measuring cylinder with a suitable scale interval.','Remove air bubbles from the object surface.'],
    safety:['Lower dense objects gently to avoid cracking the measuring cylinder.'],
    followUp:[{q:'Why must the object be fully submerged?',a:'The volume rise must equal the entire volume of the object.'},{q:'What happens if an air bubble stays attached?',a:'The measured displaced volume is too large, so the calculated density is too small.'}],
  }),
  'a3-centre-gravity': make({
    topic:'A3', title:'Centre of gravity of an irregular lamina', source:'CSEC practical workflow',
    aim:'Locate the centre of gravity of an irregular flat lamina using vertical plumb lines.',
    apparatus:['irregular card lamina','pin','clamp stand','plumb line','pencil'],
    method:['Make a small suspension hole near the edge.','Suspend the lamina and hang the plumb line from the same point.','When both are at rest, draw the vertical line shown by the plumb line.','Repeat from a second and third suspension point.','Mark the intersection of the lines as the centre of gravity.'],
    table:{rows:3,columns:[{key:'point',label:'suspension point',type:'text'},{key:'observation',label:'plumb-line observation',type:'text'}]},
    analysis:['The centre of gravity lies on every vertical line through the point of suspension.','A third line tests whether the first two lines locate the same region.'],
    errors:['The plumb line may still be swinging when its position is marked.','Thick pencil lines make the intersection a region rather than a single point.'],
    accuracy:['Wait for swinging to stop before drawing each line.','Use a thin line and sharp pencil.','Use suspension points well separated around the lamina.'],
    safety:['Secure the pin and clamp so the lamina cannot fall unexpectedly.'],
    followUp:[{q:'Why must the centre of gravity lie below the suspension point?',a:'At equilibrium the weight acts vertically through the support, so there is no turning moment.'}],
  }),
  'a3-lever': make({
    topic:'A3', title:'Principle of moments', source:'CSEC practical workflow',
    aim:'Test the principle of moments for a metre rule in equilibrium about a pivot.',
    apparatus:['metre rule','knife-edge or pivot','mass hangers','slotted masses','balance if the rule weight must be included'],
    variables:{independent:'force or perpendicular distance on one side of the pivot',dependent:'balancing force or distance on the other side',controls:['same pivot position for a set of readings','rule horizontal at balance']},
    method:['Balance the metre rule on the pivot and record the pivot position.','Hang a known load at a measured distance from the pivot.','Place a second load on the opposite side and adjust its position until the rule is horizontal.','Measure both perpendicular distances from the pivot.','Convert masses to forces and calculate clockwise and anticlockwise moments.','Repeat with different loads or distances and compare the two moments.'],
    table:{rows:6,columns:[{key:'F1',label:'force 1',unit:'N'},{key:'d1',label:'distance 1',unit:'m'},{key:'M1',label:'moment 1',unit:'N m'},{key:'F2',label:'force 2',unit:'N'},{key:'d2',label:'distance 2',unit:'m'},{key:'M2',label:'moment 2',unit:'N m'}]},
    analysis:['For equilibrium, compare the total clockwise moment with the total anticlockwise moment about the same pivot.','If the metre rule weight acts away from the pivot, include its moment.'],
    errors:['Friction at the pivot can support a small unbalanced moment.','Distance readings are uncertain if the line of action of a hanger is not directly above the scale mark.'],
    accuracy:['Use a sharp, low-friction pivot.','Measure each distance from the pivot to the line of action of the force.','Wait until the rule is horizontal and at rest before reading positions.'],
    safety:['Keep masses over the bench and away from feet.'],
    followUp:[{q:'State the principle of moments for a body in equilibrium.',a:'The total clockwise moment about a point equals the total anticlockwise moment about the same point.'},{q:'Why must distances be measured from the pivot to the line of action of each force?',a:'Moment depends on the perpendicular distance from the pivot to the force line.'}],
  }),
  'a3-spring': make({
    topic:'A3', title:'Force-extension and Hooke law', source:'Phase 3 audit blueprint',
    aim:'Investigate the relationship between applied force and spring extension and determine the spring constant in the proportional region.',
    apparatus:['spring','clamp stand','metre rule','pointer','mass hanger','slotted masses'],
    variables:{independent:'applied force, F',dependent:'extension, x',controls:['same spring','same zero reference','loads added gently']},
    method:['Measure the unloaded spring length.','Add masses in equal steps and allow the spring to come to rest.','Record the loaded length and calculate extension.','Convert each added mass to force using F = mg.','Continue only within the safe load of the spring.','Plot force vertically against extension horizontally.'],
    table:{rows:6,columns:[{key:'m',label:'mass',unit:'kg'},{key:'F',label:'force',unit:'N'},{key:'L',label:'length',unit:'m'},{key:'x',label:'extension',unit:'m'}]},
    graph:{xKey:'x',yKey:'F',xLabel:'extension, x / m',yLabel:'force, F / N',relationship:'A straight line through the origin indicates F proportional to x in the Hooke-law region.',gradientMeaning:'For F against x, gradient = spring constant k in N/m.'},
    analysis:['Identify the straight-line region before calculating k.','Do not assume data beyond the proportional region obey Hooke law.'],
    errors:['Parallax in the length reading changes the calculated extension.','Residual oscillation makes the loaded length difficult to read consistently.'],
    accuracy:['Read the ruler at eye level.','Keep the ruler close to the spring and use a pointer.','Add masses gently and wait for oscillations to stop.'],
    safety:['Do not exceed the safe load.','Keep feet clear of falling masses.'],
    followUp:[{q:'What does the gradient represent when F is plotted against x?',a:'The spring constant, k.'},{q:'What is the limit of proportionality?',a:'The point beyond which force and extension are no longer proportional.'}],
  }),
  'a4-motion': make({
    topic:'A4', title:'Motion graph investigation', source:'CSEC practical workflow',
    aim:'Use position or velocity data to identify uniform motion and uniform acceleration from graphs.',
    apparatus:['trolley or dynamics cart','track','timing system or ticker timer','metre rule'],
    variables:{independent:'time',dependent:'position or velocity',controls:['same trolley','same track setting for each run']},
    method:['Set up the trolley and timing system.','Record position at equal time intervals or obtain velocity readings.','Repeat any doubtful run.','Plot the requested graph using labelled axes and units.','Use a large triangle to determine a gradient where required.'],
    table:{rows:6,columns:[{key:'t',label:'time',unit:'s'},{key:'s',label:'displacement',unit:'m'},{key:'v',label:'velocity',unit:'m/s'}]},
    graph:{xKey:'t',yKey:'v',xLabel:'time / s',yLabel:'velocity / (m/s)',relationship:'The gradient of a velocity-time graph is acceleration. The area under the graph is displacement.',gradientMeaning:'gradient = Δv/Δt in m/s²'},
    analysis:['Use graph shape before calculating values.','Distinguish signed displacement from total distance if velocity becomes negative.'],
    errors:['Timing resolution and position-reading uncertainty produce scatter in calculated velocities.','Friction or a non-level track may change the motion during a run.'],
    accuracy:['Use evenly spaced time data.','Avoid parallax in metre-rule readings.','Use a best-fit line for noisy experimental data.'],
    safety:['Keep the trolley from running off the bench.'],
    followUp:[{q:'What does a horizontal line on a velocity-time graph mean?',a:'Constant velocity and zero acceleration.'}],
  }),
  'a5-power': make({
    topic:'A5', title:'Human power on stairs', source:'CSEC practical workflow',
    aim:'Estimate useful mechanical power while a person climbs a measured vertical height.',
    apparatus:['balance','stopwatch','metre rule or known stair dimensions','safe staircase'],
    method:['Measure the student mass.','Measure the total vertical height climbed, not the distance along the stairs.','Time the climb over the same height for repeated trials.','Calculate gain in gravitational potential energy mgh.','Calculate power = mgh/t.'],
    table:{rows:4,columns:[{key:'m',label:'mass',unit:'kg'},{key:'h',label:'vertical height',unit:'m'},{key:'t',label:'time',unit:'s'},{key:'P',label:'power',unit:'W'}]},
    analysis:['Compare repeat times and use an average if the effort is similar.','State that the calculation estimates useful mechanical power, not total metabolic power.'],
    errors:['Reaction time affects the measured climbing time.','Uncertainty in the total vertical height changes the calculated gain in gravitational potential energy.'],
    accuracy:['Measure vertical height carefully.','Start and stop timing at clearly defined points.'],
    safety:['Use a dry, clear staircase and avoid running if conditions are unsafe.'],
    followUp:[{q:'Why is vertical height used rather than stair-path length?',a:'The gain in gravitational potential energy depends on vertical height, mgh.'}],
  }),
  'a6-buoyancy': make({
    topic:'A6', title:'Archimedes principle and upthrust', source:'CSEC practical workflow',
    aim:'Compare the upthrust on an immersed object with the weight of the liquid displaced.',
    apparatus:['spring balance','solid object','Eureka can or overflow vessel','water','collecting beaker','balance or measuring cylinder'],
    variables:{independent:'object or immersed volume',dependent:'upthrust and displaced-liquid weight',controls:['same liquid','object fully immersed for each full-immersion trial','object not touching the container']},
    method:['Measure the weight of the object in air with the spring balance.','Fill the overflow vessel until excess water has stopped dripping.','Lower the object fully into the water without allowing it to touch the vessel.','Record the apparent weight while immersed and collect all displaced water.','Calculate upthrust = weight in air - apparent weight.','Determine the mass or volume of displaced water and calculate its weight.','Compare the upthrust with the weight of the displaced water.'],
    table:{rows:5,columns:[{key:'Wair',label:'weight in air',unit:'N'},{key:'Wwater',label:'apparent weight',unit:'N'},{key:'U',label:'upthrust',unit:'N'},{key:'md',label:'displaced-water mass',unit:'kg'},{key:'Wd',label:'displaced-water weight',unit:'N'}]},
    analysis:['Archimedes principle predicts that upthrust equals the weight of liquid displaced.','Compare the two values using measurement uncertainty rather than expecting exact equality.'],
    errors:['Water lost before collection makes the measured displaced-water weight too small.','Air bubbles on the object increase the displaced volume and affect the comparison.'],
    accuracy:['Allow the overflow level to settle before immersion.','Collect all overflow water.','Keep the object fully immersed and clear of the vessel sides and bottom.','Zero the spring balance before use.'],
    safety:['Wipe up spilled water promptly and keep water away from electrical equipment.'],
    followUp:[{q:'State Archimedes principle.',a:'The upthrust on an immersed body equals the weight of fluid displaced.'},{q:'What happens to the spring-balance reading when the object is immersed?',a:'It decreases because the liquid exerts an upward force on the object.'}],
  }),
  'a6-depth': make({
    topic:'A6', title:'Liquid pressure against depth', source:'CSEC practical workflow',
    aim:'Investigate how liquid pressure changes with depth for one liquid.',
    apparatus:['water column or tank','pressure sensor/manometer','metre rule'],
    variables:{independent:'depth below liquid surface',dependent:'gauge pressure',controls:['same liquid','same sensor calibration','same reference surface']},
    method:['Set the pressure sensor at a measured depth.','Record the gauge pressure.','Increase depth in regular steps.','Repeat readings if the sensor fluctuates.','Plot pressure against depth.'],
    table:{rows:6,columns:[{key:'h',label:'depth',unit:'m'},{key:'p',label:'gauge pressure',unit:'kPa'}]},
    graph:{xKey:'h',yKey:'p',xLabel:'depth / m',yLabel:'gauge pressure / kPa',relationship:'For a liquid of constant density, pressure is proportional to depth.',gradientMeaning:'Gradient is proportional to ρg. A denser liquid gives a steeper line.'},
    errors:['A zero or calibration error in the pressure sensor shifts all pressure readings.','Uncertainty in the sensor depth affects the pressure-depth graph.'],
    accuracy:['Measure depth vertically from the free surface to the sensor.','Zero the pressure sensor before taking readings.'],
    safety:['Keep electrical sensors and leads dry where required.'],
    followUp:[{q:'Does pressure at a given depth depend on container shape?',a:'No. For a given liquid, it depends on depth, density and g.'}],
  }),
  'b1-joule-work-heat': make({
    topic:'B1', title:'Mechanical work and heating', source:'CSEC practical workflow',
    aim:'Relate measured mechanical work to a rise in thermal energy and evaluate energy losses.',
    apparatus:['falling masses or mechanical stirrer','insulated water container','thermometer','balance','metre rule'],
    method:['Measure the moving mass and fall distance.','Record the water mass and initial temperature.','Allow the mass to fall and transfer work to the water through stirring.','Record the final temperature after a known number of drops.','Calculate mechanical work and compare with mcΔT.'],
    table:{rows:5,columns:[{key:'m',label:'falling mass',unit:'kg'},{key:'h',label:'total fall distance',unit:'m'},{key:'W',label:'mechanical work',unit:'J'},{key:'dT',label:'temperature rise',unit:'K'}]},
    graph:{xKey:'W',yKey:'dT',xLabel:'mechanical work / J',yLabel:'temperature rise / K',relationship:'For the same water mass, temperature rise should increase with mechanical work.',gradientMeaning:'The gradient depends on the heated mass, heat capacity and energy losses.'},
    errors:['Some mechanical work heats the apparatus and surroundings instead of the water.','Temperature reading delay allows additional cooling before the final value is recorded.'],
    accuracy:['Insulate the container.','Stir before reading temperature.','Measure temperature promptly to reduce cooling error.'],
    safety:['Secure falling masses and keep the drop zone clear.'],
    followUp:[{q:'Why is measured thermal energy often less than mechanical work supplied?',a:'Some energy heats the apparatus and surroundings instead of the water.'}],
  }),
  'b2-gas-laws': make({
    topic:'B2', title:'Gas-law data investigation', source:'CSEC practical workflow',
    aim:'Investigate one gas-law relationship while keeping the required third variable approximately constant.',
    apparatus:['trapped gas sample','pressure sensor','syringe or piston','temperature bath where required'],
    variables:{independent:'volume or absolute temperature',dependent:'pressure or volume',controls:['fixed gas mass','required constant variable for the chosen law']},
    method:['Choose Boyle or Charles mode before collecting data.','Change only the selected independent variable in measured steps.','Allow the system to settle before reading the dependent variable.','Record at least five pairs.','Test the relationship using a suitable graph or product/ratio.'],
    table:{rows:6,columns:[{key:'V',label:'volume',unit:'cm³'},{key:'p',label:'pressure',unit:'kPa'},{key:'T',label:'temperature',unit:'K'}]},
    analysis:['For Boyle law at constant temperature, test whether pV is approximately constant.','For Charles law at constant pressure, compare V/T using kelvin.'],
    errors:['Compression or expansion may change the gas temperature before equilibrium is restored.','Small gas leaks or sensor zero errors alter the pressure-volume relationship.'],
    accuracy:['Wait for thermal equilibrium.','Read volume without parallax.','Avoid rapid compression, which changes gas temperature.'],
    safety:['Do not exceed the pressure rating of the syringe or tubing.'],
    followUp:[{q:'Why should compression be slow in a Boyle-law experiment?',a:'Rapid compression heats the gas, so temperature would not remain constant.'}],
  }),
  'b3-specific-heat': make({
    topic:'B3', title:'Specific heat capacity of a metal block', source:'Phase 3 audit blueprint',
    aim:'Determine the specific heat capacity of a metal block by electrical heating.',
    apparatus:['metal block','electric heater','temperature probe','ammeter','voltmeter','power supply','switch','stopwatch','insulation','balance'],
    variables:{independent:'electrical energy supplied',dependent:'temperature rise',controls:['same block','same insulation','good thermal contact']},
    method:['Measure the mass of the block.','Place the heater and temperature probe firmly in the block and insulate it.','Record the initial temperature.','Switch on the heater and record V, I and heating time.','Record the final temperature and calculate ΔT.','Use E = VIt and c = E/(mΔT).'],
    table:{rows:5,columns:[{key:'V',label:'V',unit:'V'},{key:'I',label:'I',unit:'A'},{key:'t',label:'heating time',unit:'s'},{key:'m',label:'mass',unit:'kg'},{key:'Ti',label:'initial temperature',unit:'°C'},{key:'Tf',label:'final temperature',unit:'°C'},{key:'dT',label:'ΔT',unit:'K'},{key:'c',label:'c',unit:'J/(kg K)'}]},
    analysis:['Compare repeat c values.','Explain the direction of error caused by heat loss or by heating the thermometer and heater as well as the block.'],
    errors:['Energy is transferred to the surroundings and to the heater and temperature probe, not only to the block.','Poor thermal contact can make the measured block temperature lag behind the heater temperature.'],
    accuracy:['Insulate the block.','Use thermal paste or close contact in the holes.','Start timing when the heater is switched on.'],
    safety:['The block and heater become hot. Avoid touching them until cooled.'],
    followUp:[{q:'Why may the experimental c differ from the accepted value?',a:'Not all supplied electrical energy heats only the block. Energy also heats the heater, probe and surroundings.'}],
  }),
  'b3-latent-heat': make({
    topic:'B3', title:'Specific latent heat of fusion of ice', source:'Phase 3 audit blueprint',
    aim:'Determine the specific latent heat of fusion of ice using measured electrical energy and mass melted.',
    apparatus:['ice at 0 °C','electric heater','power supply','ammeter','voltmeter','stopwatch','balance or collection vessel'],
    variables:{independent:'heating time or electrical energy',dependent:'mass of ice melted',controls:['ice at melting point','same heater setting','remove surface water before the run']},
    method:['Bring the ice to its melting point and remove surface meltwater.','Measure V and I for the heater.','Heat for a measured time and measure the raw mass melted.','Run or estimate a matching control interval with no electrical heating to measure background melting.','Calculate corrected melted mass = raw melted mass - background melted mass.','Calculate electrical energy E = VIt, then use L = E/m with the corrected mass.'],
    table:{rows:5,columns:[{key:'V',label:'V',unit:'V'},{key:'I',label:'I',unit:'A'},{key:'t',label:'time',unit:'s'},{key:'mRaw',label:'raw mass melted',unit:'kg'},{key:'mBg',label:'background melt',unit:'kg'},{key:'mCorr',label:'corrected mass',unit:'kg'},{key:'L',label:'L',unit:'J/kg'}]},
    graph:{xKey:'t',yKey:'mCorr',xLabel:'heating time / s',yLabel:'corrected mass melted / kg',relationship:'At approximately constant heater power, corrected melted mass should increase with heating time.',gradientMeaning:'Correcting for background melting reduces the effect of heat gained from the surroundings.'},
    errors:['Heat from the surroundings melts some ice even when the heater is off.','Surface water or ice below 0 °C changes the mass and energy balance.'],
    accuracy:['Use ice already at 0 °C.','Dry the ice surface before starting.','Use a control run to estimate melting caused by the surroundings.'],
    safety:['Keep water away from exposed electrical connections.'],
    followUp:[{q:'Why should ice be at 0 °C before the run?',a:'Otherwise some supplied energy warms the ice to its melting point instead of providing latent heat of fusion.'}],
  }),
  'b4-radiation-surfaces': make({
    topic:'B4', title:'Surface finish and thermal radiation', source:'CSEC practical workflow',
    aim:'Compare the rate of cooling or radiation emission from otherwise identical surfaces.',
    apparatus:['identical containers or Leslie cube','hot water','thermometers or infrared sensor','stopwatch','different surface finishes'],
    variables:{independent:'surface finish',dependent:'cooling rate or detector response',controls:['same temperature','same area','same distance','same water volume']},
    method:['Prepare surfaces at the same starting temperature.','Measure temperature or detector response at equal time intervals.','Keep geometry and surroundings the same.','Compare cooling curves or detector readings.'],
    table:{rows:6,columns:[{key:'t',label:'time',unit:'min'},{key:'black',label:'dull black temperature',unit:'°C'},{key:'shiny',label:'shiny surface temperature',unit:'°C'}]},
    graph:{xKey:'t',yKey:'black',xLabel:'time / min',yLabel:'temperature / °C',fitMode:'none',fitGuidance:'Draw a smooth cooling curve. Do not force the plotted points onto a straight line.',relationship:'A stronger emitter cools more quickly under the same conditions.',gradientMeaning:'Compare the rate of temperature fall, not just one final temperature.'},
    errors:['Convection and conduction also remove energy, so the measured cooling is not due to radiation alone.','A difference in starting temperature or exposed area makes the surface comparison unfair.'],
    accuracy:['Start surfaces at the same temperature.','Use equal exposed areas.','Keep detector distance fixed if using a radiation sensor.'],
    safety:['Handle hot water and hot surfaces carefully.'],
    followUp:[{q:'Which surface is normally the best emitter?',a:'A dull black surface.'},{q:'What is the corresponding absorption rule?',a:'Good emitters are also good absorbers.'}],
  }),
  'c1-wave-graphs': make({
    topic:'C1', title:'Wave graph measurement', source:'CSEC data practical workflow',
    aim:'Measure wavelength or period from wave data and use v = fλ to determine wave speed.',
    apparatus:['wave source or simulation','scale or grid','timer where required'],
    method:['Identify whether the horizontal axis is position or time.','Measure several crest spacings or several periods where possible.','Average to reduce reading uncertainty.','Use v = fλ with consistent units.'],
    table:{rows:5,columns:[{key:'f',label:'frequency',unit:'Hz'},{key:'lambda',label:'wavelength',unit:'m'},{key:'v',label:'speed',unit:'m/s'}]},
    graph:{xKey:'lambda',yKey:'v',xLabel:'wavelength / m',yLabel:'speed / (m/s)',relationship:'For waves in one unchanged medium, speed may remain approximately constant while f and λ vary inversely.'},
    errors:['Finite line thickness and graph resolution limit how precisely crest positions or periods can be read.','A changing medium changes wave speed and invalidates comparisons made as if the speed were constant.'],
    accuracy:['Measure across several cycles, then divide by the number of cycles.','Use the axis labels before deciding whether the interval is λ or T.'],
    followUp:[{q:'What is measured crest-to-crest on a displacement-position graph?',a:'Wavelength.'},{q:'What is measured crest-to-crest on a displacement-time graph?',a:'Period.'}],
  }),
  'c2-echo-ranging': make({
    topic:'C2', title:'Speed of sound by echo timing', source:'Phase 3 audit blueprint',
    aim:'Determine the speed of sound in air from a measured distance and echo return time.',
    apparatus:['large reflecting wall','metre tape','stopwatch or audio timing system','sharp sound source'],
    variables:{independent:'distance to reflector',dependent:'echo round-trip time',controls:['same reflecting surface','same timing method']},
    method:['Measure a known distance d from a large reflecting surface.','Produce a sharp sound and measure the echo return time t.','Repeat several times and average.','Use total sound distance = 2d.','Calculate v = 2d/t.'],
    table:{rows:5,columns:[{key:'d',label:'distance to wall',unit:'m'},{key:'t',label:'echo time',unit:'s'},{key:'v',label:'speed',unit:'m/s'}]},
    graph:{xKey:'t',yKey:'d',xLabel:'echo time / s',yLabel:'one-way distance / m',relationship:'One-way distance should be proportional to echo time.',gradientMeaning:'For d against t, gradient is approximately v/2.'},
    errors:['Reaction time affects the measured echo interval.','Background noise or multiple reflections can make the returning echo difficult to identify.'],
    accuracy:['Use a long distance to reduce percentage timing error.','Repeat and average.','Use a hard, flat reflecting surface and avoid strong background noise.'],
    safety:['Choose a safe open area away from traffic.'],
    followUp:[{q:'Why is the sound travel distance 2d?',a:'The pulse travels to the wall and back to the observer.'}],
  }),
  'c4-refraction': make({
    topic:'C4', title:'Refraction and refractive index', source:'CSEC practical workflow',
    aim:'Measure incident and refracted angles and determine refractive index using Snell’s law.',
    apparatus:['ray box or laser ray','glass block','paper','ruler','protractor'],
    variables:{independent:'angle of incidence, i',dependent:'angle of refraction, r',controls:['same material','same wavelength or colour','same face of block']},
    method:['Trace the block and draw a normal at the point of incidence.','Send a narrow ray at a measured angle i.','Mark the ray path and trace the refracted ray.','Measure r from the normal.','Repeat for several incident angles.','Calculate sin i and sin r, then plot sin i against sin r.'],
    table:{rows:6,columns:[{key:'i',label:'i',unit:'°'},{key:'r',label:'r',unit:'°'},{key:'sini',label:'sin i'},{key:'sinr',label:'sin r'}]},
    graph:{xKey:'sinr',yKey:'sini',xLabel:'sin r',yLabel:'sin i',relationship:'For air into one transparent material, sin i is proportional to sin r.',gradientMeaning:'gradient = sin i / sin r = refractive index relative to air.'},
    errors:['A broad ray or thick pencil marks make the ray direction uncertain.','Angle-reading uncertainty increases when the marked points are too close together.'],
    accuracy:['Use a narrow ray.','Mark points far apart on each ray before joining them.','Measure angles from the normal.'],
    safety:['Do not look directly into a laser beam.'],
    followUp:[{q:'Why measure angles from the normal?',a:'The laws of reflection and refraction define incidence and refraction angles relative to the normal.'}],
  }),
  'c4-double-slit': make({
    topic:'C4', title:"Young's double-slit interference", source:'CSEC practical workflow',
    aim:'Investigate the interference pattern produced by two closely spaced slits and determine how fringe spacing depends on wavelength, slit separation and screen distance.',
    apparatus:['low-power monochromatic laser or approved narrow light source','double-slit slide','screen','metre rule','clamps and holders','darkened working area'],
    variables:{independent:'screen distance, L',dependent:'fringe spacing, x',controls:['same wavelength, λ','same slit separation, d','slits and screen kept parallel']},
    method:['Mount the double-slit slide so the light passes through both slits and reaches the screen.','Measure the perpendicular distance L from the slits to the screen.','Identify several consecutive bright fringes near the centre of the pattern.','Measure the total width w across N fringe spacings rather than measuring one small spacing.','Calculate the mean fringe spacing x = w/N.','Repeat for at least five values of L while keeping wavelength and slit separation fixed.','Plot fringe spacing x vertically against screen distance L horizontally.'],
    table:{rows:6,columns:[{key:'L',label:'screen distance, L',unit:'m'},{key:'N',label:'number of fringe spacings'},{key:'w',label:'width across N spacings, w',unit:'mm'},{key:'x',label:'mean fringe spacing, x',unit:'mm'}]},
    graph:{xKey:'L',yKey:'x',xLabel:'screen distance, L / m',yLabel:'fringe spacing, x / mm',relationship:'For fixed wavelength and slit separation, fringe spacing is directly proportional to screen distance.',gradientMeaning:'For x against L, the gradient represents λ/d after units are made consistent.'},
    analysis:['Use x = λL/d to explain the effect of changing wavelength, screen distance or slit separation.','A straight x against L graph supports direct proportionality when λ and d are fixed.','Measure across several fringe spacings to reduce the percentage uncertainty in x.'],
    errors:['The centre of a bright fringe has a finite width, so its exact position is uncertain.','If the screen is not parallel to the slit plane, fringe spacing varies across the pattern.','The stated slit separation has a manufacturing tolerance.'],
    accuracy:['Measure across many fringes and divide by the number of intervals.','Use the central region where fringes are clearest.','Keep the screen square to the beam and measure L perpendicular to the slit plane.','Darken the room enough to make fringe centres easy to locate.'],
    safety:['Use only a low-power classroom laser or approved light source.','Never look into the laser beam or direct it towards another person.','Keep reflective objects out of the beam path and keep the beam below eye level.'],
    followUp:[{q:'Why measure across several fringe spacings instead of one?',a:'The measured distance is larger, so the same ruler uncertainty produces a smaller percentage uncertainty in the calculated fringe spacing.'},{q:'What happens to fringe spacing if slit separation is reduced?',a:'The fringes move farther apart because x = λL/d.'},{q:'What happens to fringe spacing when wavelength increases?',a:'The fringes move farther apart.'}],
  }),
  'c5-focal-length': make({
    topic:'C5', title:'Focal length of a converging lens', source:'CSEC practical workflow',
    aim:'Determine the focal length of a converging lens from measured object and image distances.',
    apparatus:['converging lens and holder','illuminated object','screen','metre rule'],
    variables:{independent:'object distance, u',dependent:'image distance, v',controls:['same lens','measure from optical centre','sharp image criterion']},
    method:['Place the object, lens and screen on one straight line.','Adjust the screen until a sharp real image is formed.','Measure u and v from the lens centre.','Repeat for several object positions.','Calculate f from 1/f = 1/u + 1/v or the relationship specified by the course.','Compare repeated f values.'],
    table:{rows:6,columns:[{key:'u',label:'u',unit:'cm'},{key:'v',label:'v',unit:'cm'},{key:'f',label:'f',unit:'cm'}]},
    graph:{xKey:'u',yKey:'v',xLabel:'object distance, u / cm',yLabel:'image distance, v / cm',fitMode:'none',fitGuidance:'Do not draw a straight best-fit line on u-v axes. Use repeated calculated f values or a linearised graph when the question asks for one.',relationship:'The u-v relationship is not generally a straight line. Use repeated calculated f values or the requested linearised form.'},
    errors:['The sharpest image position is judged by eye and has a range of acceptable screen positions.','The exact optical centre of a thick lens is difficult to locate with a metre rule.'],
    accuracy:['Measure from the optical centre of the lens.','Use a darkened area and a clear object to judge sharp focus.','Repeat at several u values.'],
    safety:['Keep bright lamps cool and stable.'],
    followUp:[{q:'Why must a real image be used with the screen method?',a:'Only real rays actually meet at the image position and form an image on a screen.'}],
  }),
  'd4-ohms-law': make({
    topic:'D4', title:'Potential difference and current', source:'Phase 3 audit blueprint',
    aim:'Investigate the relationship between potential difference across a conductor and current through it, then determine resistance from the graph.',
    apparatus:['DC supply','fixed resistor or resistance wire','ammeter','voltmeter','switch','variable resistor','connecting leads'],
    variables:{independent:'potential difference or current setting',dependent:'current or potential difference',controls:['same conductor','approximately constant conductor temperature']},
    method:['Connect the ammeter in series with the conductor.','Connect the voltmeter in parallel across the conductor.','Use the variable resistor to change current.','For each setting record I and V.','Take enough readings for a reliable graph.','Plot V vertically against I horizontally and draw a best-fit line.'],
    table:{rows:7,columns:[{key:'I',label:'I',unit:'A'},{key:'V',label:'V',unit:'V'},{key:'R',label:'V/I',unit:'Ω'}]},
    graph:{xKey:'I',yKey:'V',xLabel:'current, I / A',yLabel:'potential difference, V / V',relationship:'A straight line through the origin indicates an ohmic conductor with approximately constant resistance.',gradientMeaning:'gradient = ΔV/ΔI = resistance in ohms.'},
    analysis:['Use a large triangle on the best-fit line to calculate gradient.','Discuss heating if the graph bends at high current.'],
    errors:['Heating changes the conductor resistance during the run.','Meter resolution and internal resistance introduce measurement uncertainty.'],
    accuracy:['Open the switch between readings where appropriate.','Check meter zero.','Avoid excessive heating.','Read analogue scales at eye level.'],
    safety:['Use low voltage and switch off before changing connections.'],
    followUp:[{q:'Why is the voltmeter connected in parallel?',a:'It measures potential difference across the conductor and has high resistance so it draws little current.'},{q:'Why is the ammeter connected in series?',a:'The circuit current must pass through it, and its low resistance minimises disturbance.'}],
  }),
  'd6-magnetic-fields': make({
    topic:'D6', title:'Mapping a magnetic field', source:'CSEC practical workflow',
    aim:'Map the direction and shape of the magnetic field around a bar magnet using a plotting compass.',
    apparatus:['bar magnet','plotting compass','paper','pencil'],
    method:['Place the magnet beneath or on a sheet of paper and mark its outline.','Place the compass near one pole and mark the direction of its north-seeking end.','Move the compass so its tail reaches the previous mark and repeat.','Join the marks with a smooth field line and add arrows.','Repeat from several starting positions.'],
    table:{rows:5,columns:[{key:'start',label:'starting region',type:'text'},{key:'direction',label:'observed compass direction',type:'text'}]},
    analysis:['Outside a bar magnet, field-line arrows run from north to south.','Closer field lines represent stronger field regions.'],
    errors:['Nearby magnetic materials or other magnets distort the field being mapped.','The plotting compass has finite size, so its marked direction is only an approximation at one point.'],
    accuracy:['Keep the magnet fixed.','Keep iron objects and other magnets away.','Use a small plotting compass.'],
    safety:['Keep strong magnets away from sensitive electronic devices.'],
    followUp:[{q:'Why must field lines never cross?',a:'The magnetic field at one point has only one direction.'}],
  }),
  'd7-motor-effect': make({
    topic:'D7', title:'Force on a current-carrying conductor', source:'CSEC practical workflow',
    aim:'Demonstrate and investigate the force on a current-carrying conductor in a magnetic field.',
    apparatus:['low-voltage supply','straight conductor','strong magnet','switch','leads'],
    variables:{independent:'current magnitude or direction',dependent:'force direction or relative size',controls:['same conductor length in field','same magnet geometry']},
    method:['Place the conductor perpendicular to the magnetic field.','Switch on briefly and observe the force direction.','Reverse current and record the change.','Return current direction, reverse the magnetic field and record the change.','Increase current where safe and compare force size.'],
    table:{rows:5,columns:[{key:'current',label:'current direction / size',type:'text'},{key:'field',label:'field direction',type:'text'},{key:'force',label:'force observation',type:'text'}]},
    analysis:['Use Fleming’s left-hand rule to predict direction.','A larger current or stronger field should produce a larger force when geometry is unchanged.'],
    errors:['Friction at the supports can reduce the observed motion of the conductor.','The magnetic field may not be uniform over the full active length of the conductor.'],
    accuracy:['Keep the active conductor length and field geometry fixed between comparisons.'],
    safety:['Use low voltage and switch on only briefly to avoid heating.'],
    followUp:[{q:'What happens to the force if current direction reverses?',a:'The force reverses.'},{q:'Name two factors that increase force.',a:'Examples include larger current, stronger magnetic field or greater conductor length in the field.'}],
  }),
  'd7-induction-generator': make({
    topic:'D7', title:'Electromagnetic induction', source:'CSEC practical workflow',
    aim:'Investigate factors that affect the magnitude and direction of induced e.m.f. in a coil.',
    apparatus:['coil','bar magnet','sensitive galvanometer or voltage sensor','connecting leads'],
    variables:{independent:'magnet speed, field strength or number of turns',dependent:'induced e.m.f. or meter deflection',controls:['same motion path when comparing one factor','same coil where required']},
    method:['Connect the coil to a sensitive meter.','Move a magnet into the coil and record deflection.','Move it out and compare direction.','Repeat at different speeds.','Where available, compare a stronger magnet or coil with more turns.'],
    table:{rows:6,columns:[{key:'motion',label:'motion direction',type:'text'},{key:'speed',label:'relative speed'},{key:'emf',label:'peak induced e.m.f.',unit:'mV'}]},
    graph:{xKey:'speed',yKey:'emf',xLabel:'relative speed',yLabel:'peak induced e.m.f. / mV',relationship:'Faster change of magnetic flux linkage gives a larger induced e.m.f.'},
    analysis:['No steady e.m.f. is induced if the magnet and coil are stationary relative to each other.','Reversing relative motion reverses induced-current direction.'],
    errors:['The magnet speed is difficult to reproduce exactly by hand.','Meter response and coil alignment affect the recorded peak deflection.'],
    accuracy:['Use the same travel distance for speed comparisons.','Record peak deflection consistently.'],
    safety:['Keep strong magnets away from devices that may be affected.'],
    followUp:[{q:'Why does faster motion give a larger induced e.m.f.?',a:'The magnetic flux linkage changes more rapidly.'}],
  }),
  'd7-transformer': make({
    topic:'D7', title:'Transformer voltage ratio', source:'CSEC practical workflow',
    aim:'Test the relationship between transformer voltage ratio and turns ratio using a low-voltage alternating supply.',
    apparatus:['low-voltage A.C. supply','laminated iron core','primary coil','secondary coil with selectable turns','two A.C. voltmeters or multimeters','connecting leads'],
    variables:{independent:'number of turns on the secondary coil, Ns',dependent:'secondary voltage, Vs',controls:['same primary turns, Np','same primary voltage, Vp','same core assembly']},
    method:['Assemble the primary and secondary coils on the iron core.','Connect the primary to a low-voltage A.C. supply and measure Vp.','Measure the open-circuit secondary voltage Vs for a known number of secondary turns Ns.','Change Ns while keeping Vp and Np fixed.','Record Vs for at least five values of Ns.','Compare Vs/Vp with Ns/Np and plot Vs against Ns.'],
    table:{rows:6,columns:[{key:'Np',label:'primary turns, Np'},{key:'Ns',label:'secondary turns, Ns'},{key:'Vp',label:'primary voltage, Vp',unit:'V'},{key:'Vs',label:'secondary voltage, Vs',unit:'V'},{key:'turnRatio',label:'Ns/Np'},{key:'voltageRatio',label:'Vs/Vp'}]},
    graph:{xKey:'Ns',yKey:'Vs',xLabel:'secondary turns, Ns',yLabel:'secondary voltage, Vs / V',relationship:'For fixed Vp and Np, Vs is approximately proportional to Ns.',gradientMeaning:'For Vs against Ns, gradient is approximately Vp/Np when losses are small.'},
    analysis:['Compare the measured voltage ratio with the turns ratio for each reading.','Explain small differences using coil resistance, flux leakage and meter uncertainty.'],
    errors:['Not all magnetic flux produced by the primary links the secondary coil.','Coil resistance and meter resolution cause the measured voltage ratio to differ from the ideal value.'],
    accuracy:['Keep the core tightly assembled.','Use the same low primary voltage for every reading.','Record voltages only after the readings are steady.'],
    safety:['Use a low-voltage laboratory A.C. supply only. Do not connect student coils directly to the mains.','Switch off the supply before changing coil connections.'],
    followUp:[{q:'State the ideal transformer voltage relationship.',a:'Vs/Vp = Ns/Np.'},{q:'Why does a transformer require alternating current?',a:'A changing current produces a changing magnetic flux, which induces an e.m.f. in the secondary coil.'}],
  }),
  'e3-random-decay': make({
    topic:'E3', title:'Random decay using repeated trials', source:'CSEC simulation practical workflow',
    aim:'Model random radioactive decay and show how a large sample produces a predictable statistical trend.',
    apparatus:['coin, dice or SPARK random-decay simulation','results table'],
    variables:{independent:'trial number or elapsed interval',dependent:'number remaining undecayed',controls:['same decay rule each interval','same starting population for comparisons']},
    method:['Start with a large number of model nuclei.','Apply one random decay rule to every remaining nucleus.','Remove the nuclei selected as decayed.','Record the number remaining.','Repeat for several intervals and plot number remaining against interval.'],
    table:{rows:8,columns:[{key:'t',label:'interval number'},{key:'N',label:'number remaining'}]},
    graph:{xKey:'t',yKey:'N',xLabel:'interval number',yLabel:'number remaining',fitMode:'none',fitGuidance:'Draw a smooth decreasing curve through the trend. Do not join every point with straight segments.',relationship:'Individual decays are random, but a large sample shows an approximately exponential decrease.'},
    analysis:['Repeat the whole model and compare the exact sequences.','Look for a stable half-life trend even though individual runs differ.'],
    errors:['A finite sample produces random statistical fluctuations from one run to another.','A small starting population makes the relative scatter larger.'],
    accuracy:['Use a large starting sample to reduce relative random fluctuations.','Apply exactly the same decay rule in every interval.'],
    safety:['Use a simulation or safe model. Do not handle radioactive sources without approved laboratory procedures.'],
    followUp:[{q:'Can the exact decay time of one nucleus be predicted?',a:'No. Individual decay is random.'},{q:'What becomes predictable for a large sample?',a:'The statistical rate of decay and half-life.'}],
  }),
  'e3-half-life': make({
    topic:'E3', title:'Half-life from decay data', source:'CSEC data practical workflow',
    aim:'Determine the half-life of a radioactive sample or simulation from activity or count-rate data.',
    apparatus:['approved count-rate data or SPARK half-life simulation','graph paper or graph tool'],
    variables:{independent:'time',dependent:'corrected activity or count rate',controls:['same detector geometry','background treatment kept consistent']},
    method:['Record activity or count rate at equal time intervals.','Subtract background count rate if the data include it.','Plot corrected activity against time.','Choose one activity and find the time to fall to half that value.','Repeat with another pair of half-values and average if appropriate.'],
    table:{rows:7,columns:[{key:'t',label:'time',unit:'min'},{key:'A',label:'measured activity',unit:'Bq'},{key:'Ac',label:'corrected activity',unit:'Bq'}]},
    graph:{xKey:'t',yKey:'Ac',xLabel:'time / min',yLabel:'corrected activity / Bq',fitMode:'none',fitGuidance:'Draw a smooth decay curve. Read half-life from horizontal time intervals between successive halvings.',relationship:'Successive halvings should occur over approximately equal time intervals.',gradientMeaning:'Half-life is read from horizontal time differences, not from the instantaneous gradient.'},
    analysis:['Check more than one halving interval.','Do not force noisy decay data into an exact straight line on ordinary axes.'],
    errors:['Random counting statistics cause the measured count rate to fluctuate.','Background count rate can vary and changes the corrected activity if it is poorly measured.'],
    accuracy:['Use sufficient counts in each interval.','Keep detector-source distance unchanged.','Measure and subtract background where appropriate.'],
    safety:['Use supplied data or a simulation unless supervised procedures for sealed sources are in place.'],
    followUp:[{q:'Why should background count be subtracted?',a:'Background radiation contributes counts that do not come from the source and would distort the decay curve.'}],
  }),
});

export function physicsPracticalForInteractive(interactiveId) {
  return PHYSICS_PRACTICAL_BLUEPRINTS[String(interactiveId || '')] || null;
}

export function physicsPracticalStats() {
  const blueprints = Object.values(PHYSICS_PRACTICAL_BLUEPRINTS);
  return Object.freeze({
    practicals: blueprints.length,
    withGraphs: blueprints.filter(item => item.graph).length,
    topics: new Set(blueprints.map(item => item.topic)).size,
    sections: new Set(blueprints.map(item => item.topic?.[0])).size,
  });
}
