import { criticalAngleDeg, diffractionStrength, doubleSlitPathState, echoDistance, emFrequencyFromWavelength, frequencyFromPeriod, lensFocalLength, lensImageDistance, magnificationFromDistances, refractiveIndexFromAngles, speedInMedium, waveSpeed } from '../cWavesPhysics.mjs';
export function buildWaveLabModel({frequencyHz=5,wavelengthM=.4,type='transverse'}={}){return{frequencyHz,wavelengthM,type,speedMps:waveSpeed({frequencyHz,wavelengthM}),periodS:frequencyFromPeriod(frequencyHz),particleMotion:type==='longitudinal'?'parallel to wave travel':'perpendicular to wave travel'};}
export function buildWaveGraphModel({mode='position',frequencyHz=4,wavelengthM=.5,amplitudeM=.08}={}){return{mode,frequencyHz,wavelengthM,amplitudeM,horizontalQuantity:mode==='position'?'wavelength':'period',horizontalValue:mode==='position'?wavelengthM:1/frequencyHz};}
export function buildEchoLabModel({speedMps=340,timeS=.5}={}){return{speedMps,timeS,totalPathM:speedMps*timeS,distanceM:echoDistance({speedMps,timeS})};}
export function buildPitchLoudnessModel({frequencyHz=440,amplitude=.5}={}){return{frequencyHz,amplitude,pitchLabel:frequencyHz>=880?'high':frequencyHz<=220?'low':'medium',loudnessLabel:amplitude>=.7?'loud':amplitude<=.3?'soft':'moderate'};}
const EM=[['radio',1e2,'transmitting aerial','broadcasting'],['microwave',1e-2,'magnetron','cooking and communication'],['infrared',1e-5,'warm body','remote controls and thermal imaging'],['visible',5.5e-7,'Sun or lamp','vision and optical fibres'],['ultraviolet',2e-7,'Sun or UV lamp','sterilising and security marking'],['X-ray',1e-10,'X-ray tube','radiographs'],['gamma',1e-12,'radioactive nucleus','sterilising and cancer treatment']];
export function buildEMSpectrumModel({index=3}={}){const i=Math.max(0,Math.min(EM.length-1,Math.round(index))),[region,wavelengthM,source,use]=EM[i];return{index:i,region,wavelengthM,frequencyHz:emFrequencyFromWavelength(wavelengthM),source,use,order:EM.map(x=>x[0])};}
export function buildReflectionModel({incidenceDeg=35}={}){const i=Math.max(0,Math.min(90,Number(incidenceDeg)));return{incidenceDeg:i,reflectionDeg:i,fromSurfaceDeg:90-i,imageProperties:['virtual','upright','same size','laterally inverted']};}
export function buildRefractionModel({incidenceDeg=45,refractiveIndex=1.5}={}){const i=Math.max(0.01,Math.min(89,Number(incidenceDeg))),n=Math.max(1,Number(refractiveIndex));const sinr=Math.sin(i*Math.PI/180)/n;const r=Math.asin(Math.min(1,sinr))*180/Math.PI;return{incidenceDeg:i,refractionDeg:r,refractiveIndex:n,speedMps:speedInMedium({refractiveIndex:n}),checkN:refractiveIndexFromAngles({incidenceDeg:i,refractionDeg:r})};}
export function buildTIRModel({refractiveIndex=1.5,incidenceDeg=50}={}){const n=Math.max(1,Number(refractiveIndex)),c=criticalAngleDeg(n),i=Math.max(0,Math.min(89.9,Number(incidenceDeg)));return{refractiveIndex:n,criticalAngleDeg:c,incidenceDeg:i,state:i>c?'total internal reflection':Math.abs(i-c)<.2?'critical ray along boundary':'refracted ray leaves medium'};}
export function buildDoubleSlitModel({wavelengthNm=600,slitSpacingMm=.30,screenDistanceM=2,pathDifferenceWavelengths=0}={}){const wavelengthM=wavelengthNm*1e-9,slitSpacingM=slitSpacingMm*1e-3;return{wavelengthNm,slitSpacingMm,screenDistanceM,fringeSpacingM:wavelengthM*screenDistanceM/slitSpacingM,pathState:doubleSlitPathState({pathDifferenceWavelengths}),diffraction:diffractionStrength({wavelengthM,gapM:slitSpacingM})};}
export function buildLensRayModel({focalLengthCm=10,objectDistanceCm=30}={}){const f=Math.max(.1,Number(focalLengthCm)),u=Math.max(.1,Number(objectDistanceCm));if(u<=f)return{focalLengthCm:f,objectDistanceCm:u,imageType:'virtual',imageDistanceCm:null,magnification:null};const v=lensImageDistance({focalLength:f,objectDistance:u});return{focalLengthCm:f,objectDistanceCm:u,imageType:'real',imageDistanceCm:v,magnification:magnificationFromDistances({imageDistance:v,objectDistance:u})};}
export function buildFocalLengthModel({objectDistanceCm=30,imageDistanceCm=60}={}){const f=lensFocalLength({objectDistance:objectDistanceCm,imageDistance:imageDistanceCm});return{objectDistanceCm,imageDistanceCm,focalLengthCm:f,magnification:magnificationFromDistances({imageDistance:imageDistanceCm,objectDistance:objectDistanceCm})};}
