import { createClient } from "@supabase/supabase-js";

const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

const JSON_HEADERS = { ...CORS_HEADERS, "Content-Type": "application/json" };
const MAX_BASE64_CHARS = 7_000_000;

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), { status, headers: JSON_HEADERS });
}

function serviceKey(): string {
  const legacy = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  if (legacy) return legacy;
  const raw = Deno.env.get("SUPABASE_SECRET_KEYS") || "{}";
  const parsed = JSON.parse(raw) as Record<string, string>;
  const key = parsed.default || Object.values(parsed)[0];
  if (!key) throw new Error("Supabase service key is unavailable.");
  return key;
}

function escapeHtml(value: unknown): string {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function safeList(value: unknown, max = 3): Array<Record<string, unknown>> {
  return Array.isArray(value)
    ? value.slice(0, max).filter(item => item && typeof item === "object") as Array<Record<string, unknown>>
    : [];
}

function metric(value: unknown, available: boolean): string {
  if (!available) return "—";
  const number = Number(value);
  return Number.isFinite(number) ? `${Math.round(number)}%` : "—";
}

function looksLikePdfBase64(value: string): boolean {
  if (!value || value.length > MAX_BASE64_CHARS) return false;
  try {
    // The first bytes of every PDF generated by SPARK begin with %PDF-.
    return atob(value.slice(0, 16)).startsWith("%PDF-");
  } catch {
    return false;
  }
}

function reportHtml(args: {
  parentName: string;
  studentName: string;
  periodLabel: string;
  report: Record<string, unknown>;
}): string {
  const summary = (args.report.summary || {}) as Record<string, unknown>;
  const activity = (args.report.activity || {}) as Record<string, unknown>;
  const strongest = safeList(args.report.strongestSkills);
  const weakest = safeList(args.report.weakestSkills);
  const recommendations = Array.isArray(args.report.recommendations)
    ? (args.report.recommendations as unknown[]).slice(0, 3).map(item => String(item || ""))
    : [];
  const goal = args.report.goal && typeof args.report.goal === "object"
    ? args.report.goal as Record<string, unknown>
    : null;
  const studyCircle = args.report.studyCircle && typeof args.report.studyCircle === "object"
    ? args.report.studyCircle as Record<string, unknown>
    : null;

  const skillRows = (rows: Array<Record<string, unknown>>) => rows.map(row =>
    `<li style="margin:4px 0"><strong>${escapeHtml(row.skill)}</strong> - ${Math.round(Number(row.score ?? row.mastery_score ?? 0))}%</li>`
  ).join("");

  const masteryAvailable = Number(summary.skillCount || 0) > 0;
  const examAvailable = Boolean(activity.hasExamAverage) || Number(activity.examsCompleted || 0) > 0;

  return `<!doctype html>
<html><body style="margin:0;background:#f4f8fb;font-family:Arial,sans-serif;color:#15324b">
  <div style="max-width:640px;margin:0 auto;padding:28px 18px">
    <div style="background:#0f2557;border-radius:16px 16px 0 0;padding:28px;color:#fff">
      <div style="font-weight:800;font-size:22px">SPARK</div>
      <div style="color:#5eead4;font-size:12px;font-weight:800;letter-spacing:.08em;margin-top:4px">STUDENT PROGRESS REPORT</div>
      <h1 style="margin:20px 0 5px;font-size:25px">${escapeHtml(args.studentName)}</h1>
      <div style="color:#d8e4f0">CSEC Mathematics · ${escapeHtml(args.periodLabel)}</div>
    </div>
    <div style="background:#fff;border:1px solid #d7e2ee;border-top:0;border-radius:0 0 16px 16px;padding:26px">
      <p style="margin-top:0">Hi ${escapeHtml(args.parentName || "there")},</p>
      <p>Here is the SPARK progress report you generated for ${escapeHtml(args.studentName)}. The PDF version is attached.</p>
      <div style="background:#e7faf6;border-radius:12px;padding:16px;margin:20px 0">
        <div style="font-size:11px;font-weight:800;color:#087f73;letter-spacing:.06em">SPARK INSIGHT</div>
        <p style="margin:7px 0 0;line-height:1.55">${escapeHtml(summary.insight || "SPARK is building a clearer picture as more learning activity is completed.")}</p>
      </div>
      <table style="width:100%;border-collapse:collapse;margin:18px 0">
        <tr><td style="padding:10px;border:1px solid #e7edf4"><strong>${metric(summary.mastery, masteryAvailable)}</strong><br><span style="color:#6b7c93;font-size:12px">Skill mastery</span></td><td style="padding:10px;border:1px solid #e7edf4"><strong>${metric(activity.examAverage, examAvailable)}</strong><br><span style="color:#6b7c93;font-size:12px">Exam average</span></td></tr>
        <tr><td style="padding:10px;border:1px solid #e7edf4"><strong>${Number(activity.questionsAttempted || 0)}</strong><br><span style="color:#6b7c93;font-size:12px">Questions attempted</span></td><td style="padding:10px;border:1px solid #e7edf4"><strong>${Number(activity.lessonsCompleted || 0)}</strong><br><span style="color:#6b7c93;font-size:12px">Lessons completed</span></td></tr>
      </table>
      ${goal?.target_percent ? `<div style="background:#f7fafc;border:1px solid #e7edf4;border-radius:10px;padding:12px 14px;margin:16px 0"><strong>Learning goal</strong><div style="margin-top:5px;color:#52677a">Target ${Math.round(Number(goal.target_percent))}% in CSEC Mathematics${goal.target_date ? ` by ${escapeHtml(goal.target_date)}` : ""}</div></div>` : ""}
      <div style="font-size:13px;color:#52677a;margin:14px 0"><strong style="color:#15324b">Study Circle:</strong> ${studyCircle?.active ? `Participating${Number(studyCircle.group_size || 0) > 0 ? ` in a ${Math.round(Number(studyCircle.group_size))}-student group` : ""}` : "Not currently active"}</div>
      <div style="display:block;margin:18px 0"><strong>Strongest areas</strong><ul>${skillRows(strongest) || "<li>More mastery data is needed.</li>"}</ul></div>
      <div style="display:block;margin:18px 0"><strong>Areas to improve</strong><ul>${skillRows(weakest) || "<li>No priority areas recorded yet.</li>"}</ul></div>
      <div style="display:block;margin:18px 0"><strong>Recommended next steps</strong><ol>${recommendations.map(item => `<li style="margin:5px 0">${escapeHtml(item)}</li>`).join("")}</ol></div>
      <p style="font-size:12px;color:#6b7c93;line-height:1.5;margin-top:24px">This report summarizes activity recorded in SPARK and is intended to support learning conversations. It should be considered alongside classroom work and teacher or tutor feedback.</p>
    </div>
  </div>
</body></html>`;
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: CORS_HEADERS });
  if (req.method !== "POST") return json({ ok: false, error: "Method not allowed" }, 405);

  let auditId: string | null = null;
  let admin: ReturnType<typeof createClient> | null = null;

  try {
    const authHeader = req.headers.get("Authorization") || "";
    if (!authHeader.toLowerCase().startsWith("bearer ")) return json({ ok: false, error: "Authentication required" }, 401);

    const supabaseUrl = Deno.env.get("SUPABASE_URL");
    const anonKey = Deno.env.get("SUPABASE_ANON_KEY");
    const resendKey = Deno.env.get("RESEND_API_KEY");
    const fromEmail = Deno.env.get("REPORT_FROM_EMAIL");
    if (!supabaseUrl || !anonKey) throw new Error("Supabase environment is incomplete.");
    if (!resendKey || !fromEmail) return json({ ok: false, error: "Progress report email is not configured yet." }, 503);

    const scoped = createClient(supabaseUrl, anonKey, {
      global: { headers: { Authorization: authHeader } },
      auth: { persistSession: false, autoRefreshToken: false },
    });
    const { data: authData, error: authError } = await scoped.auth.getUser();
    const parent = authData?.user;
    if (authError || !parent?.id || !parent.email) return json({ ok: false, error: "Authentication required" }, 401);
    if (!parent.email_confirmed_at) return json({ ok: false, error: "Confirm your Parent account email before emailing progress reports." }, 403);

    const payload = await req.json() as Record<string, unknown>;
    const studentId = String(payload.student_id || "").trim();
    const periodLabel = String(payload.period_label || "Progress report").trim().slice(0, 100) || "Progress report";
    const pdfBase64 = String(payload.pdf_base64 || "");
    const report = payload.report && typeof payload.report === "object" ? payload.report as Record<string, unknown> : {};
    if (!studentId || !pdfBase64) return json({ ok: false, error: "The report data is incomplete." }, 400);
    if (pdfBase64.length > MAX_BASE64_CHARS) return json({ ok: false, error: "The PDF attachment is too large." }, 413);
    if (!looksLikePdfBase64(pdfBase64)) return json({ ok: false, error: "The report attachment is not a valid SPARK PDF." }, 400);

    admin = createClient(supabaseUrl, serviceKey(), { auth: { persistSession: false, autoRefreshToken: false } });
    const [{ data: parentProfile }, { data: link }, { data: studentProfile }] = await Promise.all([
      admin.from("profiles").select("id,name,role").eq("id", parent.id).maybeSingle(),
      admin.from("parent_student_links").select("id,status").eq("parent_id", parent.id).eq("student_id", studentId).eq("status", "approved").maybeSingle(),
      admin.from("profiles").select("id,name,role").eq("id", studentId).maybeSingle(),
    ]);

    if (parentProfile?.role !== "parent") return json({ ok: false, error: "Only Parent accounts can email child progress reports." }, 403);
    if (!link?.id || studentProfile?.role !== "student") return json({ ok: false, error: "You do not have access to this student's report." }, 403);

    const { data: reservation, error: reservationError } = await admin.rpc("spark_begin_progress_report_email", {
      p_parent_id: parent.id,
      p_student_id: studentId,
      p_period_label: periodLabel,
    });
    if (reservationError) {
      const message = String(reservationError.message || "");
      if (message.includes("SPARK_REPORT_RATE_LIMIT_15M")) {
        return json({ ok: false, error: "You've emailed several reports recently. Please wait about 15 minutes before sending another." }, 429);
      }
      if (message.includes("SPARK_REPORT_RATE_LIMIT_24H")) {
        return json({ ok: false, error: "You've reached today's progress-report email limit. You can still download the PDF." }, 429);
      }
      throw reservationError;
    }
    auditId = String(reservation || "") || null;

    const subject = `SPARK progress report - ${studentProfile.name || "Student"}`;
    const resendResponse = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${resendKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: fromEmail,
        to: [parent.email],
        subject,
        html: reportHtml({
          parentName: parentProfile?.name || "Parent",
          studentName: studentProfile?.name || "Student",
          periodLabel,
          report,
        }),
        attachments: [{
          filename: `SPARK_${String(studentProfile?.name || "Student").replace(/[^A-Za-z0-9]+/g, "_")}_Progress_Report.pdf`,
          content: pdfBase64,
        }],
      }),
    });

    const resendBody = await resendResponse.json().catch(() => ({}));
    if (!resendResponse.ok) {
      console.error("Resend progress report failure:", resendBody);
      if (auditId) {
        await admin.from("spark_progress_report_email_log").update({
          status: "failed",
          error_code: `provider_${resendResponse.status}`,
          completed_at: new Date().toISOString(),
        }).eq("id", auditId);
      }
      return json({ ok: false, error: "The email provider could not deliver the report." }, 502);
    }

    if (auditId) {
      await admin.from("spark_progress_report_email_log").update({
        status: "sent",
        provider_message_id: String(resendBody?.id || "") || null,
        completed_at: new Date().toISOString(),
      }).eq("id", auditId);
    }

    return json({ ok: true, email_id: resendBody?.id || null, recipient: parent.email });
  } catch (error) {
    console.error("send-progress-report failed:", error);
    if (auditId && admin) {
      try {
        await admin.from("spark_progress_report_email_log").update({
          status: "failed",
          error_code: "internal_error",
          completed_at: new Date().toISOString(),
        }).eq("id", auditId);
      } catch {
        // The original delivery error is more important than an audit-write failure.
      }
    }
    return json({ ok: false, error: "Could not send the progress report. Please try again." }, 500);
  }
});
