import { SECTION_E_ATOMIC_PHYSICS_LESSONS } from '../course/sectionEAtomicPhysicsLessons.mjs';
export const SECTION_E_OBJECTIVES=Object.freeze(Object.fromEntries(SECTION_E_ATOMIC_PHYSICS_LESSONS.flatMap(t=>t.objectives)));

const CUSTOM=Object.freeze({
  "E2.4": Object.freeze([{"profile": "UK", "stem": "A neutral sodium-23 atom has atomic number 11. How many neutrons does its nucleus contain?", "correct": "12", "distractors": ["11", "23", "34"], "explanation": "N = A - Z = 23 - 11 = 12."}, {"profile": "UK", "stem": "A nucleus has 17 protons and 18 neutrons. Its mass number is", "correct": "35", "distractors": ["17", "18", "1"], "explanation": "A = Z + N = 17 + 18 = 35."}, {"profile": "KC", "stem": "Which relationship correctly connects mass number A, atomic number Z and neutron number N?", "correct": "A = Z + N", "distractors": ["A = Z - N", "Z = A + N", "N = A + Z"], "explanation": "The mass number counts protons and neutrons together."}, {"profile": "UK", "stem": "A neutral atom has A = 40 and Z = 20. Which set gives its protons, neutrons and electrons?", "correct": "20 protons, 20 neutrons, 20 electrons", "distractors": ["40 protons, 20 neutrons, 20 electrons", "20 protons, 40 neutrons, 20 electrons", "20 protons, 20 neutrons, 40 electrons"], "explanation": "Z gives 20 protons, N = A - Z = 20 neutrons, and a neutral atom has 20 electrons."}]),
  "E3.2": Object.freeze([{"profile": "KC", "stem": "Which description of an alpha particle is correct?", "correct": "A helium nucleus with charge +2.", "distractors": ["A fast electron with charge -1.", "A high-energy electromagnetic wave.", "A neutral neutron emitted from the nucleus."], "explanation": "An alpha particle contains two protons and two neutrons and has charge +2."}, {"profile": "KC", "stem": "Which radioactive emission is an electromagnetic wave with no charge and no rest mass?", "correct": "gamma", "distractors": ["alpha", "beta", "a proton"], "explanation": "Gamma radiation is high-energy electromagnetic radiation."}, {"profile": "KC", "stem": "Which emission is a fast electron from the nucleus?", "correct": "beta", "distractors": ["alpha", "gamma", "a neutron"], "explanation": "Beta-minus emission is an electron emitted from a nuclear transformation."}, {"profile": "UK", "stem": "Which ordering goes from greatest ionising ability to least?", "correct": "alpha, beta, gamma", "distractors": ["gamma, beta, alpha", "beta, alpha, gamma", "alpha, gamma, beta"], "explanation": "Alpha is most strongly ionising, beta is intermediate, and gamma is least ionising."}]),
  "E3.5": Object.freeze([{"profile": "UK", "stem": "In an electric field, alpha and beta particles bend in opposite directions mainly because they", "correct": "carry opposite charges.", "distractors": ["have equal masses.", "are both uncharged.", "travel at exactly the same speed."], "explanation": "Alpha is positive and beta is negative, so their electric forces are opposite."}, {"profile": "KC", "stem": "Which radioactive emission is not deflected by either an electric field or a magnetic field?", "correct": "gamma", "distractors": ["alpha", "beta", "all three"], "explanation": "Gamma radiation is uncharged."}, {"profile": "UK", "stem": "Under comparable conditions, beta particles are deflected more strongly than alpha particles because beta particles", "correct": "have much smaller mass.", "distractors": ["have no charge.", "have twice the positive charge.", "are electromagnetic waves."], "explanation": "Beta particles are far lighter than alpha particles, so the same type of field produces a much larger curvature."}, {"profile": "UK", "stem": "A beam separates into one undeflected path and two paths bending in opposite directions. The undeflected path is", "correct": "gamma radiation.", "distractors": ["alpha radiation.", "beta radiation.", "a mixture of alpha and beta only."], "explanation": "The uncharged gamma component is not deflected."}]),
  "E3.6": Object.freeze([{"profile": "UK", "stem": "An alpha decay starts from a nucleus with A = 226 and Z = 88. The daughter nucleus has", "correct": "A = 222 and Z = 86.", "distractors": ["A = 226 and Z = 89.", "A = 222 and Z = 90.", "A = 225 and Z = 87."], "explanation": "Alpha emission reduces the mass number by 4 and the atomic number by 2."}, {"profile": "UK", "stem": "In beta-minus decay, the daughter nucleus has", "correct": "the same mass number and an atomic number one greater.", "distractors": ["mass number four less and atomic number two less.", "the same atomic number and a mass number one greater.", "both mass number and atomic number unchanged."], "explanation": "In beta-minus decay a neutron becomes a proton and an electron, so A stays fixed and Z rises by 1."}, {"profile": "KC", "stem": "Which pair of totals must balance in a nuclear equation?", "correct": "mass number and atomic number", "distractors": ["charge only and temperature", "electron shell count and pressure", "volume and density"], "explanation": "Both nucleon number and proton number must balance across a nuclear equation."}, {"profile": "UK", "stem": "Carbon-14 has Z = 6 and undergoes beta-minus decay. The daughter nucleus has A and Z equal to", "correct": "14 and 7.", "distractors": ["10 and 4.", "14 and 5.", "13 and 6."], "explanation": "Beta-minus decay leaves A unchanged and increases Z by 1."}]),
  "E3.9": Object.freeze([{"profile": "UK", "stem": "A decay graph shows a count rate falling from 800 counts/min to 400 counts/min in 6 hours and from 400 to 200 in the next 6 hours. The half-life is", "correct": "6 hours", "distractors": ["3 hours", "12 hours", "18 hours"], "explanation": "Each halving takes 6 hours, so the half-life is constant at 6 hours."}, {"profile": "KC", "stem": "On a radioactive decay graph, a constant half-life means", "correct": "successive halvings take equal time intervals.", "distractors": ["equal numbers of nuclei decay in every interval.", "the graph is a straight line through the origin.", "every nucleus decays at the same instant."], "explanation": "A constant fraction decays in equal time intervals, so successive halvings take equal times."}, {"profile": "UK", "stem": "A sample falls from 1200 counts/min to 600 counts/min in 4 days. If its half-life is constant, after a further 4 days the count rate is expected to be", "correct": "300 counts/min", "distractors": ["0 counts/min", "400 counts/min", "900 counts/min"], "explanation": "Another half-life halves 600 to 300 counts/min."}, {"profile": "KC", "stem": "Why is a smooth decay curve preferred to joining random measured points with straight segments?", "correct": "Radioactive decay is random, but a large sample follows a smooth statistical trend.", "distractors": ["Every nucleus decays at a fixed scheduled time.", "The activity must decrease by the same number each minute.", "Half-life changes after each measurement."], "explanation": "Individual decays are random while the behaviour of a large sample follows a smooth exponential trend."}]),
  "E3.10": Object.freeze([{"profile": "UK", "stem": "A radioactive sample has a half-life of 5 days. What fraction remains after 15 days?", "correct": "1/8", "distractors": ["1/3", "1/6", "1/16"], "explanation": "15 days is three half-lives, so the fraction remaining is (1/2)^3 = 1/8."}, {"profile": "UK", "stem": "A sample starts with an activity of 1600 Bq and has a half-life of 2 hours. Its activity after 6 hours is", "correct": "200 Bq", "distractors": ["800 Bq", "400 Bq", "100 Bq"], "explanation": "Six hours is three half-lives: 1600 -> 800 -> 400 -> 200 Bq."}, {"profile": "KC", "stem": "The number of half-lives elapsed is found from", "correct": "total elapsed time divided by the half-life.", "distractors": ["half-life divided by total elapsed time.", "initial activity divided by final activity only.", "initial mass plus final mass."], "explanation": "n = elapsed time / half-life."}, {"profile": "UK", "stem": "A source falls from 640 counts/min to 80 counts/min. How many half-lives have elapsed?", "correct": "3", "distractors": ["2", "4", "8"], "explanation": "640 -> 320 -> 160 -> 80, which is three halvings."}]),
  "E3.11": Object.freeze([{"profile": "UK", "stem": "Why is a gamma-emitting isotope with a short half-life useful as a medical tracer?", "correct": "Gamma can escape the body for detection and the short half-life limits the exposure time.", "distractors": ["Gamma is stopped by the skin and the short half-life makes it permanently active.", "Alpha escapes the body more easily than gamma.", "A long half-life is always preferred so the patient remains radioactive."], "explanation": "A tracer should be detectable outside the body while limiting the time the patient remains exposed."}, {"profile": "UK", "stem": "Why is beta radiation suitable for monitoring the thickness of a sheet?", "correct": "It is partly absorbed, so the detector count changes with thickness.", "distractors": ["It passes through every thickness unchanged.", "It is completely stopped by air before reaching the sheet.", "It has no interaction with matter."], "explanation": "Partial absorption makes beta count rate sensitive to sheet thickness."}, {"profile": "KC", "stem": "Carbon-14 dating is used mainly for", "correct": "once-living material.", "distractors": ["measuring the voltage of a circuit.", "mapping a magnetic field.", "determining the refractive index of glass."], "explanation": "The carbon-14 fraction remaining after death gives an estimate of the age of once-living material."}, {"profile": "UK", "stem": "A source used in an industrial gauge should often have a relatively long half-life because", "correct": "it then does not need frequent replacement.", "distractors": ["its radiation becomes non-ionising.", "the decay rate becomes dependent on temperature.", "a long half-life makes every emission alpha."], "explanation": "A longer-lived source gives a more stable useful service life."}]),
  "E3.12": Object.freeze([{"profile": "UK", "stem": "A mass of 2.0 × 10^-6 kg is converted to energy. Using c = 3.0 × 10^8 m/s, the energy released is", "correct": "1.8 × 10^11 J", "distractors": ["6.0 × 10^2 J", "1.8 × 10^5 J", "9.0 × 10^16 J"], "explanation": "E = mc^2 = 2.0 × 10^-6 × (3.0 × 10^8)^2 = 1.8 × 10^11 J."}, {"profile": "KC", "stem": "Which relationship connects a mass change to nuclear energy release?", "correct": "E = mc^2", "distractors": ["E = m/c^2", "E = mc", "E = c/m"], "explanation": "Mass-energy equivalence is E = mc^2."}, {"profile": "KC", "stem": "In a nuclear reaction that releases energy, the mass of the products is slightly", "correct": "less than the mass of the reactants.", "distractors": ["greater than the mass of the reactants by exactly one kilogram.", "equal in all cases with no mass-energy change.", "zero."], "explanation": "The mass difference corresponds to the released energy through E = mc^2."}, {"profile": "UK", "stem": "Which statement correctly distinguishes fission and fusion?", "correct": "Fission splits a heavy nucleus, while fusion joins light nuclei.", "distractors": ["Fission joins light nuclei, while fusion splits a heavy nucleus.", "Both are chemical reactions involving outer electrons only.", "Neither can release nuclear energy."], "explanation": "Fission and fusion are different nuclear processes, both able to release energy through a small mass change."}]),
});

const ANCHORS=Object.freeze({
  "E1.1": Object.freeze({"stem": "Which sequence best represents the development of the atomic model described in the course?", "correct": "Dalton solid sphere, Thomson plum pudding, Rutherford nuclear model, Bohr shells.", "distractors": ["Bohr shells, Dalton solid sphere, Rutherford nuclear model, Thomson plum pudding.", "Thomson nuclear model, Dalton shells, Rutherford plum pudding, Bohr solid sphere.", "Rutherford solid sphere, Bohr plum pudding, Thomson nucleus, Dalton shells."], "explanation": "The models changed as new evidence required a better explanation.", "profile": "KC"}),
  "E1.2": Object.freeze({"stem": "In the Geiger-Marsden experiment, most alpha particles passed through the thin foil with little or no deflection. This suggests that", "correct": "most of the atom is empty space.", "distractors": ["positive charge fills the atom uniformly.", "electrons contain nearly all atomic mass.", "the nucleus occupies most of the atomic volume."], "explanation": "Most alpha particles met no concentrated matter or charge, supporting an atom that is mostly empty space.", "profile": "KC"}),
  "E2.1": Object.freeze({"stem": "A correct sketch of a simple atom should place", "correct": "protons and neutrons in a central nucleus and electrons in shells outside.", "distractors": ["electrons and neutrons in the nucleus and protons in shells.", "all particles on one circular shell.", "only protons in the atom."], "explanation": "The nucleus contains protons and neutrons, while electrons occupy shells outside it.", "profile": "KC"}),
  "E2.2": Object.freeze({"stem": "Which comparison between a proton and an electron is correct?", "correct": "Their charges are equal in magnitude and opposite in sign, while the proton is much more massive.", "distractors": ["They have the same charge and the same mass.", "The electron is positive and heavier than the proton.", "The proton is neutral and the electron is positive."], "explanation": "A proton has charge +1 and relative mass about 1, while an electron has charge -1 and far smaller mass.", "profile": "KC"}),
  "E2.3": Object.freeze({"stem": "Why is a normal atom electrically neutral?", "correct": "It has equal numbers of protons and electrons.", "distractors": ["It contains no charged particles.", "Its neutrons cancel all proton mass.", "Its nucleus has zero charge."], "explanation": "Equal positive proton charge and negative electron charge cancel.", "profile": "KC"}),
  "E2.5": Object.freeze({"stem": "Which pair represents isotopes of the same element?", "correct": "Atoms with the same number of protons but different numbers of neutrons.", "distractors": ["Atoms with different numbers of protons and the same mass number.", "Atoms with the same neutrons but different protons.", "An atom and an ion of a different element."], "explanation": "Isotopes share atomic number but have different neutron numbers and therefore different mass numbers.", "profile": "KC"}),
  "E2.6": Object.freeze({"stem": "For the first twenty elements, what does the number of occupied electron shells indicate?", "correct": "the period", "distractors": ["the group only", "the mass number", "the neutron number"], "explanation": "The number of occupied shells gives the period, while outer-shell electrons are linked to the group.", "profile": "KC"}),
  "E3.1": Object.freeze({"stem": "Marie Curie is associated with radioactivity because she", "correct": "carried out pioneering work on radioactive materials and isolated radioactive elements including radium.", "distractors": ["proposed the plum pudding model.", "performed the Geiger-Marsden scattering experiment.", "invented the first electric cell."], "explanation": "Marie Curie made major experimental contributions to the study of radioactivity and radioactive elements.", "profile": "KC"}),
  "E3.3": Object.freeze({"stem": "Which absorber is appropriate when comparing the penetration of beta radiation after paper has been passed through?", "correct": "a few millimetres of aluminium", "distractors": ["a thin sheet of paper only", "a vacuum with no absorber", "a glass prism"], "explanation": "Beta passes through paper but is strongly reduced by a few millimetres of aluminium.", "profile": "KC"}),
  "E3.4": Object.freeze({"stem": "In a cloud chamber, alpha tracks are typically", "correct": "short, thick and relatively straight.", "distractors": ["long, thin and strongly wandering.", "invisible because alpha does not ionise.", "identical to gamma tracks in all respects."], "explanation": "Strong ionisation gives alpha particles dense, short tracks.", "profile": "KC"}),
  "E3.7": Object.freeze({"stem": "A dice model of radioactive decay best demonstrates that", "correct": "individual removals are random but a large population shows a statistical decay pattern.", "distractors": ["every die is removed after exactly the same number of throws.", "heating the dice changes their decay probability like a radioactive nucleus.", "the number removed each round must be exactly half."], "explanation": "The model represents random individual events and an approximately predictable large-sample trend.", "profile": "KC"}),
  "E3.8": Object.freeze({"stem": "Which change affects the half-life of a radioactive isotope under ordinary laboratory conditions?", "correct": "None of heating, cooling, pressure change or chemical reaction.", "distractors": ["Heating strongly shortens it.", "Cooling doubles it.", "Chemical reaction stops the decay."], "explanation": "Radioactive decay is a nuclear process and is independent of ordinary external conditions.", "profile": "KC"}),
  "E3.13": Object.freeze({"stem": "Which response gives one valid argument for and one valid argument against nuclear power?", "correct": "High energy output from little fuel, but long-lived radioactive waste must be managed.", "distractors": ["No greenhouse gases of any kind are ever associated with a station, and there is no waste.", "It uses no fuel, but produces only chemical waste.", "It depends on sunshine, but has no accident risk."], "explanation": "A balanced answer identifies specific benefits and specific costs or risks.", "profile": "KC"}),
});


const firstSentence=s=>String(s||'').trim().split(/(?<=[.!?])\s+/)[0]||String(s||'').trim();
const clip=(s,n=220)=>{const x=String(s||'').replace(/\s+/g,' ').trim();return x.length>n?x.slice(0,n-1).trim()+'…':x};
const topicForObjective=id=>SECTION_E_ATOMIC_PHYSICS_LESSONS.find(t=>t.objectives.some(([x])=>x===id));
function generatedSpecs(objective){
  const topic=topicForObjective(objective),card=topic.objectiveCards?.[objective]||{},peer=topic.objectives.filter(([id])=>id!==objective).map(([id])=>topic.objectiveCards?.[id]||{});
  const core=clip(firstSentence(card.inShort||card.detail||SECTION_E_OBJECTIVES[objective]));
  const watch=clip(firstSentence(card.watchOut||'Ignore the conditions in the question.'));
  const peerCore=[...new Set(peer.map(x=>clip(firstSentence(x.inShort||x.detail))).filter(Boolean).filter(x=>x!==core))];
  while(peerCore.length<3)peerCore.push(`A statement about a different ${topic.id} objective ${peerCore.length+1}.`);
  const exam=clip(firstSentence(card.howAsked||card.inShort||SECTION_E_OBJECTIVES[objective]));
  const examD=[...new Set(peer.map(x=>clip(firstSentence(x.howAsked||x.inShort))).filter(Boolean).filter(x=>x!==exam))];
  while(examD.length<3)examD.push(`A response aimed at a different ${topic.id} objective ${examD.length+1}.`);
  const detail=clip(firstSentence(card.detail||card.inShort||SECTION_E_OBJECTIVES[objective]));
  const detailD=[...new Set(peer.map(x=>clip(firstSentence(x.detail||x.inShort))).filter(Boolean).filter(x=>x!==detail))];
  while(detailD.length<3)detailD.push(`An unrelated statement about ${topic.title} ${detailD.length+1}.`);
  const trueD=[...new Set([core,...peerCore].filter(x=>x!==watch))].slice(0,3);while(trueD.length<3)trueD.push(`A correct statement that does not contain the named misconception ${trueD.length+1}.`);
  return [
    {profile:'KC',stem:`Which statement best addresses ${objective}: ${SECTION_E_OBJECTIVES[objective]}?`,correct:core,distractors:peerCore.slice(0,3),explanation:clip(card.inShort||card.detail||core,340)},
    {profile:'KC',stem:`Which statement is a misconception to avoid when working with ${objective}?`,correct:watch,distractors:trueD,explanation:clip(card.watchOut||'The selected statement conflicts with the syllabus treatment.',340)},
    {profile:'UK',stem:`Which point is most relevant when a question assesses ${objective}?`,correct:exam,distractors:examD.slice(0,3),explanation:clip(card.howAsked||card.inShort||exam,340)},
    {profile:'UK',stem:`Which statement is consistent with the Physics behind ${objective}?`,correct:detail,distractors:detailD.slice(0,3),explanation:clip(card.detail||card.inShort||detail,340)}
  ];
}
const PRACTICAL_SUPPORT=new Set(['E1.2','E3.3','E3.7','E3.9']);
const specs=[];
for(const objective of Object.keys(SECTION_E_OBJECTIVES)){
  let rows=CUSTOM[objective];
  if(!rows){
    const generated=generatedSpecs(objective);
    const anchor=ANCHORS[objective];
    rows=anchor?[anchor,...generated.slice(1)]:generated;
  }
  for(const row of rows) specs.push({objective,...row});
}
function makeQuestion(spec,index){
  const answer=index%4,options=[...spec.distractors];options.splice(answer,0,spec.correct);
  return Object.freeze({id:`e-atomic-${String(index+1).padStart(3,'0')}`,objective:spec.objective,topic:spec.objective.split('.')[0],profile:spec.profile||'KC',stem:spec.stem,options:Object.freeze(options),answer,explanation:spec.explanation,traps:Object.freeze(options.map((_,i)=>i===answer?'':`This option does not satisfy ${spec.objective}.`)),assessmentScope:PRACTICAL_SUPPORT.has(spec.objective)?'knowledge-support-for-practical':'objective-linked'});
}
export const SECTION_E_MCQ_BANK=Object.freeze(specs.map(makeQuestion));
function flashcardsForTopic(topic){return topic.objectives.flatMap(([objective,syllabusWording])=>{const card=topic.objectiveCards?.[objective]||{};return [
{id:`fc-${objective.toLowerCase().replace('.','-')}-1`,objective,topic:topic.id,front:syllabusWording,back:card.inShort||card.detail||'',syllabusWording},
{id:`fc-${objective.toLowerCase().replace('.','-')}-2`,objective,topic:topic.id,front:card.formula?`State the key relationship for ${objective}.`:`What should you watch out for in ${objective}?`,back:card.formula||card.watchOut||card.detail||'',syllabusWording},
{id:`fc-${objective.toLowerCase().replace('.','-')}-3`,objective,topic:topic.id,front:`How should you approach ${objective} in an examination question?`,back:card.howAsked||'State the relevant nuclear or atomic principle accurately and include the required evidence, conditions and units.',syllabusWording}
]})}
export const SECTION_E_FLASHCARDS=Object.freeze(SECTION_E_ATOMIC_PHYSICS_LESSONS.flatMap(flashcardsForTopic));
export const SECTION_E_TOPICS=Object.freeze(SECTION_E_ATOMIC_PHYSICS_LESSONS.map(topic=>Object.freeze({id:topic.id,title:topic.title,lesson:topic,objectives:Object.freeze(Object.fromEntries(topic.objectives)),mcq:Object.freeze(SECTION_E_MCQ_BANK.filter(q=>q.topic===topic.id)),flashcards:Object.freeze(SECTION_E_FLASHCARDS.filter(c=>c.topic===topic.id))})));
function rng(seed){let s=(Number(seed)>>>0)||1;return()=>((s=(1664525*s+1013904223)>>>0)/4294967296)}
function shuffle(items,random){const out=[...items];for(let i=out.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out;}
export function buildSectionEObjectiveAudit({seed=1}={}){const random=rng(seed),selected=[];for(const objective of Object.keys(SECTION_E_OBJECTIVES)){const pool=SECTION_E_MCQ_BANK.filter(q=>q.objective===objective);selected.push(pool[Math.floor(random()*pool.length)]);}return shuffle(selected,random);}
export const DEFAULT_SECTION_E_CHECKPOINT_QUOTAS=Object.freeze({E1:4,E2:8,E3:18});
export function buildSectionECheckpoint({seed=1,quotas=DEFAULT_SECTION_E_CHECKPOINT_QUOTAS}={}){const random=rng(seed),selected=[];for(const topic of SECTION_E_TOPICS){const count=Number(quotas[topic.id]||0),pool=shuffle(topic.mcq,random);if(count>pool.length)throw new Error(`Quota ${count} exceeds ${topic.id} pool`);selected.push(...pool.slice(0,count));}return shuffle(selected,random);}
export function sectionEStats(){return{section:'E',topics:SECTION_E_TOPICS.length,objectives:Object.keys(SECTION_E_OBJECTIVES).length,mcq:SECTION_E_MCQ_BANK.length,flashcards:SECTION_E_FLASHCARDS.length,byTopic:Object.fromEntries(SECTION_E_TOPICS.map(t=>[t.id,{objectives:Object.keys(t.objectives).length,mcq:t.mcq.length,flashcards:t.flashcards.length}]))};}
export const SECTION_E_PRACTICAL_SUPPORT_OBJECTIVES=Object.freeze([...PRACTICAL_SUPPORT]);
