import { SECTION_E_ATOMIC_PHYSICS_LESSONS } from '../course/sectionEAtomicPhysicsLessons.mjs';
const words=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').split(/\s+/).filter(w=>w.length>3&&!['that','with','from','this','which','when','into','than','they','their','where','what','should','would','because','about','there','have','been'].includes(w));
const terms=s=>[...new Set(words(s))].slice(0,7);
function criteriaFor(topic,id){const card=topic.objectiveCards?.[id]||{},a=terms(card.inShort||card.detail),b=terms(card.detail),c=terms(card.watchOut);return[
{code:'B1',marks:1,profile:'KC',objective:id,description:`states a correct core idea for ${id}`,check:{type:'writtenConcept',any:a.length?a:[id.toLowerCase()]}},
{code:'B2',marks:1,profile:'UK',objective:id,description:`adds relevant evidence, mechanism, interpretation or application for ${id}`,check:{type:'writtenConcept',any:b.length?b:a}},
{code:'B3',marks:1,profile:'UK',objective:id,description:'keeps the atomic or nuclear statement physically consistent',check:{type:'writtenConcept',any:[...a,...b].slice(0,9),forbidden:c.slice(0,2)}}];}
const questions=[];let serial=1;
for(const topic of SECTION_E_ATOMIC_PHYSICS_LESSONS){
  const size=topic.id==='E3'?4:3;
  for(let i=0;i<topic.objectives.length;i+=size){
    const group=topic.objectives.slice(i,i+size),parts=group.map(([id,wording],j)=>({id:String.fromCharCode(97+j),marks:3,objective:id,prompt:topic.objectiveCards?.[id]?.howAsked||`Explain or apply: ${wording}`,requireDrawing:/sketch|graph|tracks|experiment/i.test(topic.objectiveCards?.[id]?.howAsked||wording),criteria:criteriaFor(topic,id)}));
    const practical=group.some(([id,wording])=>/conduct|experiment|graph|sketch/i.test(wording));
    questions.push({id:`e-${topic.id.toLowerCase()}-p2-${String(serial++).padStart(2,'0')}`,topic:topic.id,kind:practical?'data analysis':'structured',marks:parts.reduce((s,p)=>s+p.marks,0),title:`${topic.id} ${topic.title} practice ${Math.floor(i/size)+1}`,stem:`Work through the following ${topic.title.toLowerCase()} parts. Show calculations, nuclear-number balance, evidence and practical detail where required.`,parts});
  }
}
const halfLifeData={id:'e-e3-data-half-life',topic:'E3',kind:'data analysis',marks:25,title:'Random decay and half-life data analysis',stem:'A detector records the corrected activity of a radioactive source at equal time intervals. Analyse the data as a decay curve and connect the pattern with random nuclear decay.',parts:[
{id:'a',marks:4,objective:'E3.7',prompt:'Describe a dice or coin activity that models random radioactive decay, including what represents an undecayed nucleus and what event represents decay.',requireDrawing:false,criteria:[{code:'B1',marks:1,profile:'XS',objective:'E3.7',description:'uses many dice or coins to represent many nuclei',check:{type:'writtenConcept',any:['dice','coins','nuclei']}},{code:'B2',marks:1,profile:'XS',objective:'E3.7',description:'uses a fixed random outcome as the decay event',check:{type:'writtenConcept',any:['six','head','random outcome']}},{code:'B3',marks:1,profile:'XS',objective:'E3.7',description:'removes or records decayed items before repeating',check:{type:'writtenConcept',any:['remove','remaining','repeat']}},{code:'B4',marks:1,profile:'XS',objective:'E3.7',description:'connects unpredictable individual events with a statistical large-sample trend',check:{type:'writtenConcept',any:['random','unpredictable','large sample','statistical']}}]},
{id:'b',marks:5,objective:'E3.9',prompt:'The activity falls from about 960 Bq to 480 Bq at 6 min, 240 Bq at 12 min and 120 Bq at 18 min. State the half-life and explain how the data show it is constant.',requireDrawing:true,criteria:[{code:'M1',marks:1,profile:'UK',objective:'E3.9',description:'identifies successive halvings',check:{type:'containsValues',values:[960,480,240,120],need:2}},{code:'A1',marks:1,profile:'UK',objective:'E3.9',description:'states 6 min',check:{type:'containsQuantity',value:6,unit:'min'}},{code:'B1',marks:1,profile:'UK',objective:'E3.9',description:'states that each halving takes the same time',check:{type:'writtenConcept',any:['same time','equal time','constant interval']}},{code:'B2',marks:1,profile:'XS',objective:'E3.9',description:'plots or sketches a smooth decreasing decay curve',manual:true},{code:'B3',marks:1,profile:'UK',objective:'E3.9',description:'does not claim equal numbers decay in each interval',check:{type:'writtenConcept',any:['fraction','proportion','half']}}]},
{id:'c',marks:6,objective:'E3.10',prompt:'A source has initial activity 3200 Bq and half-life 6 min. Calculate its activity after 24 min and state the fraction of the original activity that remains.',requireDrawing:false,criteria:[{code:'M1',marks:1,profile:'UK',objective:'E3.10',description:'finds four half-lives from 24/6',check:{type:'containsValues',values:[4],need:1}},{code:'M2',marks:1,profile:'UK',objective:'E3.10',description:'applies repeated halving or 1/2^n',check:{type:'writtenConcept',any:['half','1/2','2^4','2⁴']}},{code:'A1',marks:1,profile:'UK',objective:'E3.10',description:'activity is 200 Bq',check:{type:'containsQuantity',value:200,unit:'Bq'}},{code:'A2',marks:1,profile:'UK',objective:'E3.10',description:'fraction remaining is 1/16',check:{type:'writtenConcept',any:['1/16','0.0625']}},{code:'B1',marks:1,profile:'UK',objective:'E3.10',description:'keeps time units consistent',check:{type:'writtenConcept',any:['min','minute']}},{code:'B2',marks:1,profile:'UK',objective:'E3.10',description:'distinguishes activity from mass',check:{type:'writtenConcept',any:['activity','becquerel','bq']}}]},
{id:'d',marks:5,objective:'E3.8',prompt:'Explain why changing the temperature, pressure or chemical state of the source does not change its half-life.',requireDrawing:false,criteria:[{code:'B1',marks:1,profile:'KC',objective:'E3.8',description:'states radioactive decay is a nuclear process',check:{type:'writtenConcept',any:['nuclear','nucleus']}},{code:'B2',marks:1,profile:'UK',objective:'E3.8',description:'states ordinary external changes mainly affect electrons or bulk conditions',check:{type:'writtenConcept',any:['electron','chemical','external']}},{code:'B3',marks:1,profile:'UK',objective:'E3.8',description:'states heating or cooling does not alter decay rate',check:{type:'writtenConcept',any:['unaffected','does not change','independent']}},{code:'B4',marks:1,profile:'UK',objective:'E3.8',description:'states pressure does not alter decay rate',check:{type:'writtenConcept',any:['pressure','compress']}},{code:'B5',marks:1,profile:'UK',objective:'E3.8',description:'states chemical reaction does not alter decay rate',check:{type:'writtenConcept',any:['chemical','reaction']}}]},
{id:'e',marks:5,objective:'E3.11',prompt:'Give one suitable medical or industrial radioisotope application and explain how the emission type and half-life suit the job.',requireDrawing:false,criteria:[{code:'B1',marks:1,profile:'KC',objective:'E3.11',description:'names a valid application',check:{type:'writtenConcept',any:['tracer','thickness','gauge','dating','sterilis','radiotherapy','medical']}},{code:'B2',marks:1,profile:'UK',objective:'E3.11',description:'identifies a suitable emission type',check:{type:'writtenConcept',any:['gamma','beta']}},{code:'B3',marks:1,profile:'UK',objective:'E3.11',description:'links penetration or absorption to detection',check:{type:'writtenConcept',any:['penetrat','detect','absorb','escape']}},{code:'B4',marks:1,profile:'UK',objective:'E3.11',description:'discusses a suitable half-life',check:{type:'writtenConcept',any:['half-life','half life','short','long']}},{code:'B5',marks:1,profile:'UK',objective:'E3.11',description:'connects half-life choice to exposure or replacement frequency',check:{type:'writtenConcept',any:['exposure','replace','patient','service life']}}]}
]};
questions.push(halfLifeData);
export const SECTION_E_STRUCTURED_BANK=Object.freeze(questions);
export function sectionEStructuredStats(){return{questions:SECTION_E_STRUCTURED_BANK.length,marks:SECTION_E_STRUCTURED_BANK.reduce((s,q)=>s+q.marks,0),byTopic:Object.fromEntries(SECTION_E_ATOMIC_PHYSICS_LESSONS.map(t=>[t.id,SECTION_E_STRUCTURED_BANK.filter(q=>q.topic===t.id).length]))};}
