import React, { useState } from 'react';
import PhysicsMechanicsPractice from '../../mechanics/components/PhysicsMechanicsPractice';
import PhysicsThermalPractice from '../../thermal/components/PhysicsThermalPractice';
import PhysicsWavesPractice from '../../waves/components/PhysicsWavesPractice';
import PhysicsElectricityPractice from '../../electricity/components/PhysicsElectricityPractice';
import PhysicsAtomicPractice from '../../atomic/components/PhysicsAtomicPractice';
import PhysicsPaper2Exam from '../../paper2/components/PhysicsPaper2Exam';
import './physicsSubjectView.css';

const PRACTICE_SECTIONS=[
  {id:'A',title:'Mechanics',detail:'Topic tests, structured practice and the Section A checkpoint.',ready:true},
  {id:'B',title:'Thermal Physics and Kinetic Theory',detail:'Topic tests, structured practice and the Section B checkpoint.',ready:true},
  {id:'C',title:'Waves and Optics',detail:'Topic tests, structured practice and the Section C checkpoint.',ready:true},
  {id:'D',title:'Electricity and Magnetism',detail:'Topic tests, structured practice and the Section D checkpoint.',ready:true},
  {id:'E',title:'The Physics of the Atom',detail:'Topic tests, structured practice and the Section E checkpoint.',ready:true},
];
export default function PhysicsPracticeHub({userId,onBack,onActivity}){const[section,setSection]=useState(null);if(section==='paper2')return <PhysicsPaper2Exam userId={userId} onBack={()=>setSection(null)} onActivity={onActivity}/>;if(section==='A')return <PhysicsMechanicsPractice userId={userId} onBack={()=>setSection(null)} onActivity={onActivity}/>;if(section==='B')return <PhysicsThermalPractice userId={userId} onBack={()=>setSection(null)} onActivity={onActivity}/>;if(section==='C')return <PhysicsWavesPractice userId={userId} onBack={()=>setSection(null)} onActivity={onActivity}/>;if(section==='D')return <PhysicsElectricityPractice userId={userId} onBack={()=>setSection(null)} onActivity={onActivity}/>;if(section==='E')return <PhysicsAtomicPractice userId={userId} onBack={()=>setSection(null)} onActivity={onActivity}/>;return <main className="physics-subject-view"><div className="psv-shell"><header className="psv-hero"><div>{onBack&&<button type="button" className="psv-back" onClick={onBack}><span className="psv-back-arrow" aria-hidden="true"><svg viewBox="0 0 20 20" focusable="false"><path d="M12.5 5.5 8 10l4.5 4.5M8 10h8"/></svg></span><span>Change subject</span></button>}<div className="psv-eyebrow">CSEC Physics practice</div><h1>Choose a practice mode</h1><p>Practise by syllabus section or sit a full Physics Paper 02 simulation under examination conditions.</p></div></header><section className="psv-section-grid"><button type="button" className="psv-section-card" onClick={()=>setSection('paper2')}><span className="psv-section-code">02</span><span className="psv-section-copy"><span className="psv-section-status">Full examination simulator</span><strong>Physics Paper 2</strong><small>Four complete 100-mark practice papers, 2 hours 30 minutes each, with interactive graphs, autosave and criterion-by-criterion review.</small></span><span className="psv-section-arrow" aria-hidden="true"><svg className="psv-section-arrow-icon" viewBox="0 0 20 20" focusable="false"><path d="M6 14L14 6M8 6h6v6"/></svg></span></button>{PRACTICE_SECTIONS.map(s=><button key={s.id} type="button" className={`psv-section-card ${s.ready?'':'psv-section-card-disabled'}`} onClick={()=>s.ready&&setSection(s.id)} disabled={!s.ready}><span className="psv-section-code">{s.id}</span><span className="psv-section-copy"><span className="psv-section-status">{s.ready?'Practice available':'Lessons available'}</span><strong>{s.title}</strong><small>{s.detail}</small></span><span className="psv-section-arrow" aria-hidden="true">{s.ready?<svg className="psv-section-arrow-icon" viewBox="0 0 20 20" focusable="false"><path d="M6 14L14 6M8 6h6v6"/></svg>:<span className="psv-unavailable-dot">•</span>}</span></button>)}</section></div></main>}
