begin;

-- Generic, subject-scoped progress snapshots. New SPARK subjects can write to
-- this table through the RPCs below without adding subject-specific columns to
-- the dashboard or parent reporting schema.
create table if not exists public.spark_subject_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  subject_id text not null,
  activity_key text not null,
  activity_type text not null,
  section_id text,
  topic_id text,
  title text not null,
  completed boolean not null default false,
  score numeric(10,2),
  max_score numeric(10,2),
  percent numeric(6,2),
  best_percent numeric(6,2),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  metadata jsonb not null default '{}'::jsonb,
  completed_at timestamptz,
  first_recorded_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, subject_id, activity_key),
  check (subject_id ~ '^[a-z0-9][a-z0-9_-]{0,39}$'),
  check (char_length(activity_key) between 1 and 120),
  check (activity_type in ('lesson','lab','flashcard','topic_quiz','section_checkpoint','exam','practice','other')),
  check (percent is null or percent between 0 and 100),
  check (best_percent is null or best_percent between 0 and 100),
  check (max_score is null or max_score >= 0),
  check (score is null or score >= 0)
);

create index if not exists spark_subject_progress_user_subject_updated_idx
  on public.spark_subject_progress(user_id, subject_id, updated_at desc);
create index if not exists spark_subject_progress_user_updated_idx
  on public.spark_subject_progress(user_id, updated_at desc);

create table if not exists public.spark_subject_activity_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  subject_id text not null,
  activity_key text not null,
  activity_type text not null,
  section_id text,
  topic_id text,
  title text not null,
  completed boolean not null default true,
  score numeric(10,2),
  max_score numeric(10,2),
  percent numeric(6,2),
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  check (subject_id ~ '^[a-z0-9][a-z0-9_-]{0,39}$'),
  check (char_length(activity_key) between 1 and 120),
  check (activity_type in ('lesson','lab','flashcard','topic_quiz','section_checkpoint','exam','practice','other')),
  check (percent is null or percent between 0 and 100),
  check (max_score is null or max_score >= 0),
  check (score is null or score >= 0)
);

create index if not exists spark_subject_activity_events_user_subject_occurred_idx
  on public.spark_subject_activity_events(user_id, subject_id, occurred_at desc);
create index if not exists spark_subject_activity_events_user_occurred_idx
  on public.spark_subject_activity_events(user_id, occurred_at desc);

alter table public.spark_subject_progress enable row level security;
alter table public.spark_subject_activity_events enable row level security;
revoke all on public.spark_subject_progress from anon;
revoke insert, update, delete on public.spark_subject_progress from authenticated;
grant select on public.spark_subject_progress to authenticated;

drop policy if exists "Students view own subject progress" on public.spark_subject_progress;
create policy "Students view own subject progress"
on public.spark_subject_progress
for select
to authenticated
using (
  auth.uid() = user_id
  and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'student')
);

drop policy if exists "Parents view linked child subject progress" on public.spark_subject_progress;
create policy "Parents view linked child subject progress"
on public.spark_subject_progress
for select
to authenticated
using (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'parent')
  and exists (
    select 1 from public.parent_student_links psl
    where psl.parent_id = auth.uid()
      and psl.student_id = spark_subject_progress.user_id
      and psl.status = 'approved'
  )
);

revoke all on public.spark_subject_activity_events from anon;
revoke insert, update, delete on public.spark_subject_activity_events from authenticated;
grant select on public.spark_subject_activity_events to authenticated;

drop policy if exists "Students view own subject activity events" on public.spark_subject_activity_events;
create policy "Students view own subject activity events"
on public.spark_subject_activity_events
for select
to authenticated
using (
  auth.uid() = user_id
  and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'student')
);

drop policy if exists "Parents view linked child subject activity events" on public.spark_subject_activity_events;
create policy "Parents view linked child subject activity events"
on public.spark_subject_activity_events
for select
to authenticated
using (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'parent')
  and exists (
    select 1 from public.parent_student_links psl
    where psl.parent_id = auth.uid()
      and psl.student_id = spark_subject_activity_events.user_id
      and psl.status = 'approved'
  )
);

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'spark_subject_progress'
    ) then
      alter publication supabase_realtime add table public.spark_subject_progress;
    end if;
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'spark_subject_activity_events'
    ) then
      alter publication supabase_realtime add table public.spark_subject_activity_events;
    end if;
  end if;
end $$;

create or replace function public.spark_record_subject_progress(
  p_subject_id text,
  p_activity_key text,
  p_activity_type text,
  p_section_id text default null,
  p_topic_id text default null,
  p_title text default null,
  p_completed boolean default true,
  p_score numeric default null,
  p_max_score numeric default null,
  p_percent numeric default null,
  p_metadata jsonb default '{}'::jsonb,
  p_silent boolean default false
)
returns public.spark_subject_progress
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_subject_id text := lower(trim(coalesce(p_subject_id, '')));
  v_key text := trim(coalesce(p_activity_key, ''));
  v_type text := lower(trim(coalesce(p_activity_type, '')));
  v_title text := left(coalesce(nullif(trim(p_title), ''), v_key), 180);
  v_score numeric := case when p_score is null then null else greatest(0, p_score) end;
  v_max numeric := case when p_max_score is null then null else greatest(0, p_max_score) end;
  v_percent numeric(6,2);
  v_row public.spark_subject_progress;
  v_is_attempt boolean;
  v_existing_completed_at timestamptz;
  v_should_log boolean := false;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  if not exists (select 1 from public.profiles p where p.id = v_user_id and p.role = 'student') then
    raise exception 'Only Student accounts can record learning progress';
  end if;
  if v_subject_id !~ '^[a-z0-9][a-z0-9_-]{0,39}$' then raise exception 'Invalid subject id'; end if;
  if char_length(v_key) not between 1 and 120 then raise exception 'Invalid activity key'; end if;
  if v_type not in ('lesson','lab','flashcard','topic_quiz','section_checkpoint','exam','practice','other') then
    raise exception 'Unsupported subject activity type';
  end if;
  if v_score is not null and v_max is not null and v_max > 0 then
    v_score := least(v_score, v_max);
    v_percent := round((v_score / v_max) * 100, 2);
  elsif p_percent is not null then
    v_percent := greatest(0, least(100, p_percent));
  else
    v_percent := null;
  end if;
  v_is_attempt := v_type in ('topic_quiz','section_checkpoint','exam','practice');

  select sp.completed_at into v_existing_completed_at
  from public.spark_subject_progress sp
  where sp.user_id = v_user_id and sp.subject_id = v_subject_id and sp.activity_key = v_key;

  insert into public.spark_subject_progress(
    user_id, subject_id, activity_key, activity_type, section_id, topic_id, title,
    completed, score, max_score, percent, best_percent, attempt_count, metadata,
    completed_at, first_recorded_at, updated_at
  ) values (
    v_user_id, v_subject_id, v_key, v_type, nullif(trim(coalesce(p_section_id,'')),''),
    nullif(trim(coalesce(p_topic_id,'')),''), v_title, coalesce(p_completed, false),
    v_score, v_max, v_percent, v_percent,
    case when v_is_attempt and not coalesce(p_silent,false) then 1 else 0 end,
    coalesce(p_metadata,'{}'::jsonb) || jsonb_build_object('subject_id',v_subject_id),
    case when coalesce(p_completed,false) then now() else null end, now(), now()
  )
  on conflict (user_id, subject_id, activity_key) do update set
    activity_type = excluded.activity_type,
    section_id = coalesce(excluded.section_id, public.spark_subject_progress.section_id),
    topic_id = coalesce(excluded.topic_id, public.spark_subject_progress.topic_id),
    title = excluded.title,
    completed = excluded.completed,
    completed_at = coalesce(public.spark_subject_progress.completed_at, excluded.completed_at),
    score = coalesce(excluded.score, public.spark_subject_progress.score),
    max_score = coalesce(excluded.max_score, public.spark_subject_progress.max_score),
    percent = coalesce(excluded.percent, public.spark_subject_progress.percent),
    best_percent = case
      when excluded.percent is null then public.spark_subject_progress.best_percent
      else greatest(coalesce(public.spark_subject_progress.best_percent,0), excluded.percent)
    end,
    attempt_count = public.spark_subject_progress.attempt_count
      + case when v_is_attempt and not coalesce(p_silent,false) then 1 else 0 end,
    metadata = public.spark_subject_progress.metadata || excluded.metadata,
    updated_at = now()
  returning * into v_row;

  if not coalesce(p_silent,false) then
    v_should_log := v_is_attempt
      or v_type = 'flashcard'
      or (v_type in ('lesson','lab') and coalesce(p_completed,false) and v_existing_completed_at is null);
  end if;

  if v_should_log then
    insert into public.spark_subject_activity_events(
      user_id, subject_id, activity_key, activity_type, section_id, topic_id, title,
      completed, score, max_score, percent, metadata, occurred_at, created_at
    ) values (
      v_user_id, v_subject_id, v_key, v_type,
      nullif(trim(coalesce(p_section_id,'')),''), nullif(trim(coalesce(p_topic_id,'')),''),
      v_title, coalesce(p_completed,false), v_score, v_max, v_percent,
      coalesce(p_metadata,'{}'::jsonb) || jsonb_build_object('subject_id',v_subject_id),
      now(), now()
    );
  end if;

  return v_row;
end;
$$;

revoke all on function public.spark_record_subject_progress(text,text,text,text,text,text,boolean,numeric,numeric,numeric,jsonb,boolean) from public, anon;
grant execute on function public.spark_record_subject_progress(text,text,text,text,text,text,boolean,numeric,numeric,numeric,jsonb,boolean) to authenticated;

-- One-time/backfill synchronizer for progress that existed locally before the
-- subject-progress table was introduced. It never increments attempt counts or
-- sends notifications, and repeated calls are idempotent.
create or replace function public.spark_sync_subject_progress(
  p_subject_id text,
  p_rows jsonb
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_subject_id text := lower(trim(coalesce(p_subject_id,'')));
  v_item jsonb;
  v_count integer := 0;
  v_key text;
  v_type text;
  v_percent numeric;
  v_best numeric;
  v_attempts integer;
  v_when timestamptz;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  if not exists (select 1 from public.profiles p where p.id = v_user_id and p.role = 'student') then
    raise exception 'Only Student accounts can sync learning progress';
  end if;
  if v_subject_id !~ '^[a-z0-9][a-z0-9_-]{0,39}$' then raise exception 'Invalid subject id'; end if;
  if jsonb_typeof(coalesce(p_rows,'[]'::jsonb)) <> 'array' then raise exception 'Progress rows must be an array'; end if;
  if jsonb_array_length(coalesce(p_rows,'[]'::jsonb)) > 250 then raise exception 'Too many progress rows'; end if;

  for v_item in select value from jsonb_array_elements(coalesce(p_rows,'[]'::jsonb)) loop
    v_key := trim(coalesce(v_item->>'activity_key',''));
    v_type := lower(trim(coalesce(v_item->>'activity_type','')));
    if char_length(v_key) not between 1 and 120 then continue; end if;
    if v_type not in ('lesson','lab','flashcard','topic_quiz','section_checkpoint','exam','practice','other') then continue; end if;
    begin v_percent := nullif(v_item->>'percent','')::numeric; exception when others then v_percent := null; end;
    begin v_best := nullif(v_item->>'best_percent','')::numeric; exception when others then v_best := null; end;
    begin v_attempts := greatest(0,coalesce(nullif(v_item->>'attempt_count','')::integer,0)); exception when others then v_attempts := 0; end;
    begin v_when := nullif(v_item->>'occurred_at','')::timestamptz; exception when others then v_when := null; end;

    insert into public.spark_subject_progress(
      user_id, subject_id, activity_key, activity_type, section_id, topic_id, title,
      completed, score, max_score, percent, best_percent, attempt_count, metadata,
      completed_at, first_recorded_at, updated_at
    ) values (
      v_user_id, v_subject_id, v_key, v_type,
      nullif(trim(coalesce(v_item->>'section_id','')),''), nullif(trim(coalesce(v_item->>'topic_id','')),''),
      left(coalesce(nullif(trim(v_item->>'title'),''),v_key),180),
      coalesce((v_item->>'completed')::boolean,false),
      case when v_item ? 'score' and nullif(v_item->>'score','') is not null then greatest(0,(v_item->>'score')::numeric) else null end,
      case when v_item ? 'max_score' and nullif(v_item->>'max_score','') is not null then greatest(0,(v_item->>'max_score')::numeric) else null end,
      case when v_percent is null then null else greatest(0,least(100,v_percent)) end,
      case when coalesce(v_best,v_percent) is null then null else greatest(0,least(100,coalesce(v_best,v_percent))) end,
      v_attempts,
      coalesce(v_item->'metadata','{}'::jsonb) || jsonb_build_object('subject_id',v_subject_id,'backfilled',true),
      case when coalesce((v_item->>'completed')::boolean,false) then coalesce(v_when,now()) else null end,
      coalesce(v_when,now()), coalesce(v_when,now())
    )
    on conflict (user_id,subject_id,activity_key) do update set
      completed = case
        when excluded.activity_type in ('lesson','lab') then public.spark_subject_progress.completed or excluded.completed
        else public.spark_subject_progress.completed
      end,
      completed_at = coalesce(public.spark_subject_progress.completed_at, excluded.completed_at),
      score = coalesce(public.spark_subject_progress.score, excluded.score),
      max_score = coalesce(public.spark_subject_progress.max_score, excluded.max_score),
      percent = coalesce(public.spark_subject_progress.percent, excluded.percent),
      best_percent = greatest(coalesce(public.spark_subject_progress.best_percent,0),coalesce(excluded.best_percent,0)),
      attempt_count = greatest(public.spark_subject_progress.attempt_count, excluded.attempt_count),
      metadata = public.spark_subject_progress.metadata || excluded.metadata,
      updated_at = case
        when public.spark_subject_progress.updated_at is null then excluded.updated_at
        when v_when is null then public.spark_subject_progress.updated_at
        else greatest(public.spark_subject_progress.updated_at, excluded.updated_at)
      end;
    v_count := v_count + 1;
  end loop;
  return v_count;
end;
$$;

revoke all on function public.spark_sync_subject_progress(text,jsonb) from public, anon;
grant execute on function public.spark_sync_subject_progress(text,jsonb) to authenticated;

-- Make SPARK Points reflect learning across subjects. Mathematics continues to
-- use its existing detailed tables. Generic subject progress adds credit for
-- non-Mathematics lesson and assessment activity without changing mastery.
create or replace function public.spark_reward_lifetime_points(p_student_id uuid)
returns integer
language sql
stable
security definer
set search_path = public
as $$
select (
  coalesce((select count(*) * 20 from public.lesson_progress lp where lp.user_id = p_student_id and lp.completed = true), 0)
  + coalesce((select count(*) * 5 from public.csec_question_attempts qa where qa.user_id = p_student_id and qa.correct is true), 0)
  + coalesce((select count(*) * 2 from public.spark_flashcard_review_events fr where fr.user_id = p_student_id), 0)
  + coalesce((select sum(case when pe.paper_type = 'paper2' then 100 else 75 end) from public.practice_exam_attempts pe where pe.user_id = p_student_id and pe.completed_at is not null), 0)
  + coalesce((select sum(case lm.event_type
      when 'topic_quiz_completed' then 30
      when 'adaptive_session_completed' then 25
      when 'skill_improved' then 40
      when 'mastery_milestone' then 50
      else 0 end)
      from public.learning_milestones lm where lm.user_id = p_student_id), 0)
  + coalesce((select count(*) * 20 from public.spark_subject_progress sp
      where sp.user_id = p_student_id and sp.subject_id <> 'mathematics'
        and sp.activity_type = 'lesson' and sp.completed = true), 0)
  + coalesce((select sum((case sp.activity_type when 'topic_quiz' then 30 when 'section_checkpoint' then 50 when 'exam' then 75 when 'practice' then 25 else 0 end) * greatest(sp.attempt_count,0))
      from public.spark_subject_progress sp
      where sp.user_id = p_student_id and sp.subject_id <> 'mathematics'
        and sp.activity_type in ('topic_quiz','section_checkpoint','exam','practice') and sp.attempt_count > 0), 0)
  + coalesce((select count(*) * 2 from public.spark_subject_activity_events se
      where se.user_id = p_student_id and se.subject_id <> 'mathematics' and se.activity_type = 'flashcard'), 0)
)::int;
$$;

revoke all on function public.spark_reward_lifetime_points(uuid) from public;
revoke all on function public.spark_reward_lifetime_points(uuid) from authenticated;

-- Replace the weekly scorer with a cross-subject version while preserving the
-- existing JSON contract consumed by SparkRewardsPanel.
create or replace function public.spark_reward_weekly_scores(p_week_start date)
returns table (
  user_id uuid,
  study_days integer,
  lessons_completed integer,
  topic_quizzes_completed integer,
  question_attempts integer,
  correct_questions integer,
  exams_completed integer,
  flashcard_reviews integer,
  skills_improved integer,
  mastery_milestones integer,
  consistency_points integer,
  improvement_points integer,
  practice_points integer,
  lesson_points integer,
  exam_points integer,
  flashcard_points integer,
  weekly_points integer
)
language sql
stable
security definer
set search_path = public
as $$
with students as (
  select p.id as user_id from public.profiles p where p.role = 'student'
),
lesson_events as (
  select lp.user_id, lp.completed_at as happened_at
  from public.lesson_progress lp
  where lp.completed = true and lp.completed_at is not null
  union all
  select se.user_id, se.occurred_at
  from public.spark_subject_activity_events se
  where se.subject_id <> 'mathematics' and se.activity_type = 'lesson' and se.completed = true
),
lesson_counts as (
  select le.user_id, count(*)::int as lessons_completed
  from lesson_events le
  where (timezone('America/Jamaica', le.happened_at))::date >= p_week_start
    and (timezone('America/Jamaica', le.happened_at))::date < p_week_start + 7
  group by le.user_id
),
question_counts as (
  select qa.user_id, count(*)::int as question_attempts,
         count(*) filter (where qa.correct is true)::int as correct_questions
  from public.csec_question_attempts qa
  where qa.attempted_at is not null
    and (timezone('America/Jamaica', qa.attempted_at))::date >= p_week_start
    and (timezone('America/Jamaica', qa.attempted_at))::date < p_week_start + 7
  group by qa.user_id
),
subject_practice as (
  select se.user_id,
         count(*) filter (where se.activity_type='topic_quiz')::int as topic_quizzes_completed,
         count(*) filter (where se.activity_type in ('section_checkpoint','exam'))::int as exams_completed
  from public.spark_subject_activity_events se
  where se.subject_id <> 'mathematics'
    and se.activity_type in ('topic_quiz','section_checkpoint','exam','practice')
    and (timezone('America/Jamaica', se.occurred_at))::date >= p_week_start
    and (timezone('America/Jamaica', se.occurred_at))::date < p_week_start + 7
  group by se.user_id
),
exam_counts as (
  select pe.user_id, count(*)::int as exams_completed
  from public.practice_exam_attempts pe
  where pe.completed_at is not null
    and (timezone('America/Jamaica', pe.completed_at))::date >= p_week_start
    and (timezone('America/Jamaica', pe.completed_at))::date < p_week_start + 7
  group by pe.user_id
),
flashcard_events as (
  select fr.user_id, fr.reviewed_at as happened_at
  from public.spark_flashcard_review_events fr
  where fr.reviewed_at is not null
  union all
  select se.user_id, se.occurred_at
  from public.spark_subject_activity_events se
  where se.subject_id <> 'mathematics' and se.activity_type = 'flashcard'
),
flashcard_counts as (
  select fe.user_id, count(*)::int as flashcard_reviews
  from flashcard_events fe
  where (timezone('America/Jamaica', fe.happened_at))::date >= p_week_start
    and (timezone('America/Jamaica', fe.happened_at))::date < p_week_start + 7
  group by fe.user_id
),
milestone_counts as (
  select lm.user_id,
         count(*) filter (where lm.event_type = 'topic_quiz_completed')::int as topic_quizzes_completed,
         count(*) filter (where lm.event_type = 'skill_improved')::int as skills_improved,
         count(*) filter (where lm.event_type = 'mastery_milestone')::int as mastery_milestones
  from public.learning_milestones lm
  where lm.created_at is not null
    and (timezone('America/Jamaica', lm.created_at))::date >= p_week_start
    and (timezone('America/Jamaica', lm.created_at))::date < p_week_start + 7
  group by lm.user_id
),
study_dates as (
  select le.user_id, (timezone('America/Jamaica', le.happened_at))::date as study_date from lesson_events le
  union
  select qa.user_id, (timezone('America/Jamaica', qa.attempted_at))::date from public.csec_question_attempts qa where qa.attempted_at is not null
  union
  select pe.user_id, (timezone('America/Jamaica', pe.completed_at))::date from public.practice_exam_attempts pe where pe.completed_at is not null
  union
  select fr.user_id, (timezone('America/Jamaica', fr.reviewed_at))::date from public.spark_flashcard_review_events fr where fr.reviewed_at is not null
  union
  select lm.user_id, (timezone('America/Jamaica', lm.created_at))::date from public.learning_milestones lm where lm.created_at is not null
  union
  select se.user_id, (timezone('America/Jamaica', se.occurred_at))::date
  from public.spark_subject_activity_events se
  where se.subject_id <> 'mathematics' and se.occurred_at is not null
),
day_counts as (
  select user_id, count(distinct study_date)::int as study_days
  from study_dates
  where study_date >= p_week_start and study_date < p_week_start + 7
  group by user_id
),
base as (
  select s.user_id,
         coalesce(dc.study_days,0)::int as study_days,
         coalesce(lc.lessons_completed,0)::int as lessons_completed,
         (coalesce(mc.topic_quizzes_completed,0)+coalesce(sp.topic_quizzes_completed,0))::int as topic_quizzes_completed,
         coalesce(qc.question_attempts,0)::int as question_attempts,
         coalesce(qc.correct_questions,0)::int as correct_questions,
         (coalesce(ec.exams_completed,0)+coalesce(sp.exams_completed,0))::int as exams_completed,
         coalesce(fc.flashcard_reviews,0)::int as flashcard_reviews,
         coalesce(mc.skills_improved,0)::int as skills_improved,
         coalesce(mc.mastery_milestones,0)::int as mastery_milestones
  from students s
  left join day_counts dc on dc.user_id=s.user_id
  left join lesson_counts lc on lc.user_id=s.user_id
  left join question_counts qc on qc.user_id=s.user_id
  left join exam_counts ec on ec.user_id=s.user_id
  left join flashcard_counts fc on fc.user_id=s.user_id
  left join milestone_counts mc on mc.user_id=s.user_id
  left join subject_practice sp on sp.user_id=s.user_id
),
scored as (
  select b.*,
         least(25,b.study_days*4)::int as consistency_points,
         least(25,b.skills_improved*10+b.mastery_milestones*5)::int as improvement_points,
         least(20,case when b.question_attempts<=0 then 0 when b.question_attempts<5 then b.correct_questions*2 else round(12.0*(b.correct_questions::numeric/nullif(b.question_attempts,0))+least(8.0,b.question_attempts::numeric/5.0))::int end)::int as practice_points,
         least(15,b.lessons_completed*5+b.topic_quizzes_completed*3)::int as lesson_points,
         least(10,b.exams_completed*5)::int as exam_points,
         least(5,ceil(b.flashcard_reviews::numeric/5.0))::int as flashcard_points
  from base b
)
select s.*,(s.consistency_points+s.improvement_points+s.practice_points+s.lesson_points+s.exam_points+s.flashcard_points)::int as weekly_points
from scored s;
$$;

revoke all on function public.spark_reward_weekly_scores(date) from public;
revoke all on function public.spark_reward_weekly_scores(date) from authenticated;

comment on table public.spark_subject_progress is
'Subject-neutral student progress snapshots used by student dashboards, linked-parent reporting and future SPARK subjects.';
comment on table public.spark_subject_activity_events is
'Append-only subject activity events used for accurate weekly streaks and rewards without mixing subject-specific accuracy denominators.';
comment on function public.spark_record_subject_progress(text,text,text,text,text,text,boolean,numeric,numeric,numeric,jsonb,boolean) is
'Records or updates one subject-scoped learning activity for the authenticated Student account.';

commit;
