-- ============================================================================
-- SPARK V5.6.1 - Answer Intelligence
--
-- This is an observational model. It records how the deterministic grader
-- classified an answer AFTER the grade is decided. It never changes answer
-- keys, marks, mastery, or the current verdict.
-- ============================================================================

create table if not exists public.spark_answer_observations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id text not null,
  skill text not null,
  source text not null default 'adaptive_practice',
  status text not null check (status in ('correct','incorrect','uncertain','blank')),
  marks_earned numeric not null default 0,
  marks_available numeric not null default 1 check (marks_available > 0),
  error_code text,
  error_label text,
  grader text not null,
  grader_confidence text not null default 'high',
  self_assessed boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists spark_answer_observations_user_created_idx
  on public.spark_answer_observations (user_id, created_at desc);
create index if not exists spark_answer_observations_question_idx
  on public.spark_answer_observations (question_id, created_at desc);
create index if not exists spark_answer_observations_error_idx
  on public.spark_answer_observations (user_id, skill, error_code)
  where error_code is not null;

create table if not exists public.spark_answer_pattern_state (
  user_id uuid not null references auth.users(id) on delete cascade,
  skill text not null,
  error_code text not null,
  error_label text,
  occurrences integer not null default 0 check (occurrences >= 0),
  last_question_id text,
  last_source text,
  last_seen_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (user_id, skill, error_code)
);

create table if not exists public.spark_question_validation_state (
  question_id text primary key,
  total_observations bigint not null default 0,
  correct_count bigint not null default 0,
  incorrect_count bigint not null default 0,
  uncertain_count bigint not null default 0,
  self_assessed_count bigint not null default 0,
  canonical_conflict_count bigint not null default 0,
  last_grader text,
  last_seen_at timestamptz,
  updated_at timestamptz not null default now()
);

alter table public.spark_answer_observations enable row level security;
alter table public.spark_answer_pattern_state enable row level security;
alter table public.spark_question_validation_state enable row level security;

drop policy if exists "Students can read own answer observations" on public.spark_answer_observations;
create policy "Students can read own answer observations"
  on public.spark_answer_observations
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Students can read own answer patterns" on public.spark_answer_pattern_state;
create policy "Students can read own answer patterns"
  on public.spark_answer_pattern_state
  for select
  to authenticated
  using (auth.uid() = user_id);

-- No direct authenticated INSERT/UPDATE/DELETE policies. Writes go through the
-- security-definer function below. Question-level aggregate health remains
-- private from ordinary clients and is intended for admin/content QA.
revoke insert, update, delete on public.spark_answer_observations from authenticated;
revoke insert, update, delete on public.spark_answer_pattern_state from authenticated;
revoke all on public.spark_question_validation_state from authenticated;

drop function if exists public.spark_record_answer_observation(
  text,text,text,text,numeric,numeric,text,text,text,text,boolean,jsonb
);

create or replace function public.spark_record_answer_observation(
  p_question_id text,
  p_skill text,
  p_source text default 'adaptive_practice',
  p_status text default 'incorrect',
  p_marks_earned numeric default 0,
  p_marks_available numeric default 1,
  p_error_code text default null,
  p_error_label text default null,
  p_grader text default 'cxc-canonical-v5.6.1',
  p_grader_confidence text default 'high',
  p_self_assessed boolean default false,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_status text := lower(coalesce(nullif(trim(p_status), ''), 'incorrect'));
  v_skill text := coalesce(nullif(trim(p_skill), ''), 'CSEC Mathematics');
  v_question_id text := coalesce(nullif(trim(p_question_id), ''), 'unknown');
  v_source text := coalesce(nullif(trim(p_source), ''), 'adaptive_practice');
  v_error_code text := nullif(trim(p_error_code), '');
  v_now timestamptz := now();
begin
  if v_user_id is null then
    raise exception 'Authentication required';
  end if;

  if v_status not in ('correct','incorrect','uncertain','blank') then
    raise exception 'Unsupported answer status: %', v_status;
  end if;

  insert into public.spark_answer_observations (
    user_id, question_id, skill, source, status,
    marks_earned, marks_available, error_code, error_label,
    grader, grader_confidence, self_assessed, metadata, created_at
  ) values (
    v_user_id, v_question_id, v_skill, v_source, v_status,
    greatest(0, coalesce(p_marks_earned, 0)), greatest(0.000001, coalesce(p_marks_available, 1)),
    v_error_code, nullif(trim(p_error_label), ''),
    coalesce(nullif(trim(p_grader), ''), 'cxc-canonical-v5.6.1'),
    coalesce(nullif(trim(p_grader_confidence), ''), 'review'),
    coalesce(p_self_assessed, false), coalesce(p_metadata, '{}'::jsonb), v_now
  );

  if v_error_code is not null and v_status <> 'correct' then
    insert into public.spark_answer_pattern_state (
      user_id, skill, error_code, error_label, occurrences,
      last_question_id, last_source, last_seen_at, updated_at
    ) values (
      v_user_id, v_skill, v_error_code, nullif(trim(p_error_label), ''), 1,
      v_question_id, v_source, v_now, v_now
    )
    on conflict (user_id, skill, error_code) do update
      set occurrences = public.spark_answer_pattern_state.occurrences + 1,
          error_label = coalesce(excluded.error_label, public.spark_answer_pattern_state.error_label),
          last_question_id = excluded.last_question_id,
          last_source = excluded.last_source,
          last_seen_at = excluded.last_seen_at,
          updated_at = excluded.updated_at;
  end if;

  insert into public.spark_question_validation_state (
    question_id, total_observations, correct_count, incorrect_count,
    uncertain_count, self_assessed_count, canonical_conflict_count,
    last_grader, last_seen_at, updated_at
  ) values (
    v_question_id,
    1,
    case when v_status = 'correct' then 1 else 0 end,
    case when v_status = 'incorrect' then 1 else 0 end,
    case when v_status = 'uncertain' then 1 else 0 end,
    case when coalesce(p_self_assessed, false) then 1 else 0 end,
    case when v_error_code = 'canonical_conflict' or coalesce((p_metadata->>'canonical_conflict')::boolean, false) then 1 else 0 end,
    coalesce(nullif(trim(p_grader), ''), 'cxc-canonical-v5.6.1'),
    v_now, v_now
  )
  on conflict (question_id) do update
    set total_observations = public.spark_question_validation_state.total_observations + 1,
        correct_count = public.spark_question_validation_state.correct_count + excluded.correct_count,
        incorrect_count = public.spark_question_validation_state.incorrect_count + excluded.incorrect_count,
        uncertain_count = public.spark_question_validation_state.uncertain_count + excluded.uncertain_count,
        self_assessed_count = public.spark_question_validation_state.self_assessed_count + excluded.self_assessed_count,
        canonical_conflict_count = public.spark_question_validation_state.canonical_conflict_count + excluded.canonical_conflict_count,
        last_grader = excluded.last_grader,
        last_seen_at = excluded.last_seen_at,
        updated_at = excluded.updated_at;

  return jsonb_build_object(
    'ok', true,
    'question_id', v_question_id,
    'status', v_status,
    'error_code', v_error_code
  );
end;
$$;

revoke all on function public.spark_record_answer_observation(
  text,text,text,text,numeric,numeric,text,text,text,text,boolean,jsonb
) from public, anon;
grant execute on function public.spark_record_answer_observation(
  text,text,text,text,numeric,numeric,text,text,text,text,boolean,jsonb
) to authenticated;
