-- SPARK V5.6.0 Learner Model
-- Explainable statistical knowledge tracing for CSEC Mathematics.
-- Each meaningful learning event updates one student's skill state.

create table if not exists public.spark_learner_skill_state (
  user_id uuid not null references auth.users(id) on delete cascade,
  skill text not null,
  mastery_probability numeric(7,6) not null default 0.500000 check (mastery_probability between 0 and 1),
  confidence numeric(7,6) not null default 0.000000 check (confidence between 0 and 1),
  evidence_count integer not null default 0 check (evidence_count >= 0),
  correct_weight numeric(12,4) not null default 0 check (correct_weight >= 0),
  incorrect_weight numeric(12,4) not null default 0 check (incorrect_weight >= 0),
  recent_score numeric(7,6) not null default 0.500000 check (recent_score between 0 and 1),
  trend_score numeric(8,7) not null default 0,
  last_result boolean,
  last_practised_at timestamptz,
  last_source text,
  misconception_counts jsonb not null default '{}'::jsonb,
  misconception_labels jsonb not null default '{}'::jsonb,
  recommended_action text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, skill)
);

create table if not exists public.spark_learner_evidence (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  skill text not null,
  source text not null,
  evidence_key text not null,
  item_id text,
  correct boolean not null,
  evidence_weight numeric(8,4) not null default 1 check (evidence_weight > 0),
  difficulty text,
  response_seconds integer,
  help_used boolean not null default false,
  error_code text,
  error_label text,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (user_id, source, evidence_key)
);

create index if not exists spark_learner_skill_state_user_priority_idx
  on public.spark_learner_skill_state (user_id, mastery_probability, confidence);
create index if not exists spark_learner_evidence_user_skill_time_idx
  on public.spark_learner_evidence (user_id, skill, occurred_at desc);

alter table public.spark_learner_skill_state enable row level security;
alter table public.spark_learner_evidence enable row level security;

revoke all on public.spark_learner_skill_state from anon;
revoke all on public.spark_learner_evidence from anon;
revoke insert, update, delete on public.spark_learner_skill_state from authenticated;
revoke insert, update, delete on public.spark_learner_evidence from authenticated;

drop policy if exists "Students can read own learner state" on public.spark_learner_skill_state;
create policy "Students can read own learner state"
on public.spark_learner_skill_state for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Approved parents can read learner state" on public.spark_learner_skill_state;
create policy "Approved parents can read learner state"
on public.spark_learner_skill_state for select
to authenticated
using (
  exists (
    select 1
    from public.parent_student_links psl
    where psl.parent_id = auth.uid()
      and psl.student_id = spark_learner_skill_state.user_id
      and psl.status = 'approved'
  )
);

drop policy if exists "Students can read own learner evidence" on public.spark_learner_evidence;
create policy "Students can read own learner evidence"
on public.spark_learner_evidence for select
to authenticated
using (auth.uid() = user_id);

grant select on public.spark_learner_skill_state to authenticated;
grant select on public.spark_learner_evidence to authenticated;

create or replace function public.spark_apply_learner_evidence(
  p_user_id uuid,
  p_skill text,
  p_source text,
  p_item_id text default null,
  p_correct boolean default false,
  p_evidence_weight numeric default 1,
  p_difficulty text default null,
  p_response_seconds integer default null,
  p_help_used boolean default false,
  p_error_code text default null,
  p_error_label text default null,
  p_metadata jsonb default '{}'::jsonb,
  p_evidence_key text default null,
  p_occurred_at timestamptz default now()
)
returns public.spark_learner_skill_state
language plpgsql
security definer
set search_path = public
as $$
declare
  v_skill text := nullif(btrim(p_skill), '');
  v_source text := coalesce(nullif(btrim(p_source), ''), 'unknown');
  v_key text := coalesce(nullif(btrim(p_evidence_key), ''), md5(random()::text || clock_timestamp()::text));
  v_weight numeric := greatest(0.05, least(2.0, coalesce(p_evidence_weight, 1)));
  v_state public.spark_learner_skill_state%rowtype;
  v_inserted_id bigint;
  v_correct_weight numeric;
  v_incorrect_weight numeric;
  v_recent numeric;
  v_bayes numeric;
  v_mastery numeric;
  v_previous numeric;
  v_trend numeric;
  v_confidence numeric;
  v_misconceptions jsonb;
  v_labels jsonb;
  v_error_count integer;
begin
  if p_user_id is null or v_skill is null then
    raise exception 'A student and skill are required';
  end if;

  if lower(coalesce(p_difficulty, '')) in ('easy', 'e') then
    v_weight := v_weight * 0.85;
  elsif lower(coalesce(p_difficulty, '')) in ('hard', 'h', 'difficult') then
    v_weight := v_weight * 1.15;
  end if;

  if coalesce(p_help_used, false) then
    v_weight := v_weight * 0.75;
  end if;

  if coalesce(p_response_seconds, 0) > 900 then
    v_weight := v_weight * 0.90;
  elsif p_response_seconds is not null and p_response_seconds between 0 and 3 then
    v_weight := v_weight * 0.85;
  end if;

  v_weight := greatest(0.05, least(2.0, v_weight));

  insert into public.spark_learner_evidence (
    user_id, skill, source, evidence_key, item_id, correct, evidence_weight,
    difficulty, response_seconds, help_used, error_code, error_label, metadata, occurred_at
  ) values (
    p_user_id, v_skill, v_source, v_key, p_item_id, coalesce(p_correct, false), v_weight,
    p_difficulty, p_response_seconds, coalesce(p_help_used, false), nullif(btrim(p_error_code), ''),
    nullif(btrim(p_error_label), ''), coalesce(p_metadata, '{}'::jsonb), coalesce(p_occurred_at, now())
  )
  on conflict (user_id, source, evidence_key) do nothing
  returning id into v_inserted_id;

  if v_inserted_id is null then
    select * into v_state
    from public.spark_learner_skill_state
    where user_id = p_user_id and skill = v_skill;
    return v_state;
  end if;

  select * into v_state
  from public.spark_learner_skill_state
  where user_id = p_user_id and skill = v_skill
  for update;

  if not found then
    v_state.user_id := p_user_id;
    v_state.skill := v_skill;
    v_state.mastery_probability := 0.5;
    v_state.confidence := 0;
    v_state.evidence_count := 0;
    v_state.correct_weight := 0;
    v_state.incorrect_weight := 0;
    v_state.recent_score := 0.5;
    v_state.trend_score := 0;
    v_state.misconception_counts := '{}'::jsonb;
    v_state.misconception_labels := '{}'::jsonb;
  end if;

  v_previous := coalesce(v_state.mastery_probability, 0.5);
  v_correct_weight := coalesce(v_state.correct_weight, 0) + case when p_correct then v_weight else 0 end;
  v_incorrect_weight := coalesce(v_state.incorrect_weight, 0) + case when p_correct then 0 else v_weight end;

  -- Beta(2,2) prior keeps the first few answers from creating false certainty.
  v_bayes := (2 + v_correct_weight) / (4 + v_correct_weight + v_incorrect_weight);
  -- Recent performance matters, but does not erase the accumulated history.
  v_recent := greatest(0, least(1, coalesce(v_state.recent_score, 0.5) * 0.70 + (case when p_correct then 1 else 0 end) * 0.30));
  v_mastery := greatest(0.01, least(0.99, v_bayes * 0.75 + v_recent * 0.25));
  v_trend := greatest(-0.25, least(0.25, coalesce(v_state.trend_score, 0) * 0.65 + (v_mastery - v_previous) * 0.35));
  v_confidence := greatest(0, least(0.99, 1 - exp(-(v_correct_weight + v_incorrect_weight) / 6.0)));

  v_misconceptions := coalesce(v_state.misconception_counts, '{}'::jsonb);
  v_labels := coalesce(v_state.misconception_labels, '{}'::jsonb);
  if not p_correct and nullif(btrim(p_error_code), '') is not null then
    begin
      v_error_count := coalesce((v_misconceptions ->> p_error_code)::integer, 0) + 1;
    exception when others then
      v_error_count := 1;
    end;
    v_misconceptions := jsonb_set(v_misconceptions, array[p_error_code], to_jsonb(v_error_count), true);
    if nullif(btrim(p_error_label), '') is not null then
      v_labels := jsonb_set(v_labels, array[p_error_code], to_jsonb(p_error_label), true);
    end if;
  end if;

  insert into public.spark_learner_skill_state (
    user_id, skill, mastery_probability, confidence, evidence_count,
    correct_weight, incorrect_weight, recent_score, trend_score, last_result,
    last_practised_at, last_source, misconception_counts, misconception_labels,
    recommended_action, created_at, updated_at
  ) values (
    p_user_id, v_skill, v_mastery, v_confidence, coalesce(v_state.evidence_count, 0) + 1,
    v_correct_weight, v_incorrect_weight, v_recent, v_trend, p_correct,
    coalesce(p_occurred_at, now()), v_source, v_misconceptions, v_labels,
    case
      when v_confidence < 0.20 then 'Build a stronger baseline with a lesson and a short practice set.'
      when v_mastery < 0.45 then 'Review the lesson, then do targeted Adaptive Practice and related flashcards.'
      when v_mastery < 0.60 then 'Use targeted Adaptive Practice and flashcards before moving to harder questions.'
      when v_mastery < 0.75 then 'Mix targeted practice with harder questions to make the skill more reliable.'
      when v_mastery < 0.85 then 'Use spaced review and exam-style questions to strengthen consistency.'
      else 'Maintain this skill with spaced review while SPARK shifts attention to weaker areas.'
    end,
    coalesce(v_state.created_at, now()), now()
  )
  on conflict (user_id, skill) do update set
    mastery_probability = excluded.mastery_probability,
    confidence = excluded.confidence,
    evidence_count = excluded.evidence_count,
    correct_weight = excluded.correct_weight,
    incorrect_weight = excluded.incorrect_weight,
    recent_score = excluded.recent_score,
    trend_score = excluded.trend_score,
    last_result = excluded.last_result,
    last_practised_at = excluded.last_practised_at,
    last_source = excluded.last_source,
    misconception_counts = excluded.misconception_counts,
    misconception_labels = excluded.misconception_labels,
    recommended_action = excluded.recommended_action,
    updated_at = now()
  returning * into v_state;

  -- Compatibility bridge. Existing Adaptive Practice already consumes
  -- csec_skill_progress. For matching skills, feed the richer mastery estimate
  -- back into that table without changing its schema or question-selection code.
  if to_regclass('public.csec_skill_progress') is not null then
    update public.csec_skill_progress
    set mastery_score = round(v_mastery * 100)
    where user_id = p_user_id and skill = v_skill;
  end if;

  return v_state;
end;
$$;

revoke all on function public.spark_apply_learner_evidence(uuid,text,text,text,boolean,numeric,text,integer,boolean,text,text,jsonb,text,timestamptz) from public;
revoke all on function public.spark_apply_learner_evidence(uuid,text,text,text,boolean,numeric,text,integer,boolean,text,text,jsonb,text,timestamptz) from anon;
revoke all on function public.spark_apply_learner_evidence(uuid,text,text,text,boolean,numeric,text,integer,boolean,text,text,jsonb,text,timestamptz) from authenticated;

create or replace function public.spark_record_learner_evidence(
  p_skill text,
  p_source text,
  p_item_id text default null,
  p_correct boolean default false,
  p_evidence_weight numeric default 1,
  p_difficulty text default null,
  p_response_seconds integer default null,
  p_help_used boolean default false,
  p_error_code text default null,
  p_error_label text default null,
  p_metadata jsonb default '{}'::jsonb,
  p_evidence_key text default null,
  p_occurred_at timestamptz default now()
)
returns public.spark_learner_skill_state
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
begin
  if v_user is null then
    raise exception 'Authentication required';
  end if;
  return public.spark_apply_learner_evidence(
    v_user, p_skill, p_source, p_item_id, p_correct, p_evidence_weight,
    p_difficulty, p_response_seconds, p_help_used, p_error_code, p_error_label,
    p_metadata, p_evidence_key, p_occurred_at
  );
end;
$$;

grant execute on function public.spark_record_learner_evidence(text,text,text,boolean,numeric,text,integer,boolean,text,text,jsonb,text,timestamptz) to authenticated;
revoke execute on function public.spark_record_learner_evidence(text,text,text,boolean,numeric,text,integer,boolean,text,text,jsonb,text,timestamptz) from anon;

create or replace function public.spark_capture_csec_question_attempt()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v jsonb := to_jsonb(new);
  v_user uuid;
  v_skill text;
  v_correct boolean;
  v_item text;
  v_key text;
  v_difficulty text;
  v_error_code text;
  v_error_label text;
  v_seconds integer;
  v_help boolean;
begin
  begin v_user := nullif(v ->> 'user_id', '')::uuid; exception when others then return new; end;
  v_skill := coalesce(nullif(v ->> 'skill', ''), nullif(v ->> 'topic', ''), nullif(v ->> 'subtopic', ''));
  if v_user is null or v_skill is null then return new; end if;

  begin
    v_correct := coalesce(nullif(v ->> 'correct', '')::boolean, nullif(v ->> 'is_correct', '')::boolean, false);
  exception when others then
    v_correct := false;
  end;
  v_item := coalesce(nullif(v ->> 'question_id', ''), nullif(v ->> 'item_id', ''), nullif(v ->> 'id', ''));
  v_key := coalesce(nullif(v ->> 'id', ''), md5(v::text));
  v_difficulty := nullif(v ->> 'difficulty', '');
  v_error_code := coalesce(nullif(v ->> 'error_code', ''), nullif(v ->> 'misconception', ''), nullif(v ->> 'mistake_code', ''));
  v_error_label := coalesce(nullif(v ->> 'error_label', ''), nullif(v ->> 'misconception_label', ''));
  begin v_seconds := nullif(v ->> 'response_seconds', '')::integer; exception when others then v_seconds := null; end;
  begin v_help := coalesce(nullif(v ->> 'help_used', '')::boolean, false); exception when others then v_help := false; end;

  perform public.spark_apply_learner_evidence(
    v_user, v_skill, coalesce(nullif(v ->> 'source', ''), 'adaptive_practice'),
    v_item, v_correct, 1, v_difficulty, v_seconds, v_help, v_error_code, v_error_label,
    jsonb_build_object('captured_by', 'csec_question_attempts_trigger'), v_key,
    coalesce(nullif(v ->> 'attempted_at', '')::timestamptz, now())
  );
  return new;
exception when others then
  -- Learner modelling must never prevent the original practice attempt saving.
  raise warning 'SPARK learner model capture failed: %', sqlerrm;
  return new;
end;
$$;

do $$
begin
  if to_regclass('public.csec_question_attempts') is not null then
    execute 'drop trigger if exists spark_capture_learner_evidence on public.csec_question_attempts';
    execute 'drop trigger if exists zz_spark_capture_learner_evidence on public.csec_question_attempts';
    -- The zz prefix intentionally runs this after existing AFTER INSERT triggers,
    -- so the compatibility mastery bridge is the final mastery signal written.
    execute 'create trigger zz_spark_capture_learner_evidence after insert on public.csec_question_attempts for each row execute function public.spark_capture_csec_question_attempt()';
  end if;
end;
$$;

-- Seed the new model from the mastery SPARK already has. This preserves each
-- student's history instead of treating V5.6.0 as a blank start.
do $$
declare
  r record;
  v jsonb;
  v_probability numeric;
  v_attempts integer;
begin
  if to_regclass('public.csec_skill_progress') is null then return; end if;
  for r in execute 'select * from public.csec_skill_progress' loop
    v := to_jsonb(r);
    if nullif(v ->> 'user_id', '') is null or nullif(v ->> 'skill', '') is null then continue; end if;
    begin
      v_probability := greatest(0.01, least(0.99, coalesce(nullif(v ->> 'mastery_score', '')::numeric, 50) / 100.0));
    exception when others then
      v_probability := 0.5;
    end;
    begin
      v_attempts := greatest(1, coalesce(
        nullif(v ->> 'attempt_count', '')::integer,
        nullif(v ->> 'attempts', '')::integer,
        nullif(v ->> 'total_attempts', '')::integer,
        1
      ));
    exception when others then
      v_attempts := 1;
    end;

    insert into public.spark_learner_skill_state (
      user_id, skill, mastery_probability, confidence, evidence_count,
      correct_weight, incorrect_weight, recent_score, trend_score,
      last_practised_at, last_source, recommended_action
    ) values (
      (v ->> 'user_id')::uuid,
      v ->> 'skill',
      v_probability,
      least(0.85, 1 - exp(-v_attempts / 6.0)),
      v_attempts,
      v_attempts * v_probability,
      v_attempts * (1 - v_probability),
      v_probability,
      0,
      coalesce(nullif(v ->> 'updated_at', '')::timestamptz, nullif(v ->> 'last_attempted_at', '')::timestamptz, now()),
      'existing_mastery',
      case
        when v_probability < 0.45 then 'Review the lesson, then do targeted Adaptive Practice and related flashcards.'
        when v_probability < 0.60 then 'Use targeted Adaptive Practice and flashcards before moving to harder questions.'
        when v_probability < 0.75 then 'Mix targeted practice with harder questions to make the skill more reliable.'
        when v_probability < 0.85 then 'Use spaced review and exam-style questions to strengthen consistency.'
        else 'Maintain this skill with spaced review while SPARK shifts attention to weaker areas.'
      end
    ) on conflict (user_id, skill) do nothing;
  end loop;
end;
$$;
