export const ADVANCED_SOCIAL_STUDIES_CONCEPTS = Object.freeze({
  // Research design, evidence and SBA language
  research_problem:["research problem","problem being studied","issue being investigated","research issue","topic under investigation"],
  research_question:["research question","question being investigated","main research question","question guiding the study"],
  research_objective:["research objective","aim of the study","purpose of the study","what the research intends to find out"],
  hypothesis:["hypothesis","testable statement","prediction to be tested","statement to be tested"],
  primary_data:["primary data","first-hand data","first hand data","data collected directly","original data collected by researcher"],
  secondary_data:["secondary data","existing data","published data","information already collected","data from books reports websites"],
  sample:["sample","selected participants","subset of population","group chosen for study"],
  research_population:["research population","target population","all persons being studied","entire group of interest"],
  sampling_bias:["sampling bias","biased sample","unrepresentative sample","sample does not represent population"],
  open_question:["open-ended question","open ended question","respondent answers in own words","allows detailed response"],
  closed_question:["closed-ended question","closed ended question","fixed response options","yes or no question","multiple choice survey question"],
  pilot_test:["pilot test","pilot study","pretest questionnaire","pre-test questionnaire","test questionnaire before full study"],
  research_validity:["validity","measures what it is intended to measure","accurately measures intended issue"],
  research_reliability:["reliability","consistent results","same method gives similar results","repeatable results"],
  informed_consent:["informed consent","participant agrees after being informed","permission from participants","voluntary consent"],
  research_confidentiality:["confidentiality","keep participant information private","protect responses from disclosure"],
  research_anonymity:["anonymity","participant not identified","no names collected","identity unknown"],
  research_neutrality:["neutral wording","unbiased question","avoid leading questions","question does not influence answer"],
  leading_question:["leading question","question suggests an answer","biased question wording","pushes respondent toward answer"],
  quantitative_data:["quantitative data","numerical data","numbers","measurable data","data expressed in numbers"],
  qualitative_data:["qualitative data","descriptive data","non numerical data","opinions experiences descriptions"],
  frequency_table:["frequency table","table showing frequencies","count table","frequency distribution"],
  bar_graph:["bar graph","bar chart"],
  pie_chart:["pie chart","circle graph"],
  line_graph:["line graph","line chart","trend graph"],
  research_finding:["finding","research finding","result from data","statement based on data"],
  evidence_based_conclusion:["evidence-based conclusion","conclusion based on findings","conclusion supported by data","conclusion from evidence"],
  evidence_based_recommendation:["evidence-based recommendation","recommendation based on findings","action supported by data","recommendation linked to evidence"],

  // Family decision-making and support
  family_needs:["family needs","household needs","basic needs of family","needs such as food shelter education"],
  family_resources:["family resources","household resources","income time skills and assets","resources available to family"],
  family_decision_making:["family decision making","household decision making","family makes decisions","joint decisions"],
  prioritise_needs:["prioritise needs","prioritize needs","put needs before wants","rank household needs"],
  needs_vs_wants:["needs and wants","needs versus wants","distinguish needs from wants","basic needs before wants"],
  child_welfare:["child welfare","well-being of child","wellbeing of child","best interests of child"],
  family_support_network:["support network","extended family support","community support for family","relatives help family"],

  // Civic participation and accountability
  civic_participation:["civic participation","citizen participation","community participation","take part in public affairs"],
  petition:["petition","sign a petition","petition government"],
  public_consultation:["public consultation","town hall consultation","public meeting","government consultation"],
  peaceful_protest:["peaceful protest","peaceful demonstration","lawful protest"],
  contact_representative:["contact representative","write to member of parliament","contact councillor","contact elected representative"],
  watchdog_media:["watchdog role of media","media holds government accountable","investigative journalism","media scrutiny"],
  ombudsman:["ombudsman","office of the ombudsman","complaints investigator","independent complaints office"],
  anti_corruption:["anti-corruption","fight corruption","prevent corruption","corruption prevention"],
  corruption:["corruption","abuse of public office","bribery","misuse of public funds"],
  public_accountability:["public accountability","government answerable to citizens","officials explain decisions","account for public spending"],
  civic_responsibility:["civic responsibility","responsibility as a citizen","citizen duty","public duty"],

  // Population and human development
  population_growth:["population growth","increase in population","population gets larger"],
  population_decline:["population decline","decrease in population","population gets smaller"],
  high_birth_rate:["high birth rate","many births","large number of births"],
  low_death_rate:["low death rate","fewer deaths","declining mortality"],
  youth_dependency:["youth dependency","large dependent child population","many children depend on working adults"],
  elderly_dependency:["elderly dependency","older dependants","aging dependants","elderly depend on working population"],
  brain_gain:["brain gain","skilled workers return","professionals return home","country gains skilled migrants"],
  return_migration:["return migration","migrants return home","returning residents"],
  skills_mismatch:["skills mismatch","workers lack skills employers need","training does not match jobs"],
  productivity:["productivity","output per worker","worker efficiency","produce more efficiently"],
  quality_of_life:["quality of life","living conditions","well-being","wellbeing","standard of living and services"],

  // Environment and sustainable development
  waste_management:["waste management","manage solid waste","garbage collection and disposal","solid waste management"],
  recycling_programme:["recycling programme","recycling program","community recycling","separate recyclable waste"],
  protected_area:["protected area","national park","marine protected area","protected forest"],
  environmental_awareness:["environmental awareness","public environmental education","teach people to protect environment"],
  water_conservation:["water conservation","save water","reduce water waste","efficient water use"],
  energy_conservation:["energy conservation","save electricity","reduce energy use","conserve electricity"],
  sustainable_agriculture:["sustainable agriculture","sustainable farming","farming that protects soil and resources"],
  disaster_risk_reduction:["disaster risk reduction","reduce disaster risk","risk reduction measures","prepare communities for hazards"],

  // Regional development, trade, ICT and tourism
  economic_growth:["economic growth","increase in output","growth in gdp","economy produces more"],
  economic_development:["economic development","improvement in living standards","better quality of life with economic progress","social and economic improvement"],
  export_diversification:["export diversification","sell different exports","broaden export base","more types of exports"],
  import_dependence:["import dependence","dependence on imports","rely heavily on imported goods"],
  foreign_direct_investment:["foreign direct investment","fdi","foreign investment in businesses","overseas firms invest locally"],
  local_ownership:["local ownership","locally owned businesses","caribbean owned business","domestic ownership"],
  digital_divide:["digital divide","unequal access to technology","lack of internet access","unequal digital access"],
  broadband_access:["broadband access","internet access","high speed internet","reliable internet"],
  digital_skills:["digital skills","computer skills","ict skills","technology skills"],
  e_government:["e-government","online government services","digital government services","government services online"],
  sustainable_tourism:["sustainable tourism","tourism that protects environment and communities","responsible tourism"],
  eco_tourism:["ecotourism","eco-tourism","nature-based tourism","environmentally responsible tourism"],
  community_tourism:["community tourism","community-based tourism","local community tourism"],
  tourism_multiplier:["tourism multiplier","tourist spending circulates locally","tourism spending supports other sectors"],
  tourism_infrastructure:["tourism infrastructure","airports roads hotels attractions","infrastructure supporting tourism"],
  tourism_training:["tourism training","hospitality training","train tourism workers","customer service training"],
  destination_marketing:["destination marketing","market the destination","tourism advertising","promote country to visitors"],
  visitor_safety:["visitor safety","tourist safety","security for visitors","safe tourism destination"],
  heritage_preservation:["heritage preservation","protect heritage sites","preserve historic sites","protect cultural heritage"],
});