export const DEVELOPMENT_CONCEPTS = Object.freeze({
  brain_drain:["brain drain","loss of skilled workers","loss of trained workers","loss of professionals","skilled people leaving","trained professionals leaving"],
  emigration:["emigration","emigrate","leave the country","move overseas","migrate abroad","leave to live abroad"],
  skilled_workers:["skilled workers","trained workers","professionals","qualified workers","highly trained people","educated workers"],
  low_wages:["low wages","low salaries","poor pay","inadequate pay","higher pay abroad","better salaries abroad"],
  unemployment:["unemployment","lack of jobs","few jobs","limited employment","job shortage","cannot find work"],
  underemployment:["underemployment","work below skill level","insufficient hours","part time when full time wanted"],
  poor_working_conditions:["poor working conditions","bad working conditions","unsafe workplace","heavy workload","inadequate working environment"],
  limited_career_growth:["limited promotion","few promotion opportunities","limited career growth","lack of advancement","few professional opportunities"],
  limited_education_opportunities:["limited tertiary education","few training opportunities","limited higher education","lack of specialist training"],
  insecurity_crime:["crime","violence","insecurity","unsafe community","fear for safety","high crime"],
  low_standard_living:["low standard of living","poor quality of life","inadequate services","poor public services"],
  job_creation:["create jobs","create more jobs","create skilled jobs","provide employment","expand employment","new skilled jobs","employment opportunities","provide suitable employment"],
  better_wages:["higher wages","better salaries","competitive salaries","improve salaries","raise salaries","increase salaries","improve pay","better pay","salary increase","better compensation"],
  better_work_conditions:["better working conditions","improve workplace","safer workplaces","reasonable workload","improved benefits"],
  career_development:["career development","promotion opportunities","professional development","training opportunities","career progression"],
  improve_social_services:["improve social services","better healthcare","better education","improve infrastructure","raise standard of living"],
  retain_workers:["retain skilled workers","workers remain","reduce emigration","encourage professionals to stay","keep trained workers","reduce brain drain"],

  small_market:["small market","small domestic market","limited market size","small population market"],
  high_transport_cost:["high transport cost","high shipping cost","expensive shipping","expensive regional transport","high freight cost"],
  natural_hazards:["natural hazards","hurricanes","tropical storms","earthquakes","volcanic eruptions","disasters"],
  disaster_disruption:["business disruption after hurricanes","production disrupted","storm damage","infrastructure damage","disaster losses"],
  trade_barriers:["trade barriers","tariffs","customs barriers","import restrictions","bureaucratic trade procedures","border delays"],
  limited_resources:["limited resources","scarce resources","small land area","limited minerals"],
  debt_burden:["high debt","debt burden","public debt","national debt"],
  climate_change:["climate change","global warming","changing climate"],
  greenhouse_gases:["greenhouse gases","carbon dioxide","co2","methane","heat trapping gases"],
  fossil_fuels:["fossil fuels","burning oil","burning coal","burning gas","petroleum combustion","fuel combustion"],
  deforestation:["deforestation","cutting down trees","forest clearing","remove forests"],
  renewable_energy:["renewable energy","solar energy","wind energy","clean energy","reduce fossil fuel use"],
  energy_efficiency:["energy efficiency","use less electricity","efficient appliances","conserve energy"],
  public_transport:["public transport","mass transit","bus system","carpool","reduce private vehicle use"],
  reforestation:["reforestation","plant trees","tree planting","restore forests","protect forests"],
  waste_reduction:["reduce waste","recycling","reuse materials","proper waste disposal"],
  lower_emissions:["reduce emissions","lower greenhouse gases","less carbon dioxide","reduce pollution","lower carbon footprint"],
  protect_environment:["protect environment","environmental protection","conserve resources","protect natural resources","sustainable use"],

  gdp:["gross domestic product","gdp","value of goods and services produced"],
  life_expectancy:["life expectancy","average years expected to live"],
  literacy:["literacy rate","ability to read and write","literacy"],
  hdi:["human development index","hdi"],
  value_added:["value added","process raw materials","manufacture finished goods","higher value product"],
  tourism_linkage:["tourism linkage","hotel buys local","local farmers supply hotels","tourism supports agriculture","link tourism to local suppliers"],
});