export const EXTENDED_SOCIAL_STUDIES_CONCEPTS = Object.freeze({
  // Family law, parenting and family relationships
  parental_responsibility:["parental responsibility","parents responsible for children","duty to care for children","responsibility for child welfare","legal responsibility for children"],
  child_maintenance:["child maintenance","financial maintenance","financial support for child","support children financially","provide financial support for children"],
  child_education_duty:["send children to school","ensure children attend school","ensure they attend school","make sure children attend school","ensure education","provide education for children","support children's education","school attendance"],
  child_protection_duty:["protect children from harm","protect child from abuse","ensure child safety","keep children safe from harm"],
  inheritance_rights:["inheritance rights","right to inherit","inherit property","succession rights"],
  family_law_marriage:["marriage law","legal marriage requirements","laws governing marriage","legal age for marriage"],
  family_law_divorce:["divorce law","legal dissolution of marriage","laws governing divorce"],
  responsible_parenthood:["responsible parenthood","responsible parenting","effective parenting","good parenting"],
  parental_guidance:["parental guidance","guide children","give advice to children","provide guidance"],
  parental_supervision:["parental supervision","supervise children","monitor children","know children's activities"],
  discipline_consistent:["consistent discipline","fair discipline","set clear rules","reasonable rules","consistent rules"],
  parental_role_model:["role model","set a good example","parents model good behaviour","parents model good behavior"],
  family_conflict:["family conflict","arguments at home","family disagreement","household conflict"],
  poor_communication:["poor communication","lack of communication","communication breakdown","do not talk openly"],
  financial_conflict:["financial problems","money problems","arguments about money","financial difficulties"],
  unequal_duties:["unequal household duties","unfair division of chores","one person does most chores","unequal responsibilities"],
  conflict_resolution:["conflict resolution","resolve conflict","settle disagreement","manage disagreement"],
  family_compromise:["family compromise","compromise at home","each person gives a little"],
  family_mediation:["family mediation","mediator helps family","neutral person helps resolve conflict"],

  // Culture and diversity
  cultural_form_music:["music","reggae","calypso","soca","dancehall","steelpan music","mento"],
  cultural_form_dance:["dance","folk dance","quadrille","limbo","traditional dance"],
  cultural_form_food:["food","cuisine","caribbean cuisine","traditional food","jerk","roti"],
  cultural_form_festival:["festival","carnival","crop over","junkanoo","emancipation celebration"],
  cultural_form_language:["language","creole","patois","dialect","caribbean language"],
  cultural_form_religion:["religion","religious practice","spiritual practice","faith tradition"],
  cultural_form_art:["art","craft","visual art","caribbean art","craftwork"],
  african_heritage:["african heritage","african ancestry","african influence","enslaved africans","african cultural influence"],
  european_heritage:["european heritage","european influence","colonisation","colonization","colonial influence"],
  indian_heritage:["indian heritage","east indian influence","indentured indians","indian cultural influence"],
  indigenous_heritage:["indigenous heritage","taino influence","kalinago influence","amerindian heritage","indigenous cultural influence"],
  chinese_heritage:["chinese heritage","chinese influence","chinese migrants"],
  migration_culture:["migration brought cultures","migrants brought traditions","migration increased cultural diversity","movement of people spread culture"],
  slavery_culture:["slavery brought african peoples","enslavement influenced culture","transatlantic slavery shaped culture"],
  indentureship_culture:["indentureship","indentured labour","indentured labor","indentured workers brought culture"],
  colonisation_culture:["colonisation","colonization","colonial rule influenced culture","european colonial influence"],
  cultural_tourism:["cultural tourism","culture attracts tourists","festivals attract visitors","heritage tourism"],
  global_cultural_reach:["global audience","international audience","worldwide popularity","culture known internationally","global influence"],
  music_global_impact:["caribbean music influenced global music","reggae worldwide","dancehall influence","soca abroad","caribbean rhythms worldwide"],
  food_global_impact:["caribbean food popular abroad","caribbean cuisine overseas","caribbean restaurants abroad"],
  diaspora_cultural_spread:["diaspora spreads culture","migrants promote culture overseas","caribbean communities abroad share culture"],

  // Government, citizenship and parties
  autocracy:["autocracy","autocratic government","rule by one person","rule by small group","limited political participation"],
  democratic_participation:["citizen participation","public participation","people participate in government","citizens choose representatives"],
  government_social_services:["provide social services","education services","health services","housing services","welfare services"],
  government_economic_management:["manage economy","economic management","promote economic growth","economic policy","support economic development"],
  government_law_order:["maintain law and order","police services","public order","enforce laws","protect citizens"],
  government_foreign_relations:["foreign relations","international relations","diplomacy","relations with other countries"],
  citizen_vote:["right to vote","vote in elections","elect representatives","participate in elections"],
  citizen_free_expression:["freedom of expression","freedom of speech","express views"],
  citizen_association:["freedom of association","join organisations","join organizations","join political parties"],
  citizen_obey_law:["obey laws","follow laws","respect the law"],
  citizen_pay_taxes:["pay taxes","pay tax","contribute taxes"],
  citizen_community_service:["community service","volunteer","volunteerism","serve community"],
  party_candidates:["select candidates","choose candidates","nominate candidates"],
  party_manifesto:["prepare manifesto","prepare a manifesto","write a manifesto","publish manifesto","publish a manifesto","develop party programme","develop party program","campaign promises"],
  party_campaign:["campaign","hold rallies","canvass voters","political campaign","campaign meetings"],
  party_government:["form government","seek political office","win election and govern","contest elections"],
  party_opposition:["provide opposition","criticise government","criticize government","hold government accountable"],
  verify_information:["verify information","fact check","fact-check","check multiple sources","confirm information"],
  official_information:["official source","electoral office","government website","recognised news source","recognized news source"],
  propaganda_emotion:["emotional appeal","fear appeal","one-sided message","selective information","misleading persuasion"],

  // Population and migration
  population_planning:["population planning","plan schools","plan hospitals","plan housing","plan roads","plan public services"],
  population_resource_allocation:["allocate resources","distribute resources","government budgeting based on population","decide where services are needed"],
  population_projection:["population projection","forecast population","predict future population","estimate future population"],
  push_rural_jobs:["few rural jobs","lack of rural employment","limited jobs in rural areas"],
  push_rural_services:["limited rural services","poor rural services","few schools or hospitals in rural areas"],
  pull_urban_jobs:["urban jobs","jobs in towns","employment in cities","more job opportunities in urban areas"],
  pull_urban_services:["better urban services","better schools in cities","better hospitals in towns","more services in urban areas"],
  overcrowding:["overcrowding","crowded cities","housing shortage","urban congestion"],
  urban_pressure_services:["pressure on services","strain on housing","strain on schools","strain on hospitals","pressure on infrastructure"],
  migrant_skills_gain:["host country gains skills","skilled migrants fill vacancies","migrants provide labour","migrants provide labor"],
  migrant_tax_gain:["migrants pay taxes","increase tax revenue","contribute to government revenue"],
  remittance_benefit:["remittances support families","money sent home supports households","remittances provide foreign exchange"],
  family_separation:["family separation","families separated by migration","children left behind","parents live abroad"],
  population_ageing_migration:["working-age people leave","young adults leave","migration contributes to ageing","migration contributes to aging"],
  labour_shortage:["labour shortage","labor shortage","worker shortage","shortage of skilled workers"],
  frictional_unemployment:["frictional unemployment","between jobs","temporarily unemployed while seeking work"],
  cyclical_unemployment:["cyclical unemployment","unemployment due to recession","job losses during economic downturn"],
  skill_training:["skills training","technical training","vocational training","workforce training"],
  scholarships:["scholarships","education grants","fund tertiary study","student financial support"],
  apprenticeships:["apprenticeships","internships","on the job training","on-the-job training"],
  preventive_health:["preventive health","vaccination","health screening","public health programmes","public health programs"],

  // Environment and resources
  watershed_protection:["watershed protection","protect watersheds","protect river catchments","protect water catchment"],
  marine_conservation:["marine conservation","protect coral reefs","protect mangroves","marine protected area","protect fisheries"],
  fishing_limits:["fishing limits","closed fishing season","catch limits","protect fish stocks","prevent overfishing"],
  mining_regulation:["regulate mining","restore mined land","mine rehabilitation","control mining damage"],
  pollution_control:["pollution control","reduce pollution","control industrial waste","prevent water pollution","prevent air pollution"],
  environmental_law:["environmental law","enforce environmental regulations","environmental legislation"],
  climate_education:["climate education","public awareness about climate change","environmental education"],
  climate_resilient_infrastructure:["climate resilient infrastructure","stronger drainage","hurricane resistant buildings","flood defences","flood defenses"],
  rainwater_harvesting:["rainwater harvesting","collect rainwater","collect rain water","catch rainwater","catch rain water","rain water tank","rainwater tank","water storage"],
  drought_resistant_crops:["drought resistant crops","drought-resistant crops","climate resilient crops"],
  early_warning:["early warning system","storm warning system","flood warning","disaster warning","weather alert system"],
  disaster_preparedness:["disaster preparedness","emergency planning","evacuation plan","disaster response plan","community disaster plan"],
  coastal_protection:["coastal protection","sea wall","seawall","mangrove restoration","coastal defence","coastal defense"],
  renewable_policy:["renewable energy policy","solar incentives","wind energy investment","support clean energy"],
  emissions_standard:["emissions standards","vehicle emission limits","industrial emission limits","carbon regulation"],

  // Regional development, industry, ICT and tourism
  integration_barrier_nationalism:["nationalism","strong national identity over regional identity","national interests above regional interests"],
  integration_barrier_cost:["cost of integration","implementation cost","cost of regional programmes","cost of regional programs"],
  integration_barrier_movement:["restrictions on movement","immigration restrictions","limits on free movement","work permit barriers"],
  integration_barrier_trade:["trade restrictions","non tariff barriers","non-tariff barriers","customs delays","regional trade restrictions"],
  caricom_function:["coordinate regional cooperation","promote regional integration","common regional policies","caricom cooperation"],
  csme_function:["single market","free movement under agreed rules","regional market access","movement of goods services capital labour","movement of goods services capital labor"],
  oecs_function:["eastern caribbean cooperation","shared services in eastern caribbean","economic union eastern caribbean","oecs cooperation"],
  ccj_function:["regional court","interprets caricom treaty","final appellate court for participating states","caribbean court"],
  federation_history:["west indies federation","political federation","1958 federation","early regional political union"],
  carifta_history:["carifta","free trade association","caribbean free trade association","regional free trade"],
  ict_remote_services:["remote services","online services","digital services","business process outsourcing","bpo"],
  ict_ecommerce:["e-commerce","ecommerce","online selling","digital marketplace"],
  ict_education:["online learning","distance education","digital education","technology in education"],
  ict_efficiency:["improve efficiency","faster communication","automation","digital records","reduce transaction time"],
  tourism_foreign_exchange:["tourism foreign exchange","visitor spending","tourist spending","foreign currency from tourists"],
  tourism_employment:["tourism jobs","hotel jobs","tour guide jobs","employment from tourism"],
  tourism_leakage:["tourism leakage","profits leave country","imports for tourism","foreign-owned tourism profits"],
  tourism_seasonality:["seasonal tourism","tourism seasonality","jobs fluctuate with tourist season"],
  tourism_environment_pressure:["tourism damages environment","pressure on beaches","waste from tourism","damage to coral reefs"],
  local_linkages:["buy local food","buy from local farmers","buy from local suppliers","buy from local farmers and suppliers","use local suppliers","source from local suppliers","support local farmers","support local craft producers","tourism businesses buy locally"],
  regional_branding:["regional branding","market caribbean jointly","joint tourism marketing","caribbean brand"],
  debt_service:["debt service","interest payments","repay national debt","debt repayment"],
  fiscal_space:["fiscal space","money available for government spending","budget room","public spending capacity"],
});