export const FAMILY_CONCEPTS = Object.freeze({
  family_socialisation:["socialisation","socialization","teach values","teaches values","learn values","learn norms","teach norms","acceptable behaviour","acceptable behavior","prepare children for society","cultural values"],
  family_economic_support:["economic support","financial support","provide money","provide income","meet basic needs","food clothing shelter","food, clothing and shelter","pay household expenses","material support","financial needs"],
  family_emotional_support:["emotional support","love and affection","care and affection","emotional security","companionship","comfort family members","sense of belonging","psychological support"],
  family_protection:["protection","protect children","protect family members","safety and security","keep children safe","shelter from harm","care and protection"],
  family_reproduction:["reproduction","procreation","having children","produce offspring","continuation of society","continuation of family"],
  family_education:["education","educate children","teach children","help with school work","support schooling","learning at home"],
  family_recreation:["recreation","leisure","family activities","spend time together","entertainment"],
  nuclear_family:["nuclear family","parents and children","mother father and children","two parents and children"],
  extended_family:["extended family","grandparents","aunts and uncles","cousins living together","relatives beyond parents and children"],
  single_parent_family:["single parent","one parent household","one-parent family","single mother","single father"],
  sibling_household:["sibling household","brothers and sisters living together","siblings living together"],
  blended_family:["blended family","reconstituted family","step family","stepfamily"],
  visiting_union:["visiting union","visiting relationship"],
  union_separate_households:["partners live separately","separate households","do not share a permanent home","maintain separate homes"],
  common_law_union:["common law","common-law union","cohabitation","consensual union"],
  union_cohabit_unmarried:["living together without marriage","live together without being married","live together without being legally married","share a home without legal marriage","cohabit without marriage","cohabit without legal marriage"],
  legal_marriage:["legal marriage","marriage","married union","formal marriage"],
  union_legal_formal:["legally married","formal legal union","marriage ceremony","recognised by law","recognized by law"],

  women_employment:["women working","women are working","women work outside the home","women working outside the home","women are working outside the home","female employment","more women employed","women in paid employment","women entering workforce","working mothers","women have jobs"],
  women_education:["women educated","girls education","female education","women professionals","women gaining qualifications","equal access to education"],
  changing_gender_norms:["changing gender roles","changing attitudes","gender equality","traditional roles changing","less rigid gender roles","shared gender roles","changing expectations of men and women"],
  technology_remote_work:["technology","work from home","remote work","working from home","technology allows flexible work","flexible work"],
  economic_pressure:["high cost of living","economic pressure","both parents need income","need two incomes","financial pressure","rising household costs"],
  migration_family_change:["migration","parent migrates","emigration","family separation through migration","parents working overseas"],
  role_sharing:["share household duties","share chores","share childcare","men help with housework","fathers care for children","shared responsibilities","shared parenting"],

  budgeting:["budget","budgeting","spending plan","plan expenses","monthly budget","household budget","money plan"],
  financial_counselling:["financial counselling","financial counseling","money management counselling","budget counselling","financial literacy session","financial education"],
  expense_tracking:["track expenses","record spending","monitor spending","keep spending records","list expenses","track household costs"],
  savings_plan:["savings plan","save regularly","emergency fund","set aside money","household savings"],
  parenting_classes:["parenting classes","parent education","parenting workshop","parent training","parent support programme","parent support program"],
  family_meetings:["family meeting","regular family meetings","household meeting","family discussion time","talk as a family"],
  communication_counselling:["communication counselling","family counselling","family counseling","relationship counselling","communication workshop","conflict resolution counselling"],
  active_listening:["active listening","listen carefully","listen to each other","allow each person to speak","hear each other"],
  clear_communication:["clear communication","open communication","talk openly","express feelings","discuss problems calmly","communicate respectfully"],
  improved_money_control:["control spending","reduce overspending","prioritise needs","prioritize needs","avoid unnecessary spending","manage money better","meet expenses"],
  reduced_financial_stress:["reduce financial stress","less money stress","fewer arguments about money","reduce conflict over money"],
  improved_family_relationships:["improve relationships","reduce family conflict","build trust","better understanding","stronger relationship","resolve disagreements"],
  informed_parenting:["better parenting decisions","parents gain skills","parents learn techniques","parents receive guidance","improve parenting skills"],

  domestic_abuse:["domestic abuse","domestic violence","intimate partner violence","family violence","spousal abuse"],
  abuse_reporting:["report abuse","hotline","reporting hotline","confidential reporting","report violence","safe reporting channel"],
  shelters_support:["shelter","safe house","victim support service","support centre","support center","temporary safe accommodation"],
  counselling_services:["counselling","counseling","therapy","psychosocial support","support services"],
  public_education_abuse:["public education campaign","awareness campaign","educate the public","domestic violence awareness"],
  legal_protection:["protection order","restraining order","law enforcement","legal protection","stronger enforcement","enforce domestic violence laws"],
});