export const GOVERNANCE_CONCEPTS = Object.freeze({
  democracy:["democracy","democratic government","government by the people"],
  free_fair_elections:["free and fair elections","fair elections","regular elections","competitive elections"],
  rule_of_law:["rule of law","everyone subject to law","government obeys law"],
  separation_of_powers:["separation of powers","separate arms of government","checks and balances"],
  rights_freedoms:["rights and freedoms","civil rights","fundamental rights","freedom of speech","freedom of association"],
  transparency:["transparency","open government","public information","disclose information","publish spending"],
  accountability:["accountability","answerable to citizens","held responsible","public officials responsible"],
  fptp:["first past the post","first-past-the-post","fptp"],
  largest_votes_wins:["most votes","largest number of votes","highest number of votes","plurality wins"],
  constituency:["constituency","electoral district","seat"],
  voter_apathy:["voter apathy","lack of interest in voting","political apathy","disinterest in elections"],
  civic_education:["civic education","voter education","teach importance of voting","electoral education","citizenship education"],
  school_civics:["school curriculum","teach voting in schools","civics in school","student civic education"],
  youth_social_media:["social media campaign","youth social media","online voter campaign","digital campaign","influencers encourage voting"],
  voter_registration_drive:["voter registration drive","registration campaign","register young voters","help citizens register"],
  polling_access:["easier access to polling","more polling stations","accessible polling stations","transport to polling stations","reduce voting barriers"],
  community_outreach:["community outreach","youth forums","town hall","community meetings","door to door education","public outreach"],
  increased_awareness:["increase awareness","better informed","understand importance","know their rights","know how to vote","understand voting process"],
  increased_participation:["increase participation","more young people vote","higher turnout","encourage voting","more citizens participate"],
  reduced_access_barriers:["reduce barriers","make voting easier","improve access","remove access problems","easier to register","easier to vote"],
  party_r:["party r","r party"],
  party_s:["party s","s party"],
  party_t:["party t","t party"],
  three_seats:["three seats","3 seats","wins three","won three","majority of seats"],
  legislature:["legislature","parliament","law making body","makes laws","passes laws"],
  executive:["executive","cabinet","implements laws","carries out policy","administers government"],
  judiciary:["judiciary","courts","interprets laws","applies laws","judicial branch"],
  redress:["redress","complaint mechanism","appeal","ombudsman","seek remedy","legal remedy"],
});