export const REGIONAL_RESEARCH_CONCEPTS = Object.freeze({
  regional_integration:["regional integration","caribbean integration","regional cooperation","caribbean cooperation"],
  caricom:["caricom","caribbean community"],
  csme:["csme","caricom single market and economy","single market and economy"],
  oecs:["oecs","organisation of eastern caribbean states","organization of eastern caribbean states"],
  ccj:["ccj","caribbean court of justice"],
  carifta:["carifta","caribbean free trade association"],
  west_indies_federation:["west indies federation","federation of the west indies"],
  larger_market:["larger market","bigger market","regional market","expanded market","more customers"],
  economies_scale:["economies of scale","lower unit cost","bulk production","produce at larger scale"],
  pooled_resources:["pool resources","shared resources","combine resources","joint resources","share expertise"],
  bargaining_power:["bargaining power","stronger negotiating position","greater negotiating power","collective voice"],
  free_movement:["free movement","movement of labour","movement of workers","movement of goods","movement of services","movement of capital"],
  regional_supply_chains:["regional supply chain","regional suppliers","regional production network","cross border suppliers","intra regional sourcing"],
  improve_transport_links:["improve transport links","better shipping","regional ferry","better air links","better sea transport","regional logistics"],
  harmonise_customs:["harmonise customs","harmonize customs","common customs procedures","standardise customs","standardize customs","simplify border procedures"],
  remove_trade_barriers:["remove trade barriers","reduce tariffs","reduce regional restrictions","remove customs barriers","facilitate trade"],
  common_standards:["common standards","harmonised standards","harmonized standards","regional standards","mutual recognition"],
  trade_finance:["trade finance","regional financing","business finance","credit for exporters","support exporters"],
  digital_trade:["digital trade","e commerce","e-commerce","online regional marketplace","electronic customs"],
  lower_trade_costs:["lower trade costs","reduce shipping costs","cheaper trade","reduce transaction costs"],
  faster_trade:["faster trade","reduce delays","quicker customs clearance","faster movement of goods"],
  more_regional_trade:["increase regional trade","more intra regional trade","more trade within caribbean","sell more regionally"],
  resilience:["resilience","recover faster","reduce disruption","withstand shocks","disaster resilience"],

  cultural_diversity:["cultural diversity","many cultures","different ethnic traditions","variety of cultures","different cultural groups"],
  cultural_transmission:["cultural transmission","pass culture","pass traditions","transfer culture","teach culture to next generation"],
  family_agent:["family","parents","grandparents","relatives"],
  media_agent:["mass media","social media","television","radio","internet","digital media"],
  education_agent:["school","education system","teachers","educational institutions"],
  religion_agent:["religious institution","church","temple","mosque","religion"],
  artistes_agent:["artistes","artists","musicians","performers","cultural groups"],
  emigrants_agent:["emigrants","diaspora","caribbean migrants","people living overseas"],
  cultural_identity:["cultural identity","sense of identity","caribbean identity","sense of belonging"],
  preserve_culture:["preserve culture","cultural preservation","protect traditions","document heritage","keep traditions alive"],
  promote_culture:["promote culture","market culture","showcase culture","cultural festival","tourism promotion"],

  questionnaire:["questionnaire","survey form","written survey"],
  interview:["interview","interview schedule","oral questions"],
  observation:["observation","observe behaviour","observe behavior"],
  random_sampling:["random sampling","simple random sample","select at random"],
  convenience_sampling:["convenience sampling","available participants","easy to reach participants"],
  purposive_sampling:["purposive sampling","judgment sample","selected for specific characteristics"],
  confidentiality:["confidentiality","keep responses private","do not reveal identities","protect identity"],
  anonymity:["anonymity","anonymous","no names","remove identifiers"],
  reliable_source:["reliable source","credible source","authoritative source","official source"],
  current_source:["current source","recent source","up to date","up-to-date"],
});