export const SOCIETY_POPULATION_CONCEPTS = Object.freeze({
  primary_group:["primary group","close personal group","intimate group","small close group","family and close friends","strong personal relationships"],
  secondary_group:["secondary group","formal task group","goal-oriented group","goal oriented group","impersonal group","less personal relationships"],
  formal_group:["formal group","written rules","official structure","elected officers","defined roles","formal organisation","formal organization"],
  informal_group:["informal group","unwritten rules","friendship group","casual group","no formal structure"],
  voluntary_group:["voluntary group","choose to join","membership by choice","voluntary membership"],
  involuntary_group:["involuntary group","membership not by choice","born into group","compulsory membership"],
  group_cohesion:["group cohesion","unity in a group","group unity","members stick together","sense of belonging in group"],
  shared_goals:["shared goals","common goals","common purpose","same objectives","shared objectives"],
  effective_leadership:["effective leadership","good leadership","strong leader","fair leadership","capable leader"],
  communication_group:["communication","open communication","members communicate","clear communication","good communication"],
  cooperation:["cooperation","co-operate","work together","teamwork","collaboration"],
  commitment:["commitment","committed members","loyalty","group loyalty","dedication"],
  social_control:["social control","control behaviour","control behavior","maintain order","encourage conformity"],
  positive_sanction:["positive sanction","reward","praise","recognition","award for good behaviour","award for good behavior"],
  negative_sanction:["negative sanction","punishment","detention","fine","penalty","disciplinary action"],
  compromise:["compromise","each side gives up something","make concessions","middle ground"],
  negotiation:["negotiation","negotiate","talk to reach agreement","discussion to resolve conflict"],
  mediation:["mediation","mediator","neutral third party","third party helps settle dispute"],
  competition:["competition","compete","rivalry","competing for resources"],
  conflict:["conflict","disagreement","dispute","clash","serious disagreement"],

  social_institution:["social institution","institution","enduring social system","lasting pattern of norms and roles"],
  institution_family:["family institution","family as institution"],
  institution_education:["education institution","educational institution","school system","education system"],
  institution_religion:["religious institution","religion","church institution","faith organisation","faith organization"],
  institution_economy:["economic institution","economy","business and financial institutions"],
  institution_government:["political institution","government institution","government"],
  institution_recreation:["recreational institution","recreation","sport institution","leisure institution"],
  institution_enduring:["enduring","lasts over time","continues over time","persistent social structure"],
  institution_norms:["norms","shared expectations","rules of behaviour","rules of behavior","accepted behaviour","accepted behavior"],
  institution_structure:["structure","hierarchy","roles and positions","organisational structure","organizational structure"],
  institution_function:["function","meets social needs","performs social functions","serves society"],
  interdependence:["interdependence","institutions depend on each other","institutions affect each other","connected institutions"],

  constitutional_monarchy:["constitutional monarchy","monarch as head of state","king or queen as head of state","monarchy under constitution"],
  republic:["republic","non-monarchical head of state","president as head of state","elected or appointed president"],
  head_of_state:["head of state","ceremonial head","state representative"],
  head_of_government:["head of government","prime minister","chief minister","leader of government"],
  constitution:["constitution","supreme law","fundamental law","rules for government","defines government powers"],
  parliament:["parliament","legislature","house of representatives","senate"],
  cabinet:["cabinet","ministers","government ministers","executive cabinet"],
  local_government:["local government","municipal corporation","parish council","city council","local authority"],
  public_services:["public services","government services","education health sanitation","services to citizens"],
  infrastructure:["infrastructure","roads","bridges","water systems","public transport","utilities"],
  national_security:["national security","defence","defense","police protection","protect borders"],
  taxation:["taxation","collect taxes","tax revenue","government taxes"],
  redistribution:["redistribution","social welfare","income support","public assistance","transfer payments"],

  proportional_representation:["proportional representation","pr system","seats based on vote share","representation based on votes"],
  voter_turnout:["voter turnout","turnout","percentage voting","people who cast ballots"],
  eligible_voter:["eligible voter","qualified voter","person entitled to vote"],
  registered_voter:["registered voter","name on voters list","registered electorate"],
  ballot:["ballot","vote paper","ballot paper"],
  polling_station:["polling station","polling place","voting station"],
  manifesto:["manifesto","party manifesto","party programme","party program","election promises"],
  political_party:["political party","party organisation","party organization"],
  opposition:["opposition","opposition party","minority party in parliament"],
  propaganda:["propaganda","biased political message","persuasive political information","one-sided campaign message"],
  fact:["fact","verifiable statement","can be checked","supported by evidence"],
  opinion:["opinion","personal view","judgement","judgment","belief"],
  bias:["bias","biased","one-sided","prejudice","slanted information"],
  source_reliability:["source reliability","credible source","trustworthy source","reliable evidence"],

  census:["census","population census","national headcount","count of population"],
  vital_registration:["vital registration","civil registration","birth and death registration","registration of births and deaths"],
  population:["population","number of people","people living in an area"],
  population_density:["population density","people per square kilometre","people per square kilometer","population divided by area"],
  population_distribution:["population distribution","where people live","spatial distribution of people","settlement pattern"],
  birth_rate:["birth rate","live births per thousand","births per 1000","births per one thousand"],
  death_rate:["death rate","deaths per thousand","deaths per 1000","deaths per one thousand"],
  fertility_rate:["fertility rate","average births per woman","average number of children per woman"],
  mortality_rate:["mortality rate","death rate","rate of deaths"],
  natural_increase:["natural increase","birth rate minus death rate","births exceed deaths","population increase from births and deaths"],
  natural_decrease:["natural decrease","deaths exceed births","negative natural increase"],
  immigration:["immigration","immigrate","move into country","enter country to live","people arriving to live"],
  net_migration:["net migration","immigration minus emigration","difference between immigration and emigration"],
  positive_net_migration:["positive net migration","more immigrants than emigrants","more people enter than leave"],
  negative_net_migration:["negative net migration","more emigrants than immigrants","more people leave than enter"],
  dependency_ratio:["dependency ratio","dependants compared with working age","dependents compared with working age"],
  population_pyramid:["population pyramid","age-sex pyramid","age sex structure diagram"],
  broad_pyramid_base:["broad base","wide base","large young population","high proportion of children","high birth rate"],
  narrow_pyramid_base:["narrow base","small young population","lower birth rate"],
  ageing_population:["ageing population","aging population","large elderly population","growing older population"],
  working_age_population:["working age population","economically active ages","labour force age group","labor force age group"],
  urbanisation:["urbanisation","urbanization","movement to towns and cities","growth of urban population"],
  rural_urban_migration:["rural urban migration","rural-to-urban migration","move from countryside to city","move to towns for work"],
  push_factor:["push factor","reason to leave","unfavourable condition at origin","unfavorable condition at origin"],
  pull_factor:["pull factor","reason attracting migrant","advantage at destination","better opportunity abroad"],
  remittances:["remittances","money sent home","funds sent by migrants","migrant money transfers"],

  human_resource_development:["human resource development","develop people skills","education training and health","improve worker skills"],
  education_training:["education and training","skills training","vocational training","technical training","professional training"],
  health_investment:["health care","healthcare","worker health","public health investment"],
  employment:["employment","paid work","job","employed"],
  self_employment:["self employment","self-employment","own business","work for oneself"],
  unemployment_rate:["unemployment rate","percentage of labour force unemployed","percentage of labor force unemployed"],
  technological_unemployment:["technological unemployment","automation replaces workers","machines replace workers","technology displaces jobs"],
  seasonal_unemployment:["seasonal unemployment","work available only in season","off-season unemployment"],
  structural_unemployment:["structural unemployment","skills mismatch","jobs change but skills do not match"],
  labour_force:["labour force","labor force","working population","employed plus unemployed seeking work"],
  entrepreneurship:["entrepreneurship","entrepreneur","start a business","business ownership"],
  lifelong_learning:["lifelong learning","continuous learning","continuous training","reskilling","upskilling"],

  renewable_resource:["renewable resource","resource can regenerate","replenishable resource"],
  nonrenewable_resource:["non-renewable resource","nonrenewable resource","finite resource","resource cannot quickly regenerate"],
  forest_resource:["forest","forests","timber","woodland"],
  water_resource:["water resource","fresh water","groundwater","rivers"],
  mineral_resource:["minerals","bauxite","gold","mineral resource"],
  fossil_resource:["petroleum","oil","natural gas","fossil fuel resource"],
  fisheries:["fisheries","fish resource","marine fish stocks"],
  sustainable_development:["sustainable development","meet present needs without harming future generations","development for present and future","sustainable use"],
  conservation:["conservation","protect resources","resource conservation","wise use of resources"],
  soil_erosion:["soil erosion","loss of topsoil","topsoil removed","soil washed away"],
  contour_farming:["contour farming","farm along contours","plough along contour","plow along contour"],
  terracing:["terracing","terraces on slopes","step farming"],
  overgrazing:["overgrazing","too many animals grazing","excessive grazing"],
  deforestation_effect:["loss of trees","forest removal","increased runoff","habitat loss"],
  environmental_impact_assessment:["environmental impact assessment","eia","assess environmental effects before project","environmental assessment"],
  mitigation:["mitigation","reduce greenhouse gas emissions","reduce cause of climate change"],
  adaptation:["adaptation","adjust to climate impacts","cope with climate change","reduce vulnerability to impacts"],
  sea_level_rise:["sea level rise","rising sea levels","higher sea level"],
  coastal_erosion:["coastal erosion","beach erosion","loss of coastline"],
  drought:["drought","prolonged dry period","water shortage"],
  flooding:["flooding","floods","inundation"],

  greater_antilles:["greater antilles","jamaica cuba hispaniola puerto rico","large antilles islands"],
  lesser_antilles:["lesser antilles","eastern caribbean island chain","windward and leeward islands"],
  mainland_caribbean:["mainland caribbean","belize guyana suriname","continental caribbean territories"],
  archipelago:["archipelago","group of islands","chain of islands"],
  caribbean_sea:["caribbean sea","sea surrounding much of the caribbean"],
  atlantic_ocean:["atlantic ocean","atlantic"],
  gross_national_income:["gross national income","gni","national income"],
  per_capita_income:["per capita income","income per person","average income per person"],
  infant_mortality:["infant mortality","infant death rate","deaths of infants"],
  school_enrolment:["school enrolment","school enrollment","education participation"],
  foreign_exchange:["foreign exchange","foreign currency earnings","forex earnings"],
  import_substitution:["import substitution","produce locally instead of importing","replace imports with local production"],
  economic_diversification:["economic diversification","diversify economy","develop several industries","reduce dependence on one industry"],
});